// frontend/src/features/task-progress/ui/TaskProgressPanel.vue
<script setup>
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import { useTaskProgress } from '../model/useTaskProgress'
import { formatDurationLong as formatDuration } from '@features/message-display'

defineEmits(['close'])

const {
  allTasks, taskCounts, planTasks, planTaskCounts, hasPlanTasks,
} = useTaskProgress()

// Tick every second to update elapsed time for running tasks
const now = ref(Date.now())
let timer = null

onMounted(() => {
  timer = setInterval(() => { now.value = Date.now() }, 1000)
})

onBeforeUnmount(() => {
  if (timer) { clearInterval(timer); timer = null }
})

function formatElapsed(startTime) {
  const diff = Math.max(0, now.value - startTime)
  return formatDuration(diff)
}

function truncate(text, max = 80) {
  if (!text || text.length <= max) return text
  return text.slice(0, max) + '...'
}

// Segmented progress: percentage for completed and in_progress
const planProgressCompleted = computed(() => {
  const t = planTaskCounts.value.total
  return t > 0 ? (planTaskCounts.value.completed / t * 100) : 0
})
const planProgressActive = computed(() => {
  const t = planTaskCounts.value.total
  return t > 0 ? (planTaskCounts.value.in_progress / t * 100) : 0
})
</script>

<template>
  <div class="task-panel" @click.stop>
    <template v-if="hasPlanTasks">
      <div class="panel-header panel-header--plan">
        <span class="panel-title">Current Plan</span>
        <span class="plan-summary">
          <span class="plan-fraction">{{ planTaskCounts.completed }}<span class="plan-sep">/</span>{{ planTaskCounts.total }}</span>
          <span v-if="planTaskCounts.in_progress > 0" class="count-badge count-running">running</span>
          <span v-else-if="planTaskCounts.completed === planTaskCounts.total" class="count-badge count-done">done</span>
        </span>
      </div>
      <div class="plan-progress-bar">
        <div class="plan-progress-done" :style="{ width: planProgressCompleted + '%' }"></div>
        <div class="plan-progress-active" :style="{ width: planProgressActive + '%' }"></div>
      </div>
      <div class="panel-body plan-body">
        <div
          v-for="(task, index) in planTasks"
          :key="task.id"
          class="plan-item"
          :class="'plan-item--' + task.status"
        >
          <div class="plan-rail">
            <div class="plan-connector plan-connector--top" :class="{ 'plan-connector--hidden': index === 0 }"></div>
            <div class="plan-node">
              <span v-if="task.status === 'in_progress'" class="plan-spinner"></span>
              <svg v-else-if="task.status === 'completed'" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">
                <polyline points="20 6 9 17 4 12"/>
              </svg>
              <span v-else class="plan-dot"></span>
            </div>
            <div class="plan-connector plan-connector--bottom" :class="{ 'plan-connector--hidden': index === planTasks.length - 1 }"></div>
          </div>
          <div class="plan-content">
            <div class="plan-label" :class="{ 'plan-label--done': task.status === 'completed' }">
              {{ task.status === 'in_progress' && task.activeForm ? task.activeForm : task.subject }}
            </div>
            <div v-if="task.status === 'in_progress' && task.subject && task.activeForm" class="plan-detail">
              {{ truncate(task.subject, 120) }}
            </div>
          </div>
          <span class="plan-step">{{ index + 1 }}</span>
        </div>
      </div>
    </template>

    <div class="panel-header" :class="{ 'panel-header--border': hasPlanTasks }">
      <span class="panel-title">Runtime Tasks</span>
      <span class="panel-counts">
        <span v-if="taskCounts.running > 0" class="count-badge count-running">{{ taskCounts.running }} running</span>
        <span v-if="taskCounts.completed > 0" class="count-badge count-done">{{ taskCounts.completed }} done</span>
        <span v-if="taskCounts.failed > 0" class="count-badge count-failed">{{ taskCounts.failed }} failed</span>
      </span>
    </div>
    <div class="panel-body">
      <div v-if="allTasks.length === 0" class="empty-state">
        No runtime tasks
      </div>
      <div
        v-for="task in allTasks"
        :key="task.task_id"
        class="task-item"
        :class="'task-' + task.status"
      >
        <div class="task-icon">
          <span v-if="task.status === 'running'" class="task-spinner"></span>
          <svg v-else-if="task.status === 'completed'" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
            <polyline points="20 6 9 17 4 12"/>
          </svg>
          <svg v-else width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
            <line x1="18" y1="6" x2="6" y2="18"/>
            <line x1="6" y1="6" x2="18" y2="18"/>
          </svg>
        </div>
        <div class="task-content">
          <div class="task-desc">{{ task.description || task.task_id }}</div>
          <div class="task-meta" v-if="task.status === 'running'">
            <span v-if="task.last_tool_name" class="task-tool">{{ task.last_tool_name }}</span>
            <span class="task-elapsed">{{ formatElapsed(task.startTime) }}</span>
          </div>
          <div class="task-meta" v-else-if="task.summary">
            <span class="task-summary">{{ truncate(task.summary) }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.task-panel {
  position: absolute;
  bottom: calc(100% + 8px);
  right: 0;
  width: min(460px, calc(100vw - 32px));
  max-height: min(560px, calc(100vh - 160px));
  background: var(--glass-bg-strong);
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-glass);
  z-index: 200;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  backdrop-filter: blur(var(--glass-blur)) saturate(var(--glass-saturate));
  -webkit-backdrop-filter: blur(var(--glass-blur)) saturate(var(--glass-saturate));
}

/* ── Header ── */
.panel-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 10px 14px;
  border-bottom: 1px solid var(--glass-border);
  background: var(--layer-glass);
  flex-shrink: 0;
}

.panel-header--plan {
  background:
    linear-gradient(135deg, color-mix(in srgb, var(--green) 12%, transparent), transparent),
    var(--layer-glass);
}

.panel-header--border {
  border-top: 1px solid var(--glass-border);
}

.panel-title {
  font-size: 13px;
  font-weight: 600;
  color: var(--text-primary);
}

.plan-summary {
  display: flex;
  align-items: center;
  gap: 8px;
}

.plan-fraction {
  font-size: 13px;
  font-weight: 600;
  color: var(--green);
  font-variant-numeric: tabular-nums;
}

.plan-sep {
  color: var(--text-muted);
  font-weight: 400;
}

.panel-counts {
  display: flex;
  align-items: center;
  gap: 6px;
}

.count-badge {
  font-size: 11px;
  padding: 1px 6px;
  border-radius: var(--radius-sm);
  font-weight: 500;
}

.count-running {
  color: var(--accent);
  background: color-mix(in srgb, var(--accent) 15%, transparent);
}

.count-done {
  color: var(--green);
  background: color-mix(in srgb, var(--green) 15%, transparent);
}

.count-failed {
  color: var(--red);
  background: color-mix(in srgb, var(--red) 15%, transparent);
}

/* ── Segmented progress bar ── */
.plan-progress-bar {
  height: 3px;
  background: color-mix(in srgb, var(--text-muted) 18%, transparent);
  flex-shrink: 0;
  display: flex;
}

.plan-progress-done {
  height: 100%;
  background: var(--green);
  transition: width 0.4s var(--ease-smooth);
}

.plan-progress-active {
  height: 100%;
  background: var(--accent);
  transition: width 0.4s var(--ease-smooth);
  animation: bar-pulse 2s ease-in-out infinite;
}

@keyframes bar-pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}

/* ── Panel body ── */
.panel-body {
  overflow-y: auto;
  max-height: 180px;
  padding: 6px 0;
  flex-shrink: 0;
}

.plan-body {
  max-height: 280px;
  padding: 6px 0 8px;
  background: color-mix(in srgb, var(--green) 4%, transparent);
}

.empty-state {
  padding: 24px;
  text-align: center;
  color: var(--text-muted);
  font-size: 13px;
}

/* ── Plan item (timeline layout) ── */
.plan-item {
  display: grid;
  grid-template-columns: 24px minmax(0, 1fr) auto;
  align-items: stretch;
  column-gap: 8px;
  padding: 6px 14px 6px 10px;
  min-height: 38px;
  transition: background var(--transition-fast), box-shadow var(--transition-fast);
}

.plan-item:hover {
  background: var(--layer-active);
}

.plan-item--in_progress {
  background: color-mix(in srgb, var(--accent) 8%, transparent);
  box-shadow: inset 3px 0 0 var(--accent);
}

/* Timeline rail: connector + node */
.plan-rail {
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 24px;
  flex-shrink: 0;
}

.plan-connector {
  width: 2px;
  flex: 1;
  background: var(--border);
  min-height: 4px;
}

.plan-connector--hidden {
  background: transparent;
}

.plan-item--completed .plan-connector {
  background: var(--green);
}

.plan-item--in_progress .plan-connector--top {
  background: var(--accent);
}

.plan-node {
  width: 20px;
  height: 20px;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

/* Status: pending dot */
.plan-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  border: 2px solid var(--text-muted);
  background: transparent;
}

/* Status: in_progress spinner */
.plan-spinner {
  width: 14px;
  height: 14px;
  border: 2px solid color-mix(in srgb, var(--accent) 30%, transparent);
  border-top-color: var(--accent);
  border-radius: 50%;
  animation: task-spin 0.8s linear infinite;
}

/* Status: completed check */
.plan-item--completed .plan-node {
  color: var(--green);
}

.plan-item--in_progress .plan-node {
  color: var(--accent);
}

.plan-item--pending .plan-node {
  color: var(--text-muted);
}

/* Content */
.plan-content {
  min-width: 0;
  padding: 2px 0;
}

.plan-label {
  font-size: 13px;
  color: var(--text-primary);
  line-height: 1.45;
  overflow-wrap: anywhere;
}

.plan-item--in_progress .plan-label {
  font-weight: 600;
  color: var(--accent);
}

.plan-label--done {
  text-decoration: line-through;
  color: var(--text-muted);
  font-weight: 400;
}

.plan-detail {
  font-size: 11px;
  color: var(--text-secondary);
  line-height: 1.35;
  margin-top: 3px;
  overflow-wrap: anywhere;
}

/* Step number */
.plan-step {
  align-self: flex-start;
  font-size: 10px;
  color: var(--text-muted);
  font-variant-numeric: tabular-nums;
  flex-shrink: 0;
  margin-top: 3px;
  min-width: 20px;
  height: 20px;
  line-height: 20px;
  text-align: center;
  border-radius: 999px;
  background: color-mix(in srgb, var(--text-muted) 8%, transparent);
}

.plan-item--completed .plan-step {
  color: var(--green);
}

.plan-item--in_progress .plan-step {
  color: var(--accent);
}

/* ── Agent task items ── */
.task-item {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  padding: 8px 14px;
  transition: background var(--transition-fast);
}

.task-item:hover {
  background: var(--layer-active);
}

.task-icon {
  flex-shrink: 0;
  width: 18px;
  height: 18px;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-top: 1px;
}

.task-running .task-icon { color: var(--accent); }
.task-completed .task-icon { color: var(--green); }
.task-failed .task-icon,
.task-stopped .task-icon { color: var(--red); }

.task-spinner {
  width: 14px;
  height: 14px;
  border: 2px solid color-mix(in srgb, var(--accent) 30%, transparent);
  border-top-color: var(--accent);
  border-radius: 50%;
  animation: task-spin 0.8s linear infinite;
}

@keyframes task-spin {
  to { transform: rotate(360deg); }
}

.task-content {
  flex: 1;
  min-width: 0;
}

.task-desc {
  font-size: 13px;
  color: var(--text-primary);
  line-height: 1.4;
  word-break: break-word;
}

.task-meta {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 3px;
  font-size: 11px;
  color: var(--text-muted);
}

.task-tool {
  color: var(--accent);
  font-family: var(--font-mono);
}

.task-elapsed {
  color: var(--text-muted);
}

.task-summary {
  color: var(--text-secondary);
  line-height: 1.3;
}
</style>

// frontend-next/src/features/task-progress/ui/TaskProgressPanel.tsx
'use client'

import { useState, useEffect, useRef } from 'react'
import { useTaskProgress } from '../model/useTaskProgress'
import { formatDurationLong } from '@/shared/lib/formatTime'

interface Props {
  messages: unknown[]
  status: string
}

export function TaskProgressPanel({ messages, status }: Props) {
  const { allTasks, taskCounts, planTasks, planTaskCounts, hasPlanTasks } = useTaskProgress(messages as never, status)
  const [now, setNow] = useState(Date.now())
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)

  useEffect(() => {
    timerRef.current = setInterval(() => setNow(Date.now()), 1000)
    return () => {
      if (timerRef.current) clearInterval(timerRef.current)
    }
  }, [])

  function formatElapsed(startTime: number) {
    const diff = Math.max(0, now - startTime)
    return formatDurationLong(diff)
  }

  function truncate(text: string, max = 80) {
    if (!text || text.length <= max) return text
    return text.slice(0, max) + '...'
  }

  const planProgressCompleted = planTaskCounts.total > 0 ? (planTaskCounts.completed / planTaskCounts.total) * 100 : 0
  const planProgressActive = planTaskCounts.total > 0 ? (planTaskCounts.in_progress / planTaskCounts.total) * 100 : 0

  return (
    <div className="task-panel" onClick={(e) => e.stopPropagation()}>
      {hasPlanTasks && (
        <>
          <div className="panel-header panel-header--plan">
            <span className="panel-title">Current Plan</span>
            <span className="plan-summary">
              <span className="plan-fraction">{planTaskCounts.completed}<span className="plan-sep">/</span>{planTaskCounts.total}</span>
              {planTaskCounts.in_progress > 0 && <span className="count-badge count-running">running</span>}
              {planTaskCounts.completed === planTaskCounts.total && planTaskCounts.in_progress === 0 && <span className="count-badge count-done">done</span>}
            </span>
          </div>
          <div className="plan-progress-bar">
            <div className="plan-progress-done" style={{ width: `${planProgressCompleted}%` }} />
            <div className="plan-progress-active" style={{ width: `${planProgressActive}%` }} />
          </div>
          <div className="panel-body plan-body">
            {planTasks.map((task, index) => (
              <div
                key={task.id}
                className={`plan-item plan-item--${task.status}`}
              >
                <div className="plan-rail">
                  <div className={`plan-connector plan-connector--top${index === 0 ? ' plan-connector--hidden' : ''}`} />
                  <div className="plan-node">
                    {task.status === 'in_progress' ? (
                      <span className="plan-spinner" />
                    ) : task.status === 'completed' ? (
                      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                        <polyline points="20 6 9 17 4 12" />
                      </svg>
                    ) : (
                      <span className="plan-dot" />
                    )}
                  </div>
                  <div className={`plan-connector plan-connector--bottom${index === planTasks.length - 1 ? ' plan-connector--hidden' : ''}`} />
                </div>
                <div className="plan-content">
                  <div className={`plan-label${task.status === 'completed' ? ' plan-label--done' : ''}`}>
                    {task.status === 'in_progress' && task.activeForm ? task.activeForm : task.subject}
                  </div>
                  {task.status === 'in_progress' && task.subject && task.activeForm && (
                    <div className="plan-detail">{truncate(task.subject, 120)}</div>
                  )}
                </div>
                <span className="plan-step">{index + 1}</span>
              </div>
            ))}
          </div>
        </>
      )}

      <div className={`panel-header${hasPlanTasks ? ' panel-header--border' : ''}`}>
        <span className="panel-title">Runtime Tasks</span>
        <span className="panel-counts">
          {taskCounts.running > 0 && <span className="count-badge count-running">{taskCounts.running} running</span>}
          {taskCounts.completed > 0 && <span className="count-badge count-done">{taskCounts.completed} done</span>}
          {taskCounts.failed > 0 && <span className="count-badge count-failed">{taskCounts.failed} failed</span>}
        </span>
      </div>
      <div className="panel-body">
        {allTasks.length === 0 ? (
          <div className="task-empty-state">No runtime tasks</div>
        ) : (
          allTasks.map((task) => (
            <div
              key={task.task_id}
              className={`task-item task-${task.status}`}
            >
              <div className="task-icon">
                {task.status === 'running' ? (
                  <span className="task-spinner" />
                ) : task.status === 'completed' ? (
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="20 6 9 17 4 12" />
                  </svg>
                ) : (
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <line x1="18" y1="6" x2="6" y2="18" />
                    <line x1="6" y1="6" x2="18" y2="18" />
                  </svg>
                )}
              </div>
              <div className="task-content">
                <div className="task-desc">{task.description || task.task_id}</div>
                {task.status === 'running' ? (
                  <div className="task-meta">
                    {task.last_tool_name && <span className="task-tool">{task.last_tool_name}</span>}
                    <span className="task-elapsed">{formatElapsed(task.startTime)}</span>
                  </div>
                ) : task.summary ? (
                  <div className="task-meta">
                    <span className="task-summary">{truncate(task.summary)}</span>
                  </div>
                ) : null}
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  )
}
