// frontend-next/src/features/agent-teams/ui/TeamRuntimePanel.tsx
'use client'

import { useState, useEffect, useCallback, useMemo } from 'react'
import { useTeamRuntime } from '../model/useTeamRuntime'
import { getTeamTaskDetail, getSessionArtifacts, cancelTeamTask, retryTeamTask, type TeamTask } from '../api/teamApi'
import { WorkflowEditor } from './WorkflowEditor'

interface Props {
  projectId: string
  sessionId: string
  coordinatorTitle?: string
  onNavigateToSession?: (sessionId: string, projectId: string) => void
}

function patchSet(set: Set<string>, value: string, add: boolean) {
  if (add) set.add(value)
  else set.delete(value)
  return new Set(set)
}

function patchMap<V, K extends string>(map: Map<K, V>, key: K, value: V | undefined): Map<K, V> {
  const next = new Map(map)
  if (value === undefined) next.delete(key as any)
  else next.set(key, value)
  return next
}

export function TeamRuntimePanel({ projectId, sessionId, coordinatorTitle, onNavigateToSession }: Props) {
  const {
    getTasksForSession,
    loadTimeline,
    loadLinkedSessions,
  } = useTeamRuntime()

  const tasks = getTasksForSession(sessionId)

  const [expandedTasks, setExpandedTasks] = useState<Set<string>>(new Set())
  const [taskDetails, setTaskDetails] = useState<Map<string, TeamTask>>(new Map())
  const [taskDetailLoading, setTaskDetailLoading] = useState<Set<string>>(new Set())
  const [taskDetailErrors, setTaskDetailErrors] = useState<Map<string, string>>(new Map())

  const [taskArtifacts, setTaskArtifacts] = useState<Map<string, unknown[]>>(new Map())
  const [artifactLoading, setArtifactLoading] = useState<Set<string>>(new Set())
  const [artifactErrors, setArtifactErrors] = useState<Map<string, string>>(new Map())
  const [diffLoading, setDiffLoading] = useState<Set<string>>(new Set())
  const [taskDiffs, setTaskDiffs] = useState<Map<string, unknown>>(new Map())
  const [diffErrors, setDiffErrors] = useState<Map<string, string>>(new Map())

  const [cancellingTasks, setCancellingTasks] = useState<Set<string>>(new Set())
  const [retryingTasks, setRetryingTasks] = useState<Set<string>>(new Set())

  const [settingsOpen, setSettingsOpen] = useState(false)
  const [settingsSaving, setSettingsSaving] = useState(false)
  const [settingsError, setSettingsError] = useState('')
  const [editConfig, setEditConfig] = useState({
    max_concurrent: 2,
    worker_max_turns: 50,
    worker_max_budget_usd: 1.0,
    max_depth: 5,
    file_checkpointing: true,
  })

  // Load timeline on mount
  useEffect(() => {
    if (projectId && sessionId) {
      loadTimeline(projectId, sessionId)
      loadLinkedSessions(projectId, sessionId)
    }
  }, [projectId, sessionId, loadTimeline, loadLinkedSessions])

  // Workflow steps from tasks
  const workflowSteps = useMemo(() => {
    return tasks.map((t) => ({
      role: t.target_role,
      role_label: t.target_role,
      status: t.status,
    }))
  }, [tasks])

  const taskDetailFor = useCallback(
    (task: TeamTask) => {
      return taskDetails.get(task.task_id) || task
    },
    [taskDetails]
  )

  async function toggleTaskDetail(task: TeamTask) {
    const taskId = task.task_id
    const willOpen = !expandedTasks.has(taskId)
    setExpandedTasks((prev) => patchSet(prev, taskId, willOpen))
    if (!willOpen || taskDetails.has(taskId) || taskDetailLoading.has(taskId)) return

    setTaskDetailLoading((prev) => patchSet(prev, taskId, true))
    setTaskDetailErrors((prev) => { const m = new Map(prev); m.delete(taskId as string); return m })
    try {
      const detail = await getTeamTaskDetail(projectId, taskId)
      setTaskDetails((prev) => patchMap(prev, taskId, detail))
    } catch (err: unknown) {
      setTaskDetailErrors((prev) =>
        patchMap(prev, taskId, err instanceof Error ? err.message : 'Failed to load task detail')
      )
    } finally {
      setTaskDetailLoading((prev) => patchSet(prev, taskId, false))
    }
  }

  async function loadArtifacts(task: TeamTask) {
    const detail = taskDetailFor(task)
    const workerSessionId = detail.worker_session_id || task.worker_session_id
    if (!workerSessionId || artifactLoading.has(task.task_id)) return
    setArtifactLoading((prev) => patchSet(prev, task.task_id, true))
    setArtifactErrors((prev) => { const m = new Map(prev); m.delete(task.task_id as string); return m })
    try {
      const data = await getSessionArtifacts(workerSessionId)
      const artifacts = (data as { artifacts?: unknown[] })?.artifacts || data || []
      setTaskArtifacts((prev) => patchMap(prev, task.task_id, artifacts))
    } catch (err: unknown) {
      setArtifactErrors((prev) =>
        patchMap(prev, task.task_id, err instanceof Error ? err.message : 'Failed to load artifacts')
      )
    } finally {
      setArtifactLoading((prev) => patchSet(prev, task.task_id, false))
    }
  }

  function isTaskCancellable(task: TeamTask) {
    return task.status === 'running' || task.status === 'waiting_for_help'
  }

  async function cancelTaskHandler(task: TeamTask) {
    if (!isTaskCancellable(task) || cancellingTasks.has(task.task_id)) return
    setCancellingTasks((prev) => patchSet(prev, task.task_id, true))
    try {
      await cancelTeamTask(projectId, task.task_id)
    } catch (err: unknown) {
      setTaskDetailErrors((prev) =>
        patchMap(prev, task.task_id, err instanceof Error ? err.message : 'Cancel failed')
      )
    } finally {
      setCancellingTasks((prev) => patchSet(prev, task.task_id, false))
    }
  }

  function isTaskRetryable(task: TeamTask) {
    return task.status === 'failed' || task.status === 'cancelled'
  }

  async function retryTaskHandler(task: TeamTask) {
    if (!isTaskRetryable(task) || retryingTasks.has(task.task_id)) return
    setRetryingTasks((prev) => patchSet(prev, task.task_id, true))
    try {
      await retryTeamTask(projectId, task.task_id)
    } catch (err: unknown) {
      setTaskDetailErrors((prev) =>
        patchMap(prev, task.task_id, err instanceof Error ? err.message : 'Retry failed')
      )
    } finally {
      setRetryingTasks((prev) => patchSet(prev, task.task_id, false))
    }
  }

  function statusIcon(status: string) {
    const map: Record<string, string> = {
      pending: '○',
      running: '▶',
      completed: '✓',
      failed: '✗',
      cancelled: '⊘',
      waiting_for_help: '?',
    }
    return map[status] || status
  }

  function openWorkerForTask(task: TeamTask) {
    const detail = taskDetailFor(task)
    const workerSessionId = detail.worker_session_id || task.worker_session_id
    if (!workerSessionId) return
    onNavigateToSession?.(workerSessionId, detail.target_project_id || task.target_project_id)
  }

  function formatCost(usd: number | undefined) {
    if (!usd || usd <= 0) return ''
    if (usd < 0.01) return '<$0.01'
    return `$${usd.toFixed(2)}`
  }

  function openSettings() {
    setEditConfig({
      max_concurrent: 2,
      worker_max_turns: 50,
      worker_max_budget_usd: 1.0,
      max_depth: 5,
      file_checkpointing: true,
    })
    setSettingsError('')
    setSettingsOpen(true)
  }

  async function saveSettings() {
    if (settingsSaving) return
    setSettingsSaving(true)
    setSettingsError('')
    try {
      // TODO: call updateTeamConfig API
      setSettingsOpen(false)
    } catch (err: unknown) {
      setSettingsError(err instanceof Error ? err.message : 'Failed to save settings')
    } finally {
      setSettingsSaving(false)
    }
  }

  return (
    <div className="team-runtime-panel">
      {/* Coordinator header */}
      <div className="panel-header">
        <div className="coordinator-info">
          <span className="coordinator-label">Coordinator</span>
          <span className="coordinator-title">{coordinatorTitle || sessionId}</span>
        </div>
        <div className="coordinator-actions">
          <button className="panel-btn" onClick={() => onNavigateToSession?.(sessionId, projectId)} title="Navigate to coordinator session">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" /><polyline points="15 3 21 3 21 9" /><line x1="10" y1="14" x2="21" y2="3" />
            </svg>
          </button>
          <button className="panel-btn" onClick={openSettings} title="Settings">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="12" cy="12" r="3" /><path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42" />
            </svg>
          </button>
        </div>
      </div>

      {/* Task count */}
      <div className="panel-section">
        <span className="section-title">Tasks ({tasks.length})</span>
      </div>

      {/* Workflow Visualization */}
      {workflowSteps.length > 0 && (
        <div className="panel-section">
          <h4 className="section-title">Workflow</h4>
          <WorkflowEditor
            mode="delegation"
            steps={workflowSteps as Array<{ role: string; role_label?: string }>}
            tasks={tasks}
          />
        </div>
      )}

      {/* Task list */}
      <div className="panel-section task-list">
        {tasks.map((task) => {
          const detail = taskDetailFor(task)
          const isExpanded = expandedTasks.has(task.task_id)
          return (
            <div key={task.task_id} className="task-card">
              <div className="task-header" onClick={() => toggleTaskDetail(task)}>
                <span className={`task-status task-status--${task.status}`}>
                  {statusIcon(task.status)}
                </span>
                <span className="task-role">{task.target_role}</span>
                <span className="task-cost">{formatCost(task.cost_usd)}</span>
                <svg
                  width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"
                  className={`task-chevron${isExpanded ? ' task-chevron--open' : ''}`}
                >
                  <polyline points="6 9 12 15 18 9" />
                </svg>
              </div>

              {isExpanded && (
                <div className="task-detail">
                  {taskDetailLoading.has(task.task_id) && <div className="task-loading">Loading...</div>}
                  {taskDetailErrors.get(task.task_id) && (
                    <div className="task-error">{taskDetailErrors.get(task.task_id)}</div>
                  )}

                  {/* Status text */}
                  <div className="detail-field">
                    <span className="detail-label">Status</span>
                    <span className={`task-status task-status--${task.status}`}>{task.status}</span>
                  </div>

                  {/* Prompt */}
                  {task.prompt && (
                    <div className="detail-field">
                      <span className="detail-label">Prompt</span>
                      <span className="detail-value detail-value--code">{task.prompt}</span>
                    </div>
                  )}

                  {/* Result */}
                  {detail.result_summary && (
                    <div className="detail-field">
                      <span className="detail-label">Result</span>
                      <span className="detail-value">{detail.result_summary}</span>
                    </div>
                  )}

                  {/* Error */}
                  {task.error_message && (
                    <div className="detail-field">
                      <span className="detail-label">Error</span>
                      <span className="detail-value detail-value--error">{task.error_message}</span>
                    </div>
                  )}

                  {/* Detail info */}
                  {detail.worker_session_id && (
                    <div className="detail-field">
                      <span className="detail-label">Worker</span>
                      <button className="detail-link" onClick={() => openWorkerForTask(task)}>
                        {detail.worker_session_id.slice(0, 8)}...
                      </button>
                    </div>
                  )}
                  {task.depth > 0 && (
                    <div className="detail-field">
                      <span className="detail-label">Depth</span>
                      <span className="detail-value">{task.depth}</span>
                    </div>
                  )}
                  {task.duration_ms != null && (
                    <div className="detail-field">
                      <span className="detail-label">Duration</span>
                      <span className="detail-value">{Math.round(task.duration_ms / 1000)}s</span>
                    </div>
                  )}

                  {/* Actions */}
                  <div className="task-actions">
                    {isTaskCancellable(task) && (
                      <button
                        className="task-action-btn task-action-btn--cancel"
                        onClick={() => cancelTaskHandler(task)}
                        disabled={cancellingTasks.has(task.task_id)}
                      >
                        {cancellingTasks.has(task.task_id) ? 'Cancelling...' : 'Cancel'}
                      </button>
                    )}
                    {isTaskRetryable(task) && (
                      <button
                        className="task-action-btn task-action-btn--retry"
                        onClick={() => retryTaskHandler(task)}
                        disabled={retryingTasks.has(task.task_id)}
                      >
                        {retryingTasks.has(task.task_id) ? 'Retrying...' : 'Retry'}
                      </button>
                    )}
                    {detail.worker_session_id && (
                      <button className="task-action-btn" onClick={() => loadArtifacts(task)}>
                        Artifacts
                      </button>
                    )}
                  </div>

                  {/* Artifacts */}
                  {taskArtifacts.has(task.task_id) && (
                    <div className="task-artifacts">
                      <span className="detail-label">Artifacts</span>
                      <div className="artifact-list">
                        {(taskArtifacts.get(task.task_id) || []).map((artifact, i) => {
                          const a = artifact as { path?: string; file_path?: string; value?: string }
                          const path = a.path || a.file_path || a.value || ''
                          return (
                            <div key={i} className="artifact-item">
                              <span className="artifact-path">{path}</span>
                            </div>
                          )
                        })}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          )
        })}

        {tasks.length === 0 && (
          <div className="task-empty">No active tasks</div>
        )}
      </div>

      {/* Settings dialog */}
      {settingsOpen && (
        <div className="settings-overlay" onClick={() => setSettingsOpen(false)}>
          <div className="settings-dialog" onClick={(e) => e.stopPropagation()}>
            <h3>Team Settings</h3>
            <div className="settings-field">
              <label>Max Concurrent</label>
              <input
                type="number"
                value={editConfig.max_concurrent}
                onChange={(e) => setEditConfig((p) => ({ ...p, max_concurrent: parseInt(e.target.value) || 2 }))}
              />
            </div>
            <div className="settings-field">
              <label>Worker Max Turns</label>
              <input
                type="number"
                value={editConfig.worker_max_turns}
                onChange={(e) => setEditConfig((p) => ({ ...p, worker_max_turns: parseInt(e.target.value) || 50 }))}
              />
            </div>
            <div className="settings-field">
              <label>Worker Max Budget (USD)</label>
              <input
                type="number"
                step="0.1"
                value={editConfig.worker_max_budget_usd}
                onChange={(e) => setEditConfig((p) => ({ ...p, worker_max_budget_usd: parseFloat(e.target.value) || 1.0 }))}
              />
            </div>
            <div className="settings-field">
              <label>Max Depth</label>
              <input
                type="number"
                value={editConfig.max_depth}
                onChange={(e) => setEditConfig((p) => ({ ...p, max_depth: parseInt(e.target.value) || 5 }))}
              />
            </div>
            {settingsError && <div className="settings-error">{settingsError}</div>}
            <div className="settings-actions">
              <button onClick={() => setSettingsOpen(false)}>Cancel</button>
              <button onClick={saveSettings} disabled={settingsSaving}>
                {settingsSaving ? 'Saving...' : 'Save'}
              </button>
            </div>
          </div>
        </div>
      )}

      <style>{`
        .team-runtime-panel {
          border: 1px solid var(--glass-border);
          border-radius: var(--radius-lg);
          background: var(--bg-secondary);
          overflow: hidden;
        }
        .panel-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 8px 12px;
          background: var(--bg-tertiary);
          border-bottom: 1px solid var(--border);
        }
        .coordinator-info { display: flex; flex-direction: column; gap: 1px; }
        .coordinator-label { font-size: 10px; font-weight: 600; color: var(--text-muted); text-transform: uppercase; }
        .coordinator-title { font-size: 12px; color: var(--text-primary); }
        .coordinator-actions { display: flex; gap: 4px; }
        .panel-btn {
          display: flex; align-items: center; justify-content: center;
          width: 28px; height: 28px;
          background: transparent; border: 1px solid transparent;
          border-radius: var(--radius-sm); color: var(--text-secondary); cursor: pointer;
        }
        .panel-btn:hover { background: var(--bg-hover); color: var(--accent); }
        .panel-section { padding: 8px 12px; }
        .section-title { font-size: 11px; font-weight: 600; color: var(--text-muted); text-transform: uppercase; margin: 0 0 6px; }
        .task-list { display: flex; flex-direction: column; gap: 4px; }
        .task-card {
          border: 1px solid var(--border);
          border-radius: var(--radius-md);
          overflow: hidden;
        }
        .task-header {
          display: flex; align-items: center; gap: 8px;
          padding: 6px 10px; cursor: pointer;
          background: var(--bg-secondary);
          transition: background var(--transition-fast);
        }
        .task-header:hover { background: var(--bg-hover); }
        .task-status { font-size: 12px; font-weight: 600; }
        .task-status--pending { color: var(--text-muted); }
        .task-status--running { color: var(--accent); }
        .task-status--completed { color: var(--green, #98c379); }
        .task-status--failed { color: var(--red, #e06c75); }
        .task-status--cancelled { color: var(--text-muted); text-decoration: line-through; }
        .task-status--waiting_for_help { color: var(--yellow, #e5c07b); }
        .task-role { flex: 1; font-size: 13px; font-weight: 500; color: var(--text-primary); }
        .task-cost { font-size: 11px; color: var(--text-muted); }
        .task-chevron {
          transition: transform 0.15s; flex-shrink: 0;
        }
        .task-chevron--open { transform: rotate(180deg); }
        .task-detail {
          padding: 8px 10px;
          border-top: 1px solid var(--border-subtle);
          display: flex; flex-direction: column; gap: 6px;
        }
        .task-loading, .task-error { font-size: 12px; padding: 4px 0; }
        .task-error { color: var(--red, #e06c75); }
        .detail-field { display: flex; gap: 8px; align-items: flex-start; }
        .detail-label {
          font-size: 11px; font-weight: 600; color: var(--text-muted);
          min-width: 60px; flex-shrink: 0;
        }
        .detail-value { font-size: 12px; color: var(--text-primary); }
        .detail-value--code {
          font-family: var(--font-mono);
          font-size: 11px;
          background: var(--bg-tertiary);
          padding: 2px 6px;
          border-radius: var(--radius-sm);
          max-height: 60px;
          overflow: hidden;
        }
        .detail-value--error { color: var(--red, #e06c75); }
        .detail-link {
          font-size: 12px; color: var(--accent);
          background: none; border: none; cursor: pointer; padding: 0;
        }
        .detail-link:hover { text-decoration: underline; }
        .task-actions { display: flex; gap: 4px; margin-top: 4px; }
        .task-action-btn {
          padding: 3px 8px; font-size: 11px;
          border: 1px solid var(--glass-border); border-radius: var(--radius-sm);
          background: var(--bg-hover); color: var(--text-secondary); cursor: pointer;
        }
        .task-action-btn:hover { color: var(--accent); }
        .task-action-btn:disabled { opacity: 0.5; cursor: not-allowed; }
        .task-action-btn--cancel { color: var(--red, #e06c75); }
        .task-action-btn--retry { color: var(--accent); }
        .task-empty { padding: 16px 0; text-align: center; color: var(--text-muted); font-size: 13px; }
        .task-artifacts { margin-top: 4px; }
        .artifact-list { display: flex; flex-direction: column; gap: 2px; margin-top: 4px; }
        .artifact-item { padding: 2px 6px; font-size: 11px; color: var(--text-secondary); }
        .artifact-path { font-family: var(--font-mono); }
        .settings-overlay {
          position: fixed; inset: 0; z-index: 1000;
          background: var(--overlay-glass);
          display: flex; align-items: center; justify-content: center;
        }
        .settings-dialog {
          background: var(--bg-secondary); border-radius: var(--radius-lg);
          border: 1px solid var(--glass-border);
          padding: 20px; width: 360px; display: flex; flex-direction: column; gap: 12px;
        }
        .settings-dialog h3 { margin: 0; font-size: 15px; color: var(--text-primary); }
        .settings-field { display: flex; flex-direction: column; gap: 4px; }
        .settings-field label { font-size: 12px; color: var(--text-secondary); }
        .settings-field input {
          padding: 6px 10px; font-size: 13px;
          background: var(--bg-input); border: 1px solid var(--glass-border);
          border-radius: var(--radius-sm); color: var(--text-primary);
        }
        .settings-error { color: var(--red, #e06c75); font-size: 12px; }
        .settings-actions { display: flex; justify-content: flex-end; gap: 8px; margin-top: 8px; }
        .settings-actions button {
          padding: 6px 14px; font-size: 12px; border-radius: var(--radius-sm);
          border: 1px solid var(--glass-border); cursor: pointer;
        }
        .settings-actions button:last-child { background: var(--accent); color: #fff; border-color: var(--accent); }
      `}</style>
    </div>
  )
}

// frontend/src/features/agent-teams/ui/TeamRuntimePanel.vue
<script setup>
import { ref, computed, watch, onMounted } from 'vue'
import { useTeamRuntime } from '../model/useTeamRuntime'
import { getProject } from '@entities/project'
import { getWorkspaceDiff } from '@entities/project/api/projectApi'
import { useCancellableAsync } from '@shared/lib/useCancellableAsync'
import { formatDuration } from '@features/message-display'
import { getSessionArtifacts, getTeamTaskDetail, cancelTeamTask } from '../api/teamApi'
import WorkflowEditor from './WorkflowEditor.vue'

const props = defineProps({
  projectId: { type: String, required: true },
  sessionId: { type: String, required: true },
  visible: { type: Boolean, default: false },
})

const emit = defineEmits(['navigate-to-session', 'close'])

const { getTasksForSession, loadTimeline, loadLinkedSessions, getWorkerSessionState, displayStatusFromTaskStatus } = useTeamRuntime()

const tasks = computed(() => getTasksForSession(props.sessionId).value)
const linkedSessions = ref([])
const loading = ref(false)
const teamConfig = ref(null)
const refreshTracker = useCancellableAsync()
const expandedTasks = ref(new Set())
const taskDetails = ref(new Map())
const taskDetailLoading = ref(new Set())
const taskDetailErrors = ref(new Map())
const taskArtifacts = ref(new Map())
const artifactLoading = ref(new Set())
const artifactErrors = ref(new Map())
const taskDiffs = ref(new Map())
const diffLoading = ref(new Set())
const diffErrors = ref(new Map())

const workflowSteps = computed(() => {
  if (!teamConfig.value) return []
  const mode = teamConfig.value.mode || 'delegation'
  return mode === 'delegation'
    ? (teamConfig.value.pipeline || [])
    : (teamConfig.value.members || [])
})

const workflowMode = computed(() => teamConfig.value?.mode || 'delegation')

const displaySessions = computed(() => linkedSessions.value.map(session => {
  const liveState = getWorkerSessionState(session.session_id) || {}
  const displayStatus = liveState.display_status || session.display_status || displayStatusFromTaskStatus(session.task_status) || session.status || 'idle'
  return {
    ...session,
    ...liveState,
    display_status: displayStatus,
    waiting_for_input: liveState.waiting_for_input ?? session.waiting_for_input ?? displayStatus === 'waiting_input',
  }
}))

async function refresh() {
  if (!props.sessionId || !props.projectId) return
  const version = refreshTracker.start()
  loading.value = true
  try {
    await loadTimeline(props.projectId, props.sessionId)
    if (!refreshTracker.isCurrent(version)) return
    linkedSessions.value = await loadLinkedSessions(props.projectId, props.sessionId)
    if (!refreshTracker.isCurrent(version)) return
    try {
      const project = await getProject(props.projectId)
      if (!refreshTracker.isCurrent(version)) return
      teamConfig.value = project?.team_config || null
    } catch {}
  } finally {
    if (refreshTracker.isCurrent(version)) loading.value = false
  }
}

watch(() => props.visible, (val) => {
  if (val) refresh()
})

watch(() => props.sessionId, () => {
  if (props.visible) refresh()
})

onMounted(() => {
  if (props.visible) refresh()
})

function patchSet(refValue, value, present) {
  const next = new Set(refValue.value)
  if (present) next.add(value)
  else next.delete(value)
  refValue.value = next
}

function patchMap(refValue, key, value) {
  const next = new Map(refValue.value)
  if (value === undefined) next.delete(key)
  else next.set(key, value)
  refValue.value = next
}

function taskDetailFor(task) {
  return taskDetails.value.get(task.task_id) || task
}

async function toggleTaskDetail(task) {
  const taskId = task.task_id
  const willOpen = !expandedTasks.value.has(taskId)
  patchSet(expandedTasks, taskId, willOpen)
  if (!willOpen || taskDetails.value.has(taskId) || taskDetailLoading.value.has(taskId)) return

  patchSet(taskDetailLoading, taskId, true)
  patchMap(taskDetailErrors, taskId, undefined)
  try {
    const detail = await getTeamTaskDetail(props.projectId, taskId)
    patchMap(taskDetails, taskId, detail)
  } catch (err) {
    patchMap(taskDetailErrors, taskId, err.message || 'Failed to load task detail')
  } finally {
    patchSet(taskDetailLoading, taskId, false)
  }
}

async function loadArtifacts(task) {
  const detail = taskDetailFor(task)
  const workerSessionId = detail.worker_session_id || task.worker_session_id
  if (!workerSessionId || artifactLoading.value.has(task.task_id)) return
  patchSet(artifactLoading, task.task_id, true)
  patchMap(artifactErrors, task.task_id, undefined)
  try {
    const data = await getSessionArtifacts(workerSessionId)
    patchMap(taskArtifacts, task.task_id, data?.artifacts || data || [])
  } catch (err) {
    patchMap(artifactErrors, task.task_id, err.message || 'Failed to load artifacts')
  } finally {
    patchSet(artifactLoading, task.task_id, false)
  }
}

function normalizeWorkspacePath(path, task) {
  if (!path) return ''
  const value = String(path)
  if (!value.startsWith('/')) return value.replace(/^\.\//, '')
  const detail = taskDetailFor(task)
  const projectDir = detail.target_project_dir || ''
  if (projectDir && value.startsWith(projectDir + '/')) {
    return value.slice(projectDir.length + 1)
  }
  return ''
}

function diffKey(task, path) {
  return `${task.task_id}:${path}`
}

async function loadDiff(task, path) {
  const relativePath = normalizeWorkspacePath(path, task)
  if (!relativePath) return
  const key = diffKey(task, relativePath)
  if (diffLoading.value.has(key)) return
  if (taskDiffs.value.has(key)) {
    patchMap(taskDiffs, key, undefined)
    return
  }
  patchSet(diffLoading, key, true)
  patchMap(diffErrors, key, undefined)
  try {
    const diff = await getWorkspaceDiff(task.target_project_id, relativePath)
    patchMap(taskDiffs, key, diff)
  } catch (err) {
    patchMap(diffErrors, key, err.message || 'Failed to load diff')
  } finally {
    patchSet(diffLoading, key, false)
  }
}

function artifactPath(artifact) {
  return artifact.path || artifact.file_path || artifact.value || ''
}

function copyText(text) {
  if (!text) return
  navigator.clipboard?.writeText(text)
}

function openWorkerForTask(task) {
  const detail = taskDetailFor(task)
  const sessionId = detail.worker_session_id || task.worker_session_id
  if (!sessionId) return
  emit('navigate-to-session', {
    sessionId,
    projectId: detail.target_project_id || task.target_project_id,
  })
}

function formatCost(usd) {
  if (!usd || usd <= 0) return ''
  return usd < 0.01 ? '<$0.01' : `$${usd.toFixed(2)}`
}

function isTaskCancellable(task) {
  return task.status === 'running' || task.status === 'waiting_for_help'
}

const cancellingTasks = ref(new Set())

async function cancelTask(task) {
  if (!isTaskCancellable(task) || cancellingTasks.value.has(task.task_id)) return
  patchSet(cancellingTasks, task.task_id, true)
  try {
    await cancelTeamTask(props.projectId, task.task_id)
  } catch (err) {
    patchMap(taskDetailErrors, task.task_id, err.message || 'Cancel failed')
  } finally {
    patchSet(cancellingTasks, task.task_id, false)
  }
}

function statusIcon(status) {
  const map = {
    pending: '…',
    idle: '○',
    running: '↻',
    waiting_input: '!',
    completed: '✓',
    failed: '×',
    cancelled: '−',
    waiting_for_help: '?',
  }
  return map[status] || '?'
}

function statusLabel(status) {
  const map = {
    pending: 'Pending',
    idle: 'Idle',
    running: 'Running',
    waiting_input: 'Waiting input',
    completed: 'Completed',
    failed: 'Failed',
    cancelled: 'Cancelled',
    waiting_for_help: 'Waiting help',
  }
  return map[status] || status
}

function navigateToWorker(session) {
  emit('navigate-to-session', {
    sessionId: session.session_id,
    projectId: session.project_id,
  })
}
</script>

<template>
  <div v-if="visible" class="team-panel">
    <div class="panel-header">
      <h3 class="panel-title">Team Runtime</h3>
      <button class="panel-close" @click="emit('close')" aria-label="Close">&times;</button>
    </div>

    <div class="panel-body">
      <!-- Workflow Visualization -->
      <section v-if="workflowSteps.length > 0" class="panel-section">
        <h4 class="section-title">Workflow</h4>
        <WorkflowEditor
          :mode="workflowMode"
          :steps="workflowSteps"
          :tasks="tasks"
          :editable="false"
        />
      </section>

      <!-- Pipeline / Tasks -->
      <section class="panel-section">
        <h4 class="section-title">Tasks</h4>
        <div v-if="loading && tasks.length === 0" class="loading-text">Loading...</div>
        <div v-else-if="tasks.length === 0" class="empty-text">No tasks dispatched yet</div>
        <div v-else class="task-list">
          <div
            v-for="task in tasks"
            :key="task.task_id"
            class="task-item"
            :class="'task-' + task.status"
          >
            <span class="task-icon">{{ statusIcon(task.status) }}</span>
            <div class="task-info">
              <span class="task-role">{{ task.target_role }}</span>
              <span class="task-prompt">{{ task.prompt }}</span>
              <span v-if="task.duration_ms" class="task-duration">{{ formatDuration(task.duration_ms) }}</span>
              <span v-if="task.cost_usd" class="task-cost">{{ formatCost(task.cost_usd) }}</span>
              <div class="task-actions">
                <button class="task-action" @click="toggleTaskDetail(task)">
                  {{ expandedTasks.has(task.task_id) ? 'Hide' : 'Detail' }}
                </button>
                <button class="task-action" :disabled="!(taskDetailFor(task).worker_session_id || task.worker_session_id)" @click="openWorkerForTask(task)">
                  Worker
                </button>
                <button class="task-action" :disabled="!(taskDetailFor(task).worker_session_id || task.worker_session_id)" @click="loadArtifacts(task)">
                  Artifacts
                </button>
                <button
                  v-if="isTaskCancellable(task)"
                  class="task-action task-action--danger"
                  :disabled="cancellingTasks.has(task.task_id)"
                  @click="cancelTask(task)"
                >
                  {{ cancellingTasks.has(task.task_id) ? 'Cancelling...' : 'Cancel' }}
                </button>
              </div>
              <div v-if="expandedTasks.has(task.task_id)" class="task-detail">
                <div v-if="taskDetailLoading.has(task.task_id)" class="loading-text">Loading detail...</div>
                <div v-else-if="taskDetailErrors.has(task.task_id)" class="detail-error">{{ taskDetailErrors.get(task.task_id) }}</div>
                <template v-else>
                  <div class="detail-section">
                    <span class="detail-label">Prompt</span>
                    <p class="detail-text">{{ taskDetailFor(task).prompt }}</p>
                  </div>
                  <div v-if="taskDetailFor(task).context" class="detail-section">
                    <span class="detail-label">Context</span>
                    <pre class="detail-pre">{{ taskDetailFor(task).context }}</pre>
                  </div>
                  <div v-if="taskDetailFor(task).result_summary" class="detail-section">
                    <span class="detail-label">Result</span>
                    <p class="detail-text">{{ taskDetailFor(task).result_summary }}</p>
                  </div>
                  <div v-if="taskDetailFor(task).error_message" class="detail-section">
                    <span class="detail-label">Error</span>
                    <p class="detail-error">{{ taskDetailFor(task).error_message }}</p>
                  </div>
                  <div v-if="taskDetailFor(task).result_data?.files_changed?.length" class="detail-section">
                    <span class="detail-label">Files</span>
                    <ul class="detail-list">
                      <li v-for="f in taskDetailFor(task).result_data.files_changed" :key="f" class="file-row">
                        <span>{{ f }}</span>
                        <button
                          v-if="normalizeWorkspacePath(f, task)"
                          class="inline-action"
                          @click="loadDiff(task, f)"
                        >Diff</button>
                      </li>
                    </ul>
                    <div
                      v-for="f in taskDetailFor(task).result_data.files_changed"
                      :key="f + ':diff'"
                      class="diff-block"
                    >
                      <template v-if="normalizeWorkspacePath(f, task) && taskDiffs.has(diffKey(task, normalizeWorkspacePath(f, task)))">
                        <span class="detail-label">Current workspace diff: {{ normalizeWorkspacePath(f, task) }}</span>
                        <pre class="diff-pre">{{ taskDiffs.get(diffKey(task, normalizeWorkspacePath(f, task)))?.patch || taskDiffs.get(diffKey(task, normalizeWorkspacePath(f, task)))?.patch_excerpt || 'No workspace diff for this file' }}</pre>
                      </template>
                      <div v-else-if="normalizeWorkspacePath(f, task) && diffLoading.has(diffKey(task, normalizeWorkspacePath(f, task)))" class="loading-text">Loading diff...</div>
                      <div v-else-if="normalizeWorkspacePath(f, task) && diffErrors.has(diffKey(task, normalizeWorkspacePath(f, task)))" class="detail-error">{{ diffErrors.get(diffKey(task, normalizeWorkspacePath(f, task))) }}</div>
                    </div>
                  </div>
                  <div v-if="taskDetailFor(task).result_data?.issues?.length" class="detail-section">
                    <span class="detail-label">Issues</span>
                    <ul class="detail-list detail-list--warn">
                      <li v-for="(issue, i) in taskDetailFor(task).result_data.issues" :key="i">{{ issue }}</li>
                    </ul>
                  </div>
                  <div v-if="taskDetailFor(task).result_data?.next_steps?.length" class="detail-section">
                    <span class="detail-label">Next</span>
                    <ul class="detail-list">
                      <li v-for="(step, i) in taskDetailFor(task).result_data.next_steps" :key="i">{{ step }}</li>
                    </ul>
                  </div>
                  <div class="detail-section detail-meta">
                    <span>Task {{ taskDetailFor(task).task_id }}</span>
                    <span v-if="taskDetailFor(task).cost_usd">Cost {{ formatCost(taskDetailFor(task).cost_usd) }}</span>
                    <span v-if="taskDetailFor(task).trace_id">Trace {{ taskDetailFor(task).trace_id }}</span>
                    <span v-if="taskDetailFor(task).parent_task_id">Parent {{ taskDetailFor(task).parent_task_id }}</span>
                    <span>Depth {{ taskDetailFor(task).depth || 0 }}</span>
                  </div>
                </template>
                <div v-if="artifactLoading.has(task.task_id)" class="loading-text">Loading artifacts...</div>
                <div v-if="artifactErrors.has(task.task_id)" class="detail-error">{{ artifactErrors.get(task.task_id) }}</div>
                <div v-if="taskArtifacts.has(task.task_id)" class="detail-section">
                  <span class="detail-label">Artifacts</span>
                  <div v-if="taskArtifacts.get(task.task_id).length === 0" class="empty-text">No artifacts found</div>
                  <ul v-else class="detail-list">
                    <li v-for="(artifact, i) in taskArtifacts.get(task.task_id)" :key="i" class="file-row">
                      <span>{{ artifactPath(artifact) || artifact.label || 'artifact' }}</span>
                      <button class="inline-action" @click="copyText(artifactPath(artifact))">Copy</button>
                      <button
                        v-if="normalizeWorkspacePath(artifactPath(artifact), task)"
                        class="inline-action"
                        @click="loadDiff(task, artifactPath(artifact))"
                      >Diff</button>
                    </li>
                  </ul>
                  <div
                    v-for="(artifact, i) in taskArtifacts.get(task.task_id)"
                    :key="i + ':artifact-diff'"
                    class="diff-block"
                  >
                    <template v-if="normalizeWorkspacePath(artifactPath(artifact), task) && taskDiffs.has(diffKey(task, normalizeWorkspacePath(artifactPath(artifact), task)))">
                      <span class="detail-label">Current workspace diff: {{ normalizeWorkspacePath(artifactPath(artifact), task) }}</span>
                      <pre class="diff-pre">{{ taskDiffs.get(diffKey(task, normalizeWorkspacePath(artifactPath(artifact), task)))?.patch || taskDiffs.get(diffKey(task, normalizeWorkspacePath(artifactPath(artifact), task)))?.patch_excerpt || 'No workspace diff for this file' }}</pre>
                    </template>
                    <div v-else-if="normalizeWorkspacePath(artifactPath(artifact), task) && diffLoading.has(diffKey(task, normalizeWorkspacePath(artifactPath(artifact), task)))" class="loading-text">Loading diff...</div>
                    <div v-else-if="normalizeWorkspacePath(artifactPath(artifact), task) && diffErrors.has(diffKey(task, normalizeWorkspacePath(artifactPath(artifact), task)))" class="detail-error">{{ diffErrors.get(diffKey(task, normalizeWorkspacePath(artifactPath(artifact), task))) }}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- Linked Sessions -->
      <section class="panel-section">
        <h4 class="section-title">Worker Sessions</h4>
        <div v-if="displaySessions.length === 0" class="empty-text">No linked sessions</div>
        <div v-else class="session-list">
          <div
            v-for="s in displaySessions"
            :key="s.session_id"
            class="session-item"
            :class="'session-' + s.display_status"
            @click="navigateToWorker(s)"
          >
            <span class="session-status-icon">{{ statusIcon(s.display_status) }}</span>
            <span class="session-role">{{ s.role }}</span>
            <span class="session-name">{{ s.name }}</span>
            <span class="session-state">{{ statusLabel(s.display_status) }}</span>
          </div>
        </div>
      </section>
    </div>

    <div class="panel-footer">
      <button class="refresh-btn" @click="refresh" :disabled="loading">
        {{ loading ? 'Refreshing...' : 'Refresh' }}
      </button>
    </div>
  </div>
</template>

<style scoped>
.team-panel {
  display: flex;
  flex-direction: column;
  width: 280px;
  height: 100%;
  border-left: 1px solid var(--border);
  background: var(--bg-secondary);
  flex-shrink: 0;
}

.panel-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px;
  border-bottom: 1px solid var(--border);
}

.panel-title {
  font-size: 13px;
  font-weight: 600;
  color: var(--text-primary);
  margin: 0;
}

.panel-close {
  background: none;
  border: none;
  color: var(--text-muted);
  font-size: 18px;
  cursor: pointer;
  padding: 2px 6px;
  border-radius: var(--radius-sm);
}

.panel-close:hover {
  color: var(--text-primary);
  background: var(--bg-hover);
}

.panel-body {
  flex: 1;
  overflow-y: auto;
  padding: 12px;
}

.panel-section {
  margin-bottom: 16px;
}

.section-title {
  font-size: 11px;
  font-weight: 600;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.5px;
  margin: 0 0 8px 0;
}

.loading-text,
.empty-text {
  font-size: 12px;
  color: var(--text-muted);
  padding: 8px 0;
}

.task-list {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.task-item {
  display: flex;
  align-items: flex-start;
  gap: 8px;
  padding: 8px;
  border-radius: var(--radius-sm);
  background: var(--bg-tertiary);
  border: 1px solid var(--border);
}

.task-item.task-running {
  border-color: color-mix(in srgb, var(--accent) 40%, var(--border));
  background: var(--accent-dim);
}

.task-item.task-completed {
  opacity: 0.8;
}

.task-item.task-failed {
  border-color: color-mix(in srgb, var(--red) 40%, var(--border));
}

.task-item.task-waiting_for_help {
  border-color: color-mix(in srgb, var(--yellow, #e5c07b) 40%, var(--border));
  background: color-mix(in srgb, var(--yellow, #e5c07b) 8%, var(--bg-tertiary));
}

.task-icon {
  font-size: 12px;
  flex-shrink: 0;
  margin-top: 1px;
}

.task-info {
  display: flex;
  flex-direction: column;
  gap: 2px;
  min-width: 0;
}

.task-role {
  font-size: 11px;
  font-weight: 600;
  color: var(--accent);
  text-transform: uppercase;
}

.task-prompt {
  font-size: 12px;
  color: var(--text-secondary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.task-duration {
  font-size: 10px;
  color: var(--text-muted);
}

.task-cost {
  font-size: 10px;
  color: var(--text-muted);
}

.task-action--danger {
  color: var(--red, #e06c75);
}

.task-action--danger:hover:not(:disabled) {
  background: color-mix(in srgb, var(--red, #e06c75) 15%, transparent);
}

.task-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  margin-top: 4px;
}

.task-action,
.inline-action {
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  background: transparent;
  color: var(--text-secondary);
  font-size: 10px;
  padding: 2px 5px;
  cursor: pointer;
}

.task-action:hover:not(:disabled),
.inline-action:hover:not(:disabled) {
  background: var(--bg-hover);
  color: var(--text-primary);
}

.task-action:disabled,
.inline-action:disabled {
  opacity: 0.45;
  cursor: not-allowed;
}

.task-detail {
  margin-top: 6px;
  padding-top: 6px;
  border-top: 1px solid var(--border);
}

.detail-section {
  margin-bottom: 8px;
}

.detail-label {
  font-size: 10px;
  font-weight: 600;
  color: var(--text-muted);
  text-transform: uppercase;
}

.detail-text,
.detail-error {
  margin: 2px 0 0;
  font-size: 11px;
  color: var(--text-secondary);
  white-space: pre-wrap;
  word-break: break-word;
}

.detail-error {
  color: var(--red);
}

.detail-pre,
.diff-pre {
  max-height: 160px;
  overflow: auto;
  margin: 4px 0 0;
  padding: 6px;
  border-radius: var(--radius-sm);
  background: var(--bg-primary);
  border: 1px solid var(--border);
  color: var(--text-secondary);
  font-size: 10px;
  white-space: pre-wrap;
  word-break: break-word;
}

.diff-pre {
  max-height: 220px;
}

.detail-list {
  list-style: none;
  padding: 0;
  margin: 2px 0 0 0;
}

.detail-list li {
  font-size: 11px;
  color: var(--text-secondary);
  padding: 1px 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.file-row {
  display: flex;
  align-items: center;
  gap: 4px;
}

.file-row span {
  min-width: 0;
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
}

.diff-block {
  margin-top: 6px;
}

.detail-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  font-size: 10px;
  color: var(--text-muted);
}

.detail-list--warn li {
  color: var(--yellow, #e5c07b);
}

.session-list {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.session-item {
  display: grid;
  grid-template-columns: auto auto minmax(0, 1fr);
  grid-template-areas:
    "icon role name"
    "icon state state";
  align-items: center;
  gap: 2px 6px;
  padding: 6px 8px;
  border-radius: var(--radius-sm);
  cursor: pointer;
  border: 1px solid transparent;
  transition: background var(--transition-fast), border-color var(--transition-fast);
}

.session-item.session-running {
  border-color: color-mix(in srgb, var(--accent) 36%, transparent);
  background: color-mix(in srgb, var(--accent) 8%, transparent);
}

.session-item.session-waiting_input {
  border-color: color-mix(in srgb, var(--yellow, #e5c07b) 55%, transparent);
  background: color-mix(in srgb, var(--yellow, #e5c07b) 12%, transparent);
}

.session-item.session-completed {
  opacity: 0.82;
}

.session-item.session-failed {
  border-color: color-mix(in srgb, var(--red) 45%, transparent);
  background: var(--red-dim);
}

.session-item.session-cancelled {
  opacity: 0.66;
}

.session-item.session-waiting_input .session-state {
  color: var(--yellow, #e5c07b);
}

.session-item.session-running .session-state {
  color: var(--accent);
}

.session-item.session-completed .session-state {
  color: var(--green);
}

.session-item:hover {
  background: var(--bg-hover);
}

.session-status-icon {
  grid-area: icon;
  font-size: 11px;
  flex-shrink: 0;
}

.session-role {
  grid-area: role;
  font-size: 11px;
  font-weight: 600;
  color: var(--accent);
  flex-shrink: 0;
}

.session-name {
  grid-area: name;
  font-size: 12px;
  color: var(--text-secondary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.session-state {
  grid-area: state;
  font-size: 10px;
  color: var(--text-muted);
  font-weight: 600;
}

.panel-footer {
  padding: 8px 12px;
  border-top: 1px solid var(--border);
}

.refresh-btn {
  width: 100%;
  padding: 6px;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  background: transparent;
  color: var(--text-secondary);
  font-size: 12px;
  cursor: pointer;
  transition: background var(--transition-fast), color var(--transition-fast);
}

.refresh-btn:hover:not(:disabled) {
  background: var(--bg-hover);
  color: var(--text-primary);
}

.refresh-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
</style>
