// frontend-next/src/features/agent-teams/ui/WorkerSessionBreadcrumb.tsx
'use client'

import { useState, useEffect, useRef } from 'react'
import { getWorkerContext } from '../api/teamApi'

interface Props {
  sessionId: string
  teamTaskId?: string
  onNavigateBack?: (sessionId: string, projectId: string) => void
}

interface WorkerContext {
  coordinator_session_id: string
  team_project_id: string
  team_project_name: string
  role: string
}

export function WorkerSessionBreadcrumb({ sessionId, teamTaskId, onNavigateBack }: Props) {
  const [context, setContext] = useState<WorkerContext | null>(null)
  const loadSeqRef = useRef(0)

  useEffect(() => {
    async function loadContext() {
      if (!teamTaskId || !sessionId) {
        setContext(null)
        return
      }
      const seq = ++loadSeqRef.current
      try {
        const data = await getWorkerContext(sessionId)
        if (seq !== loadSeqRef.current) return
        setContext(data)
      } catch {
        if (seq !== loadSeqRef.current) return
        setContext(null)
      }
    }
    loadContext()
  }, [sessionId, teamTaskId])

  function navigateBack() {
    if (!context) return
    onNavigateBack?.(context.coordinator_session_id, context.team_project_id)
  }

  if (!context) return null

  return (
    <div className="worker-breadcrumb" onClick={navigateBack}>
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <polyline points="15 18 9 12 15 6" />
      </svg>
      <span className="breadcrumb-text">Teams: {context.team_project_name}</span>
      <span className="breadcrumb-role">{context.role}</span>
      <style>{`
        .worker-breadcrumb {
          display: flex;
          align-items: center;
          gap: 6px;
          padding: 4px 10px;
          margin: 4px 8px;
          border-radius: var(--radius-sm);
          background: var(--accent-dim);
          border: 1px solid color-mix(in srgb, var(--accent) 25%, var(--border));
          color: var(--accent);
          font-size: 12px;
          cursor: pointer;
          transition: background var(--transition-fast);
          flex-shrink: 0;
        }
        .worker-breadcrumb:hover {
          background: color-mix(in srgb, var(--accent) 15%, var(--bg-secondary));
        }
        .breadcrumb-text { font-weight: 500; }
        .breadcrumb-role { color: var(--text-muted); font-size: 11px; }
      `}</style>
    </div>
  )
}

// frontend/src/features/agent-teams/ui/WorkerSessionBreadcrumb.vue
<script setup>
import { ref, watch } from 'vue'
import { getWorkerContext } from '../api/teamApi'

const props = defineProps({
  sessionId: { type: String, required: true },
  teamTaskId: { type: String, default: '' },
})

const emit = defineEmits(['navigate-back'])

const context = ref(null)
let _loadSeq = 0

async function loadContext() {
  if (!props.teamTaskId || !props.sessionId) {
    context.value = null
    return
  }
  const seq = ++_loadSeq
  try {
    const data = await getWorkerContext(props.sessionId)
    if (seq !== _loadSeq) return
    context.value = data
  } catch {
    if (seq !== _loadSeq) return
    context.value = null
  }
}

watch(() => props.sessionId, loadContext, { immediate: true })

function navigateBack() {
  if (!context.value) return
  emit('navigate-back', {
    sessionId: context.value.coordinator_session_id,
    projectId: context.value.team_project_id,
  })
}
</script>

<template>
  <div v-if="context" class="worker-breadcrumb" @click="navigateBack">
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <polyline points="15 18 9 12 15 6"/>
    </svg>
    <span class="breadcrumb-text">
      Teams: {{ context.team_project_name }}
    </span>
    <span class="breadcrumb-role">{{ context.role }}</span>
  </div>
</template>

<style scoped>
.worker-breadcrumb {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 4px 10px;
  margin: 4px 8px;
  border-radius: var(--radius-sm);
  background: var(--accent-dim);
  border: 1px solid color-mix(in srgb, var(--accent) 25%, var(--border));
  color: var(--accent);
  font-size: 12px;
  cursor: pointer;
  transition: background var(--transition-fast);
  flex-shrink: 0;
}

.worker-breadcrumb:hover {
  background: color-mix(in srgb, var(--accent) 15%, var(--bg-secondary));
}

.breadcrumb-text {
  font-weight: 500;
}

.breadcrumb-role {
  color: var(--text-muted);
  font-size: 11px;
}
</style>
