// frontend-next/src/features/memory-manager/ui/MemoryDialog.tsx
'use client'

import { useState, useEffect, useCallback, useRef, useMemo } from 'react'
import { useMemoryManager } from '../model/useMemoryManager'
import { splitLines, buildSideBySideDiff } from '@/shared/lib/diff'
import { configuredMarked } from '@/features/message-display/lib/markdownConfig'

interface MemoryDialogProps {
  visible: boolean
  projectDir?: string
  projectId?: string
  onClose: () => void
  onEvolve?: () => void
}

export function MemoryDialog({ visible, projectDir = '', projectId = '', onClose, onEvolve }: MemoryDialogProps) {
  const {
    content, versions, selectedRevision, loading, editing, editContent,
    saving, applying, error, conflictMessage,
    rules, selectedRule, ruleEditing, ruleDraft,
    setEditing, setEditContent, setSelectedRevision,
    setSelectedRule, setRuleEditing, setRuleDraft,
    loadClaudeMd, loadRules,
    save, applySelected, deleteSelectedRevision,
    saveRule, removeRule,
  } = useMemoryManager()

  const [activeTab, setActiveTab] = useState<'claude' | 'rules'>('claude')
  const [compareRevisionId, setCompareRevisionId] = useState('')
  const [ruleHistory, setRuleHistory] = useState<Array<{ hash: string; short_hash?: string; message?: string }>>([])
  const [ruleHistoryRef, setRuleHistoryRef] = useState('')
  const [ruleHistoryContents, setRuleHistoryContents] = useState<Record<string, string>>({})
  const editorRef = useRef<HTMLTextAreaElement>(null)

  // Load data when dialog opens
  useEffect(() => {
    if (visible && projectDir) {
      loadClaudeMd(projectDir)
      loadRules(projectDir)
    } else if (!visible) {
      setCompareRevisionId('')
      setRuleHistory([])
      setRuleHistoryRef('')
      setRuleHistoryContents({})
    }
  }, [visible, projectDir, loadClaudeMd, loadRules])

  // Close on Escape
  useEffect(() => {
    if (!visible) return
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.stopPropagation()
        onClose()
      }
    }
    window.addEventListener('keydown', handler, true)
    return () => window.removeEventListener('keydown', handler, true)
  }, [visible, onClose])

  // Reset compare when selected revision changes
  useEffect(() => {
    setCompareRevisionId('')
  }, [selectedRevision])

  // Markdown render helpers
  const renderedContent = useMemo(() => {
    const src = selectedRevision?.content || versions[0]?.content || content
    if (!src) return ''
    return configuredMarked(src)
  }, [selectedRevision, content, versions])

  const renderedPreview = useMemo(() => {
    if (!editContent) return ''
    return configuredMarked(editContent)
  }, [editContent])

  // Diff computation
  const compareOptions = useMemo(() => {
    return versions.filter((v) => v.id !== selectedRevision?.id)
  }, [versions, selectedRevision])

  const compareRevision = useMemo(() => {
    if (!compareRevisionId) return null
    return compareOptions.find((v) => v.id === compareRevisionId) || null
  }, [compareOptions, compareRevisionId])

  const compareRows = useMemo(() => {
    if (!compareRevision || !selectedRevision) return []
    return buildSideBySideDiff(
      splitLines(compareRevision.content),
      splitLines(selectedRevision.content),
    )
  }, [compareRevision, selectedRevision])

  const selectedState = selectedRevision?.state || ''

  // ── Handlers ──

  const handleSave = useCallback(async () => {
    await save(projectDir)
  }, [save, projectDir])

  const handleDeleteRevision = useCallback(async () => {
    await deleteSelectedRevision()
  }, [deleteSelectedRevision])

  const handleApply = useCallback(async () => {
    await applySelected(projectDir)
  }, [applySelected, projectDir])

  const handleSelectRevision = useCallback((revision: typeof versions[0]) => {
    setSelectedRevision(revision)
  }, [setSelectedRevision])

  const handleStartEdit = useCallback(() => {
    const src = selectedRevision?.content || content
    setEditContent(src)
    setEditing(true)
    setTimeout(() => editorRef.current?.focus(), 0)
  }, [selectedRevision, content, setEditContent, setEditing])

  const handleCancelEdit = useCallback(() => {
    setEditing(false)
    setEditContent('')
  }, [setEditing, setEditContent])

  const handleRuleSave = useCallback(async () => {
    await saveRule(projectDir)
    setRuleHistory([])
    setRuleHistoryRef('')
  }, [saveRule, projectDir])

  const handleRemoveRule = useCallback(async (rulePath: string) => {
    await removeRule(projectDir, rulePath)
    setRuleHistory([])
    setRuleHistoryRef('')
  }, [removeRule, projectDir])

  const handleNewRule = useCallback(() => {
    setRuleHistoryRef('')
    setSelectedRule(null)
    setRuleDraft({ path: '', content: '', pathsText: '' })
    setRuleEditing(true)
  }, [setSelectedRule, setRuleDraft, setRuleEditing])

  const handleStartRuleEdit = useCallback((rule: typeof rules[0]) => {
    setRuleDraft({ path: rule.path, content: rule.content, pathsText: (rule.paths || []).join('\n') })
    setRuleEditing(true)
  }, [setRuleDraft, setRuleEditing])

  if (!visible) return null

  return (
    <div className="memory-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose() }}>
      <div className={`memory-dialog${editing || ruleEditing ? ' memory-dialog--editing' : ''}`}>
        {/* Header */}
        <div className="memory-header">
          <div>
            <h3 className="memory-title">Project Rules</h3>
            <div className="memory-subtitle">CLAUDE.md and project rules</div>
          </div>
          <div className="header-actions">
            {!editing && !ruleEditing && (
              <button className="action-btn" disabled={!projectDir} title="Extract reusable lessons" onClick={onEvolve}>
                Evolve
              </button>
            )}
            {activeTab === 'claude' ? (
              !editing ? (
                <>
                  <button className="action-btn edit" onClick={handleStartEdit} disabled={loading}>
                    {selectedRevision ? 'Edit' : 'New Version'}
                  </button>
                  <button className="action-btn save" onClick={handleApply} disabled={!['draft', 'approved'].includes(selectedState) || applying}>
                    {applying ? 'Applying...' : 'Apply'}
                  </button>
                  <button className="action-btn danger" onClick={handleDeleteRevision} disabled={!selectedRevision || saving}>
                    Delete Version
                  </button>
                </>
              ) : (
                <>
                  <button className="action-btn save" onClick={handleSave} disabled={saving}>
                    {saving ? 'Saving...' : 'Save Version'}
                  </button>
                  <button className="action-btn cancel" onClick={handleCancelEdit}>Cancel</button>
                </>
              )
            ) : !ruleEditing ? (
              <>
                <button className="action-btn edit" onClick={handleNewRule}>New Rule</button>
                <button className="action-btn" onClick={() => handleStartRuleEdit(selectedRule!)} disabled={!selectedRule}>
                  Edit
                </button>
                <button className="action-btn danger" onClick={() => handleRemoveRule(selectedRule?.path || '')} disabled={!selectedRule || saving}>
                  Delete
                </button>
              </>
            ) : (
              <>
                <button className="action-btn save" onClick={handleRuleSave} disabled={saving || !ruleDraft.path}>
                  {saving ? 'Saving...' : 'Save Rule'}
                </button>
                <button className="action-btn cancel" onClick={() => { setRuleEditing(false); setRuleDraft({ path: '', content: '', pathsText: '' }) }}>
                  Cancel
                </button>
              </>
            )}
            <button className="close-btn" onClick={onClose}>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
              </svg>
            </button>
          </div>
        </div>

        {/* Tabs */}
        <div className="memory-tabs">
          <button className={activeTab === 'claude' ? 'active' : ''} onClick={() => setActiveTab('claude')}>CLAUDE.md</button>
          <button className={activeTab === 'rules' ? 'active' : ''} onClick={() => setActiveTab('rules')}>Rules</button>
        </div>

        {/* Notice */}
        {(error || conflictMessage) && (
          <div className={`notice${conflictMessage ? ' conflict' : ''}`}>{conflictMessage || error}</div>
        )}

        {/* Body */}
        <div className="memory-body">
          {loading && (
            <div className="loading-state">
              <div className="spinner" />
              <span>Loading...</span>
            </div>
          )}

          {!loading && activeTab === 'claude' && (
            <>
              {/* Version sidebar */}
              <aside className="version-sidebar">
                <div className="version-header">Versions</div>
                {versions.map((revision) => (
                  <button
                    key={revision.id}
                    className={`version-item${selectedRevision?.id === revision.id ? ' active' : ''}`}
                    onClick={() => handleSelectRevision(revision)}
                  >
                    <span className="version-main">v{revision.version_no}</span>
                    <span className={`state-badge ${revision.state}`}>{revision.state}</span>
                  </button>
                ))}
                {versions.length === 0 && <div className="empty-version">No versions</div>}
              </aside>

              {/* Content panel */}
              <section className="content-panel">
                {selectedRevision && (
                  <div className="revision-meta">
                    <span>v{selectedRevision.version_no}</span>
                    <span className={`state-badge ${selectedRevision.state}`}>{selectedRevision.state}</span>
                    <span className="hash">{selectedRevision.content_hash?.slice(0, 8)}</span>
                  </div>
                )}

                {/* Compare toolbar */}
                {selectedRevision && !editing && (
                  <div className="compare-toolbar">
                    <label className="compare-select-wrap">
                      <span>Compare</span>
                      <select
                        className="compare-select"
                        value={compareRevisionId}
                        onChange={(e) => setCompareRevisionId(e.target.value)}
                      >
                        <option value="">Current only</option>
                        {compareOptions.map((v) => (
                          <option key={v.id} value={v.id}>v{v.version_no} · {v.state}</option>
                        ))}
                      </select>
                    </label>
                    {compareRevision && (
                      <>
                        <span className="compare-summary">vs v{compareRevision.version_no}</span>
                      </>
                    )}
                  </div>
                )}

                {/* Editor split pane */}
                {editing ? (
                  <div className="split-pane">
                    <div className="split-editor">
                      <div className="split-label">Editor</div>
                      <textarea
                        ref={editorRef}
                        className="content-editor"
                        spellCheck={false}
                        value={editContent}
                        onChange={(e) => setEditContent(e.target.value)}
                      />
                    </div>
                    <div className="split-divider" />
                    <div className="split-preview">
                      <div className="split-label">Preview</div>
                      <div className="content-rendered markdown-body" dangerouslySetInnerHTML={{ __html: renderedPreview }} />
                    </div>
                  </div>
                ) : compareRevision ? (
                  /* Diff view */
                  <div className="diff-view">
                    {compareRows.map((row, index) => (
                      <div
                        key={row.id}
                        className={`diff-row diff-row--${row.type}`}
                        data-diff-row={`claude-${index}`}
                      >
                        <span className="diff-ln">{row.beforeLineNo ?? ''}</span>
                        <span className="diff-content">{row.beforeLine}</span>
                        <span className="diff-ln">{row.afterLineNo ?? ''}</span>
                        <span className="diff-content">{row.afterLine}</span>
                      </div>
                    ))}
                  </div>
                ) : (
                  /* Rendered content */
                  <div
                    className="content-rendered markdown-body"
                    dangerouslySetInnerHTML={{ __html: renderedContent }}
                  />
                )}
              </section>
            </>
          )}

          {!loading && activeTab === 'rules' && (
            <>
              {/* Rule sidebar */}
              <aside className="version-sidebar">
                <div className="version-header">Rules</div>
                {rules.map((rule) => (
                  <button
                    key={rule.path}
                    className={`version-item${selectedRule?.path === rule.path ? ' active' : ''}`}
                    onClick={() => { setSelectedRule(rule); setRuleEditing(false) }}
                  >
                    <span className="version-main">{rule.path}</span>
                  </button>
                ))}
                {rules.length === 0 && <div className="empty-version">No rules</div>}
              </aside>

              {/* Rule content panel */}
              <section className="content-panel">
                {ruleEditing ? (
                  <div className="rule-edit-form">
                    <label>
                      <span className="rule-form-label">Path</span>
                      <input
                        className="rule-form-input"
                        value={ruleDraft.path}
                        onChange={(e) => setRuleDraft({ ...ruleDraft, path: e.target.value })}
                        placeholder="e.g. frontend.md"
                      />
                    </label>
                    <label>
                      <span className="rule-form-label">Paths glob (one per line)</span>
                      <textarea
                        className="rule-form-textarea"
                        value={ruleDraft.pathsText}
                        onChange={(e) => setRuleDraft({ ...ruleDraft, pathsText: e.target.value })}
                        placeholder="paths globs, one per line. Empty means global."
                      />
                    </label>
                    <label>
                      <span className="rule-form-label">Content</span>
                      <textarea
                        className="rule-form-textarea rule-form-content"
                        value={ruleDraft.content}
                        onChange={(e) => setRuleDraft({ ...ruleDraft, content: e.target.value })}
                        placeholder="Rule content (markdown)"
                      />
                    </label>
                  </div>
                ) : selectedRule ? (
                  <div
                    className="content-rendered markdown-body"
                    dangerouslySetInnerHTML={{
                      __html: configuredMarked(selectedRule.content || ''),
                    }}
                  />
                ) : (
                  <div className="empty-state">Select a rule to view</div>
                )}
              </section>
            </>
          )}
        </div>
      </div>
    </div>
  )
}

// frontend/src/features/memory-manager/ui/MemoryDialog.vue
<script setup>
import { watch, computed, ref, onMounted, onBeforeUnmount, nextTick } from 'vue'
import { configuredMarked } from '@features/message-display'
import { listWorkspaceFileHistory, readWorkspaceFileAtRef } from '@entities/project/api/projectApi'
import { useMemoryManager } from '../model/useMemoryManager'
import { useDialogManager, useVisibleProxy, useEscapeToClose } from '@shared/lib/useDialogManager'

const props = defineProps({
  visible: { type: Boolean, default: false },
  projectDir: { type: String, default: '' },
  projectId: { type: String, default: '' },
})
const emit = defineEmits(['close', 'evolve'])

const { useDialog } = useDialogManager()
useDialog('memory-manager', useVisibleProxy(props, emit))

useEscapeToClose(() => props.visible, () => emit('close'))

const activeTab = ref('claude')
const claudeCompareRevisionId = ref('')
const claudeDiffCursor = ref(-1)
const ruleHistory = ref([])
const ruleHistoryLoading = ref(false)
const ruleHistoryRef = ref('')
const ruleHistoryContents = ref({})
const ruleDiffCursor = ref(-1)

const {
  content, versions, selectedRevision, selectedContent, canEditSelected,
  rules, selectedRule, ruleEditing, ruleDraft,
  loading, editing, editContent, saving, applying, error, conflictMessage,
  loadClaudeMd, loadRules, selectRevision, selectRule,
  startEdit, cancelEdit, save, startRuleEdit, startRuleDraft, cancelRuleEdit,
  saveRule, removeRule, deleteSelectedRevision, applySelected, reset,
} = useMemoryManager()

const renderedContent = computed(() => {
  if (!selectedContent.value) return ''
  return configuredMarked(selectedContent.value)
})

const renderedPreview = computed(() => {
  if (!editContent.value) return ''
  return configuredMarked(editContent.value)
})

const renderedRuleContent = computed(() => {
  if (!selectedRule.value?.content) return ''
  return configuredMarked(selectedRule.value.content)
})

const renderedRulePreview = computed(() => {
  if (!ruleDraft.value.content) return ''
  return configuredMarked(ruleDraft.value.content)
})

const selectedState = computed(() => selectedRevision.value?.state || '')
const canApply = computed(() => ['draft', 'approved'].includes(selectedState.value))
const canDeleteRevision = computed(() => Boolean(selectedRevision.value))
const rulePathLocked = computed(() => Boolean(ruleEditing.value && selectedRule.value))
const claudeCompareOptions = computed(() => versions.value.filter(revision => revision.id !== selectedRevision.value?.id))
const selectedClaudeCompareRevision = computed(() => claudeCompareOptions.value.find(revision => revision.id === claudeCompareRevisionId.value) || null)
const claudeCompareRows = computed(() => {
  if (!selectedRevision.value || !selectedClaudeCompareRevision.value) return []
  return buildSideBySideDiff(
    splitLines(selectedClaudeCompareRevision.value.content),
    splitLines(selectedRevision.value.content),
  )
})
const claudeDiffIndexes = computed(() => claudeCompareRows.value
  .map((row, index) => (row.type === 'same' ? -1 : index))
  .filter(index => index >= 0))
const claudeDiffSummary = computed(() => `${claudeDiffIndexes.value.length} diffs`)
const selectedRuleWorkspacePath = computed(() => selectedRule.value?.path ? `.claude/rules/${selectedRule.value.path}` : '')
const selectedRuleHistoryNode = computed(() => ruleHistory.value.find(item => item.hash === ruleHistoryRef.value) || null)
const selectedRuleHistoryContent = computed(() => {
  if (!selectedRuleWorkspacePath.value || !ruleHistoryRef.value) return ''
  return ruleHistoryContents.value[`${selectedRuleWorkspacePath.value}@${ruleHistoryRef.value}`] || ''
})
const ruleCompareRows = computed(() => {
  if (!selectedRule.value || !ruleHistoryRef.value) return []
  return buildSideBySideDiff(
    splitLines(selectedRuleHistoryContent.value),
    splitLines(selectedRule.value.content || ''),
  )
})
const ruleDiffIndexes = computed(() => ruleCompareRows.value
  .map((row, index) => (row.type === 'same' ? -1 : index))
  .filter(index => index >= 0))
const ruleDiffSummary = computed(() => `${ruleDiffIndexes.value.length} diffs`)

watch(() => props.visible, async (visible) => {
  if (visible && props.projectDir) {
    await Promise.all([
      loadClaudeMd(props.projectDir),
      loadRules(props.projectDir),
    ])
  } else if (!visible) {
    resetCompareState()
    reset()
  }
})

watch(() => props.projectDir, async (dir) => {
  if (props.visible && dir) {
    await Promise.all([
      loadClaudeMd(dir),
      loadRules(dir),
    ])
  }
})

watch(() => props.projectId, async (projectId) => {
  if (props.visible && projectId && selectedRule.value) {
    await loadRuleHistory()
  }
})

watch(selectedRevision, () => {
  claudeCompareRevisionId.value = ''
  claudeDiffCursor.value = -1
})

watch(selectedRule, async (rule) => {
  ruleHistoryRef.value = ''
  ruleDiffCursor.value = -1
  ruleHistory.value = []
  if (!rule || !props.projectId) return
  await loadRuleHistory()
})

function handleRefresh() {
  if (props.visible && props.projectDir) {
    loadClaudeMd(props.projectDir)
    loadRules(props.projectDir)
  }
}

async function handleOpenRuleDraft(event) {
  if (props.projectDir) {
    await loadRules(props.projectDir)
  }
  activeTab.value = 'rules'
  startRuleDraft(event.detail || {})
  ruleHistoryRef.value = ''
  ruleDiffCursor.value = -1
}

function handleOpenTab(event) {
  activeTab.value = event.detail?.tab === 'rules' ? 'rules' : 'claude'
}

onMounted(() => {
  window.addEventListener('vp-memory-refresh', handleRefresh)
  window.addEventListener('vp-memory-open-rule-draft', handleOpenRuleDraft)
  window.addEventListener('vp-memory-open-tab', handleOpenTab)
})

onBeforeUnmount(() => {
  window.removeEventListener('vp-memory-refresh', handleRefresh)
  window.removeEventListener('vp-memory-open-rule-draft', handleOpenRuleDraft)
  window.removeEventListener('vp-memory-open-tab', handleOpenTab)
})

async function handleSave() {
  await save(props.projectDir)
}

async function handleDeleteRevision() {
  await deleteSelectedRevision(props.projectDir)
}

async function handleApply() {
  await applySelected(props.projectDir)
}

async function handleRuleSave() {
  await saveRule(props.projectDir)
  if (props.projectId && selectedRule.value) {
    await loadRuleHistory()
  }
}

async function handleRemoveRule() {
  await removeRule(props.projectDir, selectedRule.value?.path)
  ruleHistory.value = []
  ruleHistoryRef.value = ''
  ruleDiffCursor.value = -1
}

function handleNewRule() {
  ruleHistoryRef.value = ''
  ruleDiffCursor.value = -1
  selectRule(null)
  startRuleEdit()
}

function handleSelectRule(rule) {
  selectRule(rule)
}

async function loadRuleHistory() {
  if (!props.projectId || !selectedRuleWorkspacePath.value) {
    ruleHistory.value = []
    ruleHistoryRef.value = ''
    return
  }
  ruleHistoryLoading.value = true
  error.value = ''
  try {
    const data = await listWorkspaceFileHistory(props.projectId, selectedRuleWorkspacePath.value, 20)
    ruleHistory.value = data.commits || []
    if (ruleHistoryRef.value && !ruleHistory.value.some(item => item.hash === ruleHistoryRef.value)) {
      ruleHistoryRef.value = ''
    }
  } catch (e) {
    ruleHistory.value = []
    ruleHistoryRef.value = ''
    error.value = e.message || 'Failed to load rule history'
  } finally {
    ruleHistoryLoading.value = false
  }
}

async function handleRuleCompareChange() {
  ruleDiffCursor.value = -1
  if (!ruleHistoryRef.value || !props.projectId || !selectedRuleWorkspacePath.value) return
  const cacheKey = `${selectedRuleWorkspacePath.value}@${ruleHistoryRef.value}`
  if (ruleHistoryContents.value[cacheKey] !== undefined) return
  try {
    const data = await readWorkspaceFileAtRef(props.projectId, selectedRuleWorkspacePath.value, ruleHistoryRef.value)
    ruleHistoryContents.value = {
      ...ruleHistoryContents.value,
      [cacheKey]: data.content || '',
    }
  } catch (e) {
    error.value = e.message || 'Failed to load rule version'
    ruleHistoryRef.value = ''
  }
}

function resetCompareState() {
  claudeCompareRevisionId.value = ''
  claudeDiffCursor.value = -1
  ruleHistory.value = []
  ruleHistoryLoading.value = false
  ruleHistoryRef.value = ''
  ruleHistoryContents.value = {}
  ruleDiffCursor.value = -1
}

import { splitLines, buildSideBySideDiff } from '@shared/lib/diff'

function formatRuleHistoryLabel(commit) {
  const shortHash = commit.short_hash || String(commit.hash || '').slice(0, 7)
  const message = String(commit.message || '').trim().split('\n')[0]
  return message ? `${shortHash} · ${message}` : shortHash
}

function nextDiff(prefix, indexes, cursorRef) {
  if (!indexes.length) return
  const next = indexes.find(index => index > cursorRef.value) ?? indexes[0]
  cursorRef.value = next
  nextTick(() => {
    document.querySelector(`[data-diff-row="${prefix}-${next}"]`)?.scrollIntoView({ block: 'center' })
  })
}

function nextClaudeDiff() {
  nextDiff('claude', claudeDiffIndexes.value, claudeDiffCursor)
}

function nextRuleDiff() {
  nextDiff('rule', ruleDiffIndexes.value, ruleDiffCursor)
}
</script>

<template>
  <Teleport to="body">
    <Transition name="dialog-fade">
      <div v-if="visible" class="memory-overlay" @click.self="emit('close')">
        <div class="memory-dialog" :class="{ 'memory-dialog--editing': editing || ruleEditing }">
          <div class="memory-header">
            <div>
              <h3 class="memory-title">Project Rules</h3>
              <div class="memory-subtitle">CLAUDE.md and project rules</div>
            </div>
            <div class="header-actions">
              <button
                v-if="!editing && !ruleEditing"
                class="action-btn"
                :disabled="!props.projectDir"
                title="Extract reusable lessons from the current session"
                @click="emit('evolve')"
              >
                Evolve
              </button>
              <template v-if="activeTab === 'claude'">
                <template v-if="!editing">
                  <button class="action-btn edit" @click="startEdit" :disabled="!canEditSelected || loading">
                    {{ selectedRevision ? 'Edit' : 'New Version' }}
                  </button>
                  <button class="action-btn save" @click="handleApply" :disabled="!canApply || applying">
                    {{ applying ? 'Applying...' : 'Apply' }}
                  </button>
                  <button class="action-btn danger" @click="handleDeleteRevision" :disabled="!canDeleteRevision || saving">Delete Version</button>
                </template>
                <template v-else>
                  <button class="action-btn save" @click="handleSave" :disabled="saving">
                    {{ saving ? 'Saving...' : 'Save Version' }}
                  </button>
                  <button class="action-btn cancel" @click="cancelEdit">Cancel</button>
                </template>
              </template>
              <template v-else>
                <template v-if="!ruleEditing">
                  <button class="action-btn edit" @click="handleNewRule">New Rule</button>
                  <button class="action-btn" @click="startRuleEdit(selectedRule)" :disabled="!selectedRule">Edit</button>
                  <button class="action-btn danger" @click="handleRemoveRule" :disabled="!selectedRule || saving">Delete</button>
                </template>
                <template v-else>
                  <button class="action-btn save" @click="handleRuleSave" :disabled="saving || !ruleDraft.path">
                    {{ saving ? 'Saving...' : 'Save Rule' }}
                  </button>
                  <button class="action-btn cancel" @click="cancelRuleEdit">Cancel</button>
                </template>
              </template>
              <button class="close-btn" @click="emit('close')">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                </svg>
              </button>
            </div>
          </div>

          <div class="memory-tabs">
            <button :class="{ active: activeTab === 'claude' }" @click="activeTab = 'claude'">CLAUDE.md</button>
            <button :class="{ active: activeTab === 'rules' }" @click="activeTab = 'rules'">Rules</button>
          </div>

          <div v-if="error || conflictMessage" class="notice" :class="{ conflict: conflictMessage }">
            {{ conflictMessage || error }}
          </div>

          <div class="memory-body">
            <div v-if="loading" class="loading-state">
              <div class="spinner"></div>
              <span>Loading...</span>
            </div>

            <template v-else-if="activeTab === 'claude'">
              <aside class="version-sidebar">
                <div class="version-header">Versions</div>
                <button
                  v-for="revision in versions"
                  :key="revision.id"
                  class="version-item"
                  :class="{ active: selectedRevision?.id === revision.id }"
                  @click="selectRevision(revision)"
                >
                  <span class="version-main">v{{ revision.version_no }}</span>
                  <span class="state-badge" :class="revision.state">{{ revision.state }}</span>
                </button>
                <div v-if="versions.length === 0" class="empty-version">No versions</div>
              </aside>

              <section class="content-panel">
                <div v-if="selectedRevision" class="revision-meta">
                  <span>v{{ selectedRevision.version_no }}</span>
                  <span class="state-badge" :class="selectedRevision.state">{{ selectedRevision.state }}</span>
                  <span class="hash">{{ selectedRevision.content_hash?.slice(0, 8) }}</span>
                </div>

                <div v-if="selectedRevision && !editing" class="compare-toolbar">
                  <label class="compare-select-wrap">
                    <span>Compare</span>
                    <select v-model="claudeCompareRevisionId" class="compare-select">
                      <option value="">Current only</option>
                      <option v-for="revision in claudeCompareOptions" :key="revision.id" :value="revision.id">
                        v{{ revision.version_no }} · {{ revision.state }}
                      </option>
                    </select>
                  </label>
                  <template v-if="selectedClaudeCompareRevision">
                    <span class="compare-summary">vs v{{ selectedClaudeCompareRevision.version_no }} · {{ claudeDiffSummary }}</span>
                    <button class="action-btn" @click="nextClaudeDiff" :disabled="claudeDiffIndexes.length === 0">Next diff</button>
                  </template>
                </div>

                <template v-if="editing">
                  <div class="split-pane">
                    <div class="split-editor">
                      <div class="split-label">Editor</div>
                      <textarea v-model="editContent" class="content-editor" spellcheck="false"></textarea>
                    </div>
                    <div class="split-divider"></div>
                    <div class="split-preview">
                      <div class="split-label">Preview</div>
                      <div class="content-rendered markdown-body" v-html="renderedPreview"></div>
                    </div>
                  </div>
                </template>

                <div v-else-if="selectedClaudeCompareRevision" class="diff-view">
                  <div
                    v-for="(row, index) in claudeCompareRows"
                    :key="row.id"
                    class="diff-row"
                    :class="[row.type, { current: claudeDiffCursor === index }]"
                    :data-diff-row="`claude-${index}`"
                  >
                    <span class="diff-kind">{{ row.type === 'added' ? '+' : row.type === 'removed' ? '-' : '·' }}</span>
                    <span class="diff-line-no">{{ row.displayLineNo || '' }}</span>
                    <pre class="diff-line">{{ row.displayLine || ' ' }}</pre>
                  </div>
                </div>
                <div v-else-if="selectedContent || content" class="content-rendered markdown-body" v-html="renderedContent"></div>
                <div v-else class="empty-state">(empty)</div>
              </section>
            </template>

            <template v-else>
              <aside class="version-sidebar">
                <div class="version-header">Rules</div>
                <button
                  v-for="rule in rules"
                  :key="rule.path"
                  class="version-item"
                  :class="{ active: selectedRule?.path === rule.path }"
                  @click="handleSelectRule(rule)"
                >
                  <span class="version-main">{{ rule.path }}</span>
                </button>
                <div v-if="rules.length === 0" class="empty-version">No rules</div>
              </aside>

              <section class="content-panel">
                <div v-if="selectedRule" class="revision-meta">
                  <span>{{ selectedRule.path }}</span>
                  <span class="state-badge applied">rule</span>
                  <span class="hash">{{ selectedRule.paths?.length ? selectedRule.paths.join(', ') : 'global' }}</span>
                </div>

                <div v-if="selectedRule && !ruleEditing" class="compare-toolbar">
                  <label class="compare-select-wrap">
                    <span>Compare</span>
                    <select v-model="ruleHistoryRef" class="compare-select" @change="handleRuleCompareChange">
                      <option value="">Current only</option>
                      <option v-for="commit in ruleHistory" :key="commit.hash" :value="commit.hash">
                        {{ formatRuleHistoryLabel(commit) }}
                      </option>
                    </select>
                  </label>
                  <span v-if="ruleHistoryLoading" class="compare-summary">Loading history...</span>
                  <span v-else-if="!ruleHistory.length" class="compare-summary">No git history yet</span>
                  <template v-else-if="selectedRuleHistoryNode">
                    <span class="compare-summary">vs {{ formatRuleHistoryLabel(selectedRuleHistoryNode) }} · {{ ruleDiffSummary }}</span>
                    <button class="action-btn" @click="nextRuleDiff" :disabled="ruleDiffIndexes.length === 0">Next diff</button>
                  </template>
                </div>

                <template v-if="ruleEditing">
                  <div class="split-pane">
                    <div class="split-editor">
                      <div class="split-label">Editor</div>
                      <input
                        v-model="ruleDraft.path"
                        class="memory-title-input"
                        :disabled="rulePathLocked"
                        placeholder="Rule path, e.g. frontend.md or vue/components.md"
                      />
                      <textarea v-model="ruleDraft.pathsText" class="memory-paths-input" placeholder="paths globs, one per line. Empty means global." spellcheck="false"></textarea>
                      <textarea v-model="ruleDraft.content" class="content-editor memory-editor" spellcheck="false"></textarea>
                    </div>
                    <div class="split-divider"></div>
                    <div class="split-preview">
                      <div class="split-label">Preview</div>
                      <div class="content-rendered markdown-body" v-html="renderedRulePreview"></div>
                    </div>
                  </div>
                </template>

                <div v-else-if="selectedRuleHistoryNode" class="diff-view">
                  <div
                    v-for="(row, index) in ruleCompareRows"
                    :key="row.id"
                    class="diff-row"
                    :class="[row.type, { current: ruleDiffCursor === index }]"
                    :data-diff-row="`rule-${index}`"
                  >
                    <span class="diff-kind">{{ row.type === 'added' ? '+' : row.type === 'removed' ? '-' : '·' }}</span>
                    <span class="diff-line-no">{{ row.displayLineNo || '' }}</span>
                    <pre class="diff-line">{{ row.displayLine || ' ' }}</pre>
                  </div>
                </div>
                <div v-else-if="selectedRule" class="content-rendered markdown-body" v-html="renderedRuleContent"></div>
                <div v-else class="empty-state">Select or create a rule</div>
              </section>
            </template>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
.memory-overlay {
  position: fixed; inset: 0; z-index: 100;
  background: var(--bg-overlay);
  display: flex; align-items: center; justify-content: center;
}
.memory-dialog {
  width: 1040px; max-width: 94vw; max-height: 84vh;
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-xl);
  display: flex; flex-direction: column;
  overflow: hidden;
  transition: width 0.2s ease;
}
.memory-dialog--editing { width: 1200px; }
.memory-header {
  display: flex; align-items: center; justify-content: space-between;
  padding: 12px 18px;
  border-bottom: 1px solid var(--border);
  flex-shrink: 0;
}
.memory-title {
  font-size: 14px; font-weight: 600;
  color: var(--text-primary);
  font-family: var(--font-mono);
  margin: 0;
}
.memory-subtitle { margin-top: 2px; color: var(--text-muted); font-size: 11px; }
.header-actions { display: flex; align-items: center; gap: 6px; flex-wrap: wrap; justify-content: flex-end; }
.memory-tabs {
  display: flex;
  gap: 6px;
  padding: 8px 18px;
  border-bottom: 1px solid var(--border);
  background: var(--bg-primary);
}
.memory-tabs button {
  padding: 5px 10px;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  background: transparent;
  color: var(--text-secondary);
  cursor: pointer;
  font-size: 12px;
}
.memory-tabs button.active {
  color: var(--accent);
  border-color: var(--accent);
  background: var(--accent-dim);
}
.close-btn {
  background: transparent; border: none;
  color: var(--text-muted); cursor: pointer;
  padding: 4px; border-radius: var(--radius-sm);
  transition: color var(--transition-fast), background var(--transition-fast);
  display: flex; align-items: center;
}
.close-btn:hover { color: var(--text-primary); background: var(--bg-hover); }
.action-btn {
  padding: 5px 12px; border-radius: var(--radius-sm);
  font-size: 12px; font-weight: 500; cursor: pointer;
  border: 1px solid var(--border); transition: all var(--transition-fast);
  font-family: var(--font-sans); background: transparent; color: var(--text-secondary);
}
.action-btn:hover:not(:disabled) { background: var(--bg-hover); }
.action-btn:disabled { opacity: 0.4; cursor: not-allowed; }
.action-btn.edit { color: var(--accent); border-color: var(--accent); }
.action-btn.edit:hover:not(:disabled) { background: var(--accent-dim); }
.action-btn.save { background: var(--accent); color: var(--text-on-accent); border-color: var(--accent); }
.action-btn.save:hover:not(:disabled) { filter: brightness(1.1); }
.action-btn.cancel { color: var(--text-secondary); }
.action-btn.danger { color: var(--danger, #ef4444); }
.notice {
  padding: 8px 18px;
  border-bottom: 1px solid var(--border);
  color: var(--text-secondary);
  background: var(--bg-tertiary);
  font-size: 12px;
}
.notice.conflict { color: var(--danger, #ef4444); }
.memory-body {
  flex: 1; overflow: hidden; display: flex;
  min-height: 460px;
}
.loading-state, .empty-state {
  flex: 1; display: flex; align-items: center; justify-content: center;
  gap: 8px; color: var(--text-muted); font-size: 13px;
}
.spinner {
  animation: spin 0.6s linear infinite;
}
.version-sidebar {
  width: 220px;
  border-right: 1px solid var(--border);
  background: var(--bg-primary);
  padding: 10px;
  overflow-y: auto;
}
.version-header { color: var(--text-muted); font-size: 11px; text-transform: uppercase; margin: 4px 6px 8px; }
.version-item {
  width: 100%; display: flex; align-items: center; justify-content: space-between;
  gap: 8px; padding: 8px; margin-bottom: 4px;
  border: 1px solid transparent; border-radius: var(--radius-sm);
  background: transparent; color: var(--text-secondary); cursor: pointer;
  text-align: left;
}
.version-item:hover { background: var(--bg-hover); }
.version-item.active { border-color: var(--accent); background: var(--accent-dim); color: var(--text-primary); }
.version-main { font-family: var(--font-mono); font-size: 12px; }
.empty-version { color: var(--text-muted); font-size: 12px; padding: 8px; }
.content-panel { flex: 1; min-width: 0; display: flex; flex-direction: column; }
.revision-meta {
  display: flex; align-items: center; gap: 8px;
  padding: 8px 14px;
  border-bottom: 1px solid var(--border);
  color: var(--text-muted); font-size: 12px;
}
.compare-toolbar {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 8px 14px;
  border-bottom: 1px solid var(--border);
  background: var(--bg-primary);
  flex-wrap: wrap;
}
.compare-select-wrap {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  color: var(--text-muted);
  font-size: 12px;
}
.compare-select {
  min-width: 220px;
  padding: 6px 10px;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  background: var(--bg-secondary);
  color: var(--text-primary);
}
.compare-summary { color: var(--text-muted); font-size: 12px; }
.state-badge {
  padding: 1px 6px; border-radius: 999px;
  background: var(--bg-tertiary); color: var(--text-muted);
  font-size: 10px; text-transform: uppercase;
}
.state-badge.applied { color: #16a34a; }
.state-badge.approved { color: var(--accent); }
.state-badge.proposed { color: #d97706; }
.state-badge.rejected, .state-badge.conflicted { color: var(--danger, #ef4444); }
.hash { font-family: var(--font-mono); }
.content-rendered {
  flex: 1; padding: 20px 24px;
  overflow-y: auto; font-size: 14px; line-height: 1.7;
}
.diff-view {
  flex: 1;
  overflow: auto;
  background: var(--bg-primary);
}
.diff-row {
  display: grid;
  grid-template-columns: 24px 56px 1fr;
  gap: 8px;
  padding: 0 14px;
  border-bottom: 1px solid color-mix(in srgb, var(--border) 65%, transparent);
  align-items: start;
}
.diff-row.current {
  background: color-mix(in srgb, var(--accent) 16%, transparent);
}
.diff-row.added {
  background: color-mix(in srgb, #22c55e 10%, transparent);
}
.diff-row.removed {
  background: color-mix(in srgb, #ef4444 10%, transparent);
}
.diff-kind,
.diff-line-no {
  padding: 8px 0;
  color: var(--text-muted);
  font-family: var(--font-mono);
  font-size: 12px;
}
.diff-line {
  margin: 0;
  padding: 8px 0;
  white-space: pre-wrap;
  word-break: break-word;
  color: var(--text-primary);
  font-family: var(--font-mono);
  font-size: 12px;
  line-height: 1.6;
}
.split-pane { flex: 1; display: flex; min-height: 0; }
.split-editor, .split-preview { flex: 1; display: flex; flex-direction: column; min-width: 0; }
.split-divider { width: 1px; background: var(--border); }
.split-label {
  padding: 8px 12px; font-size: 11px; font-weight: 600;
  color: var(--text-muted); text-transform: uppercase;
  border-bottom: 1px solid var(--border);
  background: var(--bg-primary);
}
.content-editor {
  flex: 1; padding: 16px; border: none; outline: none; resize: none;
  background: var(--bg-primary); color: var(--text-primary);
  font-family: var(--font-mono); font-size: 13px; line-height: 1.6;
}
.memory-title-input,
.memory-paths-input {
  margin: 10px 12px 0;
  padding: 8px 10px;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  background: var(--bg-primary);
  color: var(--text-primary);
  font-family: var(--font-sans);
}
.memory-title-input:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}
.memory-paths-input {
  min-height: 70px;
  resize: vertical;
}
.memory-editor { margin-top: 10px; }
.dialog-fade-enter-active, .dialog-fade-leave-active { transition: opacity 0.15s ease; }
.dialog-fade-enter-from, .dialog-fade-leave-to { opacity: 0; }
</style>
