// frontend-next/src/features/scheduler/ui/SchedulerDialog.tsx
'use client'

import { useState, useEffect, useCallback, useMemo } from 'react'
import { useScheduler } from '../model/useScheduler'

interface Props {
  visible: boolean
  projectId: string
  onClose: () => void
}

type ScheduleType = 'minutes' | 'hourly' | 'daily' | 'weekly'

interface FormState {
  name: string
  prompt: string
  schedule_type: ScheduleType
  interval_minutes: number
  interval_hours: number
  time: string
  weekday: number
  auto_unbind_after_run: boolean
  delete_session_on_success: boolean
}

const weekdays = [
  { value: 0, label: 'Monday' },
  { value: 1, label: 'Tuesday' },
  { value: 2, label: 'Wednesday' },
  { value: 3, label: 'Thursday' },
  { value: 4, label: 'Friday' },
  { value: 5, label: 'Saturday' },
  { value: 6, label: 'Sunday' },
]

const initialForm: FormState = {
  name: '',
  prompt: '',
  schedule_type: 'hourly',
  interval_minutes: 30,
  interval_hours: 1,
  time: '09:00',
  weekday: 0,
  auto_unbind_after_run: true,
  delete_session_on_success: false,
}

function parseTime(value: string) {
  const [hour, minute] = (value || '09:00').split(':').map(n => Number.parseInt(n, 10))
  return { hour: Number.isInteger(hour) ? hour : 9, minute: Number.isInteger(minute) ? minute : 0 }
}

function toCronExpr(value: FormState) {
  const time = parseTime(value.time)
  if (value.schedule_type === 'minutes') return `*/${Math.max(Number(value.interval_minutes) || 30, 1)} * * * *`
  if (value.schedule_type === 'hourly') return `${time.minute} */${Math.max(Number(value.interval_hours) || 1, 1)} * * *`
  if (value.schedule_type === 'daily') return `${time.minute} ${time.hour} * * *`
  return `${time.minute} ${time.hour} * * ${Number(value.weekday) || 0}`
}

function describeCron(expr: string) {
  const [minute, hour, , , weekday] = expr.split(' ')
  if (minute?.startsWith('*/')) return `Every ${minute.slice(2)} minutes`
  if (hour?.startsWith('*/')) return `Every ${hour.slice(2)} hours at minute ${minute}`
  const timeStr = `${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}`
  if (weekday !== '*') return `Every ${weekdays.find(day => day.value === Number(weekday))?.label || 'week'} at ${timeStr}`
  return `Every day at ${timeStr}`
}

function formatTime(value: string | null | undefined) {
  if (!value) return '-'
  return new Date(value).toLocaleString()
}

export function SchedulerDialog({ visible, projectId, onClose }: Props) {
  const { tasks, loading, saving, error, loadSchedules, saveNewSchedule, toggleSchedule, removeSchedule, runNow } = useScheduler()
  const [form, setForm] = useState<FormState>(initialForm)

  useEffect(() => {
    if (visible && projectId) {
      loadSchedules(projectId)
    }
  }, [visible, projectId, loadSchedules])

  const cronExpr = useMemo(() => toCronExpr(form), [form])

  const updateForm = useCallback(<K extends keyof FormState>(key: K, value: FormState[K]) => {
    setForm(prev => ({ ...prev, [key]: value }))
  }, [])

  const submit = useCallback(async () => {
    await saveNewSchedule({
      project_id: projectId,
      name: form.name || 'Scheduled task',
      prompt: form.prompt,
      cron_expression: cronExpr,
      auto_unbind: form.auto_unbind_after_run,
      delete_on_success: form.delete_session_on_success,
    })
    if (!error) setForm(initialForm)
  }, [projectId, form, cronExpr, saveNewSchedule, error])

  if (!visible) return null

  return (
    <div className="scheduler-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose() }}>
      <div className="scheduler-dialog" role="dialog" aria-modal="true">
        <div className="scheduler-header">
          <div>
            <span className="scheduler-eyebrow">Automation timeline</span>
            <h3>Project Clock</h3>
            <p>Create sessions in this project and run scheduled work automatically.</p>
          </div>
          <button className="close-btn" onClick={onClose} aria-label="Close scheduler">×</button>
        </div>

        {error && <div className="notice">{error}</div>}

        <div className="scheduler-body">
          <section className="schedule-form">
            <input value={form.name} onChange={e => updateForm('name', e.target.value)} placeholder="Name" aria-label="Schedule name" />

            <div className="schedule-type-grid">
              {(['minutes', 'hourly', 'daily', 'weekly'] as ScheduleType[]).map(type => (
                <button key={type} type="button" className={form.schedule_type === type ? 'active' : ''} onClick={() => updateForm('schedule_type', type)}>
                  {type === 'minutes' ? 'Every N minutes' : type === 'hourly' ? 'Every N hours' : type === 'daily' ? 'Daily' : 'Weekly'}
                </button>
              ))}
            </div>

            {form.schedule_type === 'minutes' && (
              <input type="number" min={1} max={59} value={form.interval_minutes} onChange={e => updateForm('interval_minutes', Number(e.target.value))} placeholder="Minutes" />
            )}
            {form.schedule_type === 'hourly' && (
              <input type="number" min={1} max={23} value={form.interval_hours} onChange={e => updateForm('interval_hours', Number(e.target.value))} placeholder="Hours" />
            )}
            {form.schedule_type === 'weekly' && (
              <select value={form.weekday} onChange={e => updateForm('weekday', Number(e.target.value))}>
                {weekdays.map(day => (
                  <option key={day.value} value={day.value}>{day.label}</option>
                ))}
              </select>
            )}
            {form.schedule_type !== 'minutes' && (
              <input type="time" value={form.time} onChange={e => updateForm('time', e.target.value)} />
            )}

            <div className="schedule-summary">{describeCron(cronExpr)}</div>

            <textarea
              value={form.prompt}
              onChange={e => updateForm('prompt', e.target.value)}
              placeholder="Describe the work this project session should run"
            />

            <label className="checkbox-field schedule-option">
              <input type="checkbox" checked={form.auto_unbind_after_run} onChange={e => updateForm('auto_unbind_after_run', e.target.checked)} />
              <span>Disconnect IM after each run</span>
            </label>
            <label className="checkbox-field schedule-option">
              <input type="checkbox" checked={form.delete_session_on_success} onChange={e => updateForm('delete_session_on_success', e.target.checked)} />
              <span>Delete successful execution session</span>
            </label>

            <button className="primary-btn" type="button" disabled={saving || !form.prompt || !projectId} onClick={submit}>
              {saving ? 'Saving...' : 'Create Project Clock'}
            </button>
          </section>

          <section className="schedule-list">
            <div className="schedule-list-header">
              <div>
                <span className="scheduler-eyebrow">Scheduled runs</span>
                <strong>{tasks.length} timeline{tasks.length !== 1 ? 's' : ''}</strong>
              </div>
            </div>

            {loading ? (
              <div className="empty">Loading...</div>
            ) : tasks.length === 0 ? (
              <div className="empty">No schedules</div>
            ) : (
              tasks.map(task => (
                <div key={task.id} className={`schedule-item${!task.enabled ? ' schedule-item--disabled' : ''}`}>
                  <div className="schedule-main">
                    <div className="schedule-title-row">
                      <div className="schedule-title">{task.name}</div>
                    </div>
                    <div className="schedule-meta">
                      {describeCron(task.cron_expression)} · next {formatTime(task.next_run_at)}
                      {task.auto_unbind && <span> · auto-disconnect</span>}
                      {task.delete_on_success && <span> · delete on success</span>}
                    </div>
                    <div className="schedule-prompt">{task.prompt}</div>
                    {task.runs?.length ? (
                      <div className="schedule-meta">
                        last run: {task.runs[0].status}{task.runs[0].result_session_id ? ` → ${task.runs[0].result_session_id}` : ''}
                      </div>
                    ) : null}
                  </div>
                  <div className="schedule-actions">
                    <button onClick={() => runNow(task.id)} disabled={saving}>Run now</button>
                    <button onClick={() => toggleSchedule(task)} disabled={saving}>{task.enabled ? 'Disable' : 'Enable'}</button>
                    <button className="danger" onClick={() => removeSchedule(task.id)} disabled={saving}>Delete</button>
                  </div>
                </div>
              ))
            )}
          </section>
        </div>
      </div>
    </div>
  )
}

// frontend/src/features/scheduler/ui/SchedulerDialog.vue
<script setup>
import { ref, watch, computed } from 'vue'
import { useSession } from '@entities/session'
import { useImBinding } from '@features/im-binding'
import { useScheduler } from '../model/useScheduler'
import { useDialogManager, useVisibleProxy, useEscapeToClose } from '@shared/lib/useDialogManager'

const props = defineProps({
  visible: { type: Boolean, default: false },
  projectId: { type: String, default: '' },
  sessionId: { type: String, default: '' },
})
const emit = defineEmits(['close'])

useDialogManager().useDialog('scheduler', useVisibleProxy(props, emit))

useEscapeToClose(() => props.visible, () => emit('close'))

const { sessions } = useSession()
const { availableChannels, fetchChannels } = useImBinding()
const { tasks, loading, saving, error, loadSchedules, saveNewSchedule, toggleSchedule, removeSchedule, runNow } = useScheduler()
const form = ref({
  name: '',
  prompt: '',
  schedule_type: 'hourly',
  interval_minutes: 30,
  interval_hours: 1,
  time: '09:00',
  weekday: 0,
  session_id: '',
  channel_id: '',
  auto_unbind_after_run: true,
  delete_session_on_success: false,
})

const weekdays = [
  { value: 0, label: 'Monday' },
  { value: 1, label: 'Tuesday' },
  { value: 2, label: 'Wednesday' },
  { value: 3, label: 'Thursday' },
  { value: 4, label: 'Friday' },
  { value: 5, label: 'Saturday' },
  { value: 6, label: 'Sunday' },
]

const projectSessions = computed(() => {
  return [...sessions.value]
    .filter(item => item.project_id === props.projectId)
    .sort((a, b) => new Date(b.updated_time || 0).getTime() - new Date(a.updated_time || 0).getTime())
})

const channelInstances = computed(() => {
  return availableChannels.value.flatMap(channel => (channel.instances || []).map(instance => ({
    ...instance,
    channel_type: channel.channel_type,
    display_name: channel.display_name,
  })))
})

const selectedChannel = computed(() => {
  return channelInstances.value.find(item => item.id === form.value.channel_id) || null
})

const scheduleDescription = computed(() => describeCron(toCronExpr(form.value)))
const channelHint = computed(() => {
  if (!form.value.channel_id) return 'No IM channel selected. The schedule only creates and runs a local session.'
  if (selectedChannel.value?.bound_session_id) {
    return `This channel is currently bound to session ${selectedChannel.value.bound_session_id}. The run will fail until it is released.`
  }
  if (selectedChannel.value?.init_status !== 'ready') {
    return 'This channel is not ready yet. Initialize it before the schedule runs.'
  }
  return 'Each run will bind the new execution session to this IM channel and disconnect it after completion.'
})

watch(() => props.visible, (v) => {
  if (v) {
    loadSchedules(props.projectId)
    fetchChannels()
  }
})

function parseTime(value) {
  const [hour, minute] = (value || '09:00').split(':').map(n => Number.parseInt(n, 10))
  return {
    hour: Number.isInteger(hour) ? hour : 9,
    minute: Number.isInteger(minute) ? minute : 0,
  }
}

function toCronExpr(value) {
  const time = parseTime(value.time)
  if (value.schedule_type === 'minutes') return `*/${Math.max(Number(value.interval_minutes) || 30, 1)} * * * *`
  if (value.schedule_type === 'hourly') return `${time.minute} */${Math.max(Number(value.interval_hours) || 1, 1)} * * *`
  if (value.schedule_type === 'daily') return `${time.minute} ${time.hour} * * *`
  return `${time.minute} ${time.hour} * * ${Number(value.weekday) || 0}`
}

function describeCron(expr) {
  const [minute, hour, , , weekday] = expr.split(' ')
  if (minute?.startsWith('*/')) return `Every ${minute.slice(2)} minutes`
  if (hour?.startsWith('*/')) return `Every ${hour.slice(2)} hours at minute ${minute}`
  const time = `${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}`
  if (weekday !== '*') return `Every ${weekdays.find(day => day.value === Number(weekday))?.label || 'week'} at ${time}`
  return `Every day at ${time}`
}

async function submit() {
  await saveNewSchedule({
    project_id: props.projectId,
    session_id: form.value.session_id || '',
    channel_id: form.value.channel_id || '',
    auto_unbind_after_run: form.value.auto_unbind_after_run,
    delete_session_on_success: form.value.delete_session_on_success,
    name: form.value.name || 'Scheduled task',
    prompt: form.value.prompt,
    cron_expr: toCronExpr(form.value),
    enabled: true,
  })
  if (!error.value) {
    form.value = {
      name: '',
      prompt: '',
      schedule_type: 'hourly',
      interval_minutes: 30,
      interval_hours: 1,
      time: '09:00',
      weekday: 0,
      session_id: '',
      channel_id: '',
      auto_unbind_after_run: true,
      delete_session_on_success: false,
    }
  }
}

function formatTime(value) {
  if (!value) return '-'
  return new Date(value).toLocaleString()
}

function channelOptionLabel(item) {
  const name = item?.name || item?.id || 'Channel'
  const appId = item?.app_id ? ` · ${item.app_id}` : ''
  const bound = item?.bound_session_id ? ` · bound ${item.bound_session_id}` : ''
  return `${item.display_name || item.channel_type} · ${name}${appId}${bound}`
}

function taskAnchorLabel(task) {
  if (task?.channel_id) {
    const channel = channelInstances.value.find(item => item.id === task.channel_id)
    return channel ? `IM · ${channelOptionLabel(channel)}` : `IM · ${task.channel_id}`
  }
  if (!task?.session_id) return 'Local only'
  const session = projectSessions.value.find(item => item.session_id === task.session_id)
  if (!session) return `Legacy IM notify · ${task.session_id}`
  return `Legacy IM notify · ${session.name || session.session_id}`
}
</script>

<template>
  <teleport to="body">
    <Transition name="dialog-fade">
      <div v-if="visible" class="scheduler-overlay" @click.self="emit('close')">
        <div class="scheduler-dialog" role="dialog" aria-modal="true" aria-labelledby="scheduler-title">
          <div class="scheduler-header">
            <div>
              <span class="scheduler-eyebrow">Automation timeline</span>
              <h3 id="scheduler-title">Project Clock</h3>
              <p>Create sessions in this project and run scheduled work automatically.</p>
            </div>
            <button class="close-btn" type="button" aria-label="Close scheduler" @click="emit('close')">×</button>
          </div>

          <div v-if="error" class="notice">{{ error }}</div>

          <div class="scheduler-body">
            <section class="schedule-form" aria-label="Create schedule">
              <input v-model="form.name" placeholder="Name" aria-label="Schedule name" />
              <div class="schedule-type-grid">
                <button type="button" :class="{ active: form.schedule_type === 'minutes' }" @click="form.schedule_type = 'minutes'">Every N minutes</button>
                <button type="button" :class="{ active: form.schedule_type === 'hourly' }" @click="form.schedule_type = 'hourly'">Every N hours</button>
                <button type="button" :class="{ active: form.schedule_type === 'daily' }" @click="form.schedule_type = 'daily'">Daily</button>
                <button type="button" :class="{ active: form.schedule_type === 'weekly' }" @click="form.schedule_type = 'weekly'">Weekly</button>
              </div>
              <input
                v-if="form.schedule_type === 'minutes'"
                v-model.number="form.interval_minutes"
                type="number"
                min="1"
                max="59"
                placeholder="Minutes"
              />
              <input
                v-if="form.schedule_type === 'hourly'"
                v-model.number="form.interval_hours"
                type="number"
                min="1"
                max="23"
                placeholder="Hours"
              />
              <select v-if="form.schedule_type === 'weekly'" v-model.number="form.weekday">
                <option v-for="day in weekdays" :key="day.value" :value="day.value">{{ day.label }}</option>
              </select>
              <input
                v-if="form.schedule_type !== 'minutes'"
                v-model="form.time"
                type="time"
              />
              <div class="schedule-summary">{{ scheduleDescription }}</div>
              <textarea v-model="form.prompt" placeholder="Describe the work this project session should run"></textarea>
              <div class="anchor-field">
                <label class="anchor-label">IM channel for each run</label>
                <select v-model="form.channel_id">
                  <option value="">No IM channel</option>
                  <option v-for="item in channelInstances" :key="item.id" :value="item.id">
                    {{ channelOptionLabel(item) }}
                  </option>
                </select>
                <div class="anchor-hint">{{ channelHint }}</div>
              </div>
              <label class="checkbox-field schedule-option">
                <input v-model="form.auto_unbind_after_run" type="checkbox" />
                <span>Disconnect IM after each run</span>
              </label>
              <label class="checkbox-field schedule-option">
                <input v-model="form.delete_session_on_success" type="checkbox" />
                <span>Delete successful execution session</span>
              </label>
              <button class="primary-btn" type="button" :disabled="saving || !form.prompt || !props.projectId" @click="submit">
                {{ saving ? 'Saving...' : 'Create Project Clock' }}
              </button>
            </section>

            <section class="schedule-list">
              <div class="schedule-list-header">
                <div>
                  <span class="scheduler-eyebrow">Scheduled runs</span>
                  <strong>{{ tasks.length }} timeline{{ tasks.length === 1 ? '' : 's' }}</strong>
                </div>
              </div>
              <div v-if="loading" class="empty">Loading...</div>
              <div v-else-if="tasks.length === 0" class="empty">No schedules</div>
              <div v-for="task in tasks" :key="task.id" class="schedule-item" :class="{ 'schedule-item--disabled': !task.enabled }">
                <div class="schedule-main">
                  <div class="schedule-title-row">
                    <div class="schedule-title">{{ task.name }}</div>
                    <span class="schedule-anchor" :class="{ 'schedule-anchor--active': !!task.session_id }">{{ taskAnchorLabel(task) }}</span>
                  </div>
                  <div class="schedule-meta">
                    {{ describeCron(task.cron_expr) }} · next {{ formatTime(task.next_run_time) }}
                    <span v-if="task.auto_unbind_after_run"> · auto-disconnect</span>
                    <span v-if="task.delete_session_on_success"> · delete on success</span>
                  </div>
                  <div class="schedule-prompt">{{ task.prompt }}</div>
                  <div v-if="task.runs?.length" class="schedule-meta">
                    last run: {{ task.runs[0].status }} {{ task.runs[0].result_session_id ? `→ ${task.runs[0].result_session_id}` : '' }}
                  </div>
                </div>
                <div class="schedule-actions">
                  <button type="button" @click="runNow(task.id)" :disabled="saving">Run now</button>
                  <button type="button" @click="toggleSchedule(task)" :disabled="saving">{{ task.enabled ? 'Disable' : 'Enable' }}</button>
                  <button type="button" class="danger" @click="removeSchedule(task.id)" :disabled="saving">Delete</button>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </Transition>
  </teleport>
</template>

<style scoped>
.scheduler-overlay { position: fixed; inset: 0; z-index: 100; background: color-mix(in srgb, var(--bg-overlay) 88%, transparent); backdrop-filter: blur(14px); display: flex; align-items: center; justify-content: center; padding: 24px; }
.scheduler-dialog { width: min(1060px, 96vw); max-height: min(860px, 88vh); background: radial-gradient(circle at 12% 0%, color-mix(in srgb, var(--accent) 16%, transparent), transparent 30%), var(--bg-secondary); border: 1px solid color-mix(in srgb, var(--accent) 24%, var(--border)); border-radius: calc(var(--radius-lg) + 6px); box-shadow: var(--shadow-xl), 0 24px 80px color-mix(in srgb, var(--accent) 12%, transparent); overflow: hidden; display: flex; flex-direction: column; }
.scheduler-header { display: flex; justify-content: space-between; align-items: flex-start; gap: 24px; padding: 20px 22px 18px; border-bottom: 1px solid color-mix(in srgb, var(--border) 76%, transparent); }
.scheduler-eyebrow { display: inline-flex; margin-bottom: 6px; color: var(--accent); font-size: 10px; font-weight: 800; letter-spacing: 0.12em; text-transform: uppercase; }
.scheduler-header h3 { margin: 0; font-size: 20px; color: var(--text-primary); letter-spacing: -0.02em; }
.scheduler-header p { margin: 6px 0 0; font-size: 13px; color: var(--text-muted); }
.close-btn { width: 34px; height: 34px; border: 1px solid var(--border); border-radius: 999px; background: color-mix(in srgb, var(--bg-primary) 80%, transparent); color: var(--text-muted); font-size: 22px; line-height: 1; cursor: pointer; transition: transform 180ms ease, color 180ms ease, border-color 180ms ease, background 180ms ease; }
.close-btn:hover { color: var(--text-primary); border-color: var(--accent); background: var(--bg-hover); transform: rotate(90deg); }
.notice { padding: 10px 22px; color: var(--danger, #ef4444); background: color-mix(in srgb, var(--danger, #ef4444) 10%, var(--bg-tertiary)); border-bottom: 1px solid var(--border); font-size: 12px; }
.scheduler-body { display: grid; grid-template-columns: minmax(320px, 360px) 1fr; min-height: 520px; overflow: hidden; }
.schedule-form { display: flex; flex-direction: column; gap: 12px; padding: 16px; border-right: 1px solid var(--border); background: color-mix(in srgb, var(--bg-primary) 86%, transparent); overflow-y: auto; }
.schedule-form input, .schedule-form textarea, .schedule-form select { border: 1px solid var(--border); border-radius: 12px; background: var(--bg-secondary); color: var(--text-primary); padding: 9px 10px; font-family: var(--font-sans); transition: border-color 180ms ease, box-shadow 180ms ease, background 180ms ease; }
.schedule-form input:focus, .schedule-form textarea:focus, .schedule-form select:focus { outline: none; border-color: var(--accent); box-shadow: 0 0 0 3px color-mix(in srgb, var(--accent) 16%, transparent); }
.schedule-type-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
.schedule-type-grid button { border: 1px solid var(--border); border-radius: 12px; background: var(--bg-secondary); color: var(--text-secondary); padding: 9px 10px; cursor: pointer; font-size: 11px; font-weight: 700; transition: transform 180ms ease, color 180ms ease, background 180ms ease, border-color 180ms ease; }
.schedule-type-grid button:hover:not(.active) { color: var(--text-primary); border-color: color-mix(in srgb, var(--accent) 42%, var(--border)); transform: translateY(-1px); }
.schedule-type-grid button.active { border-color: var(--accent); background: linear-gradient(135deg, var(--accent-dim), color-mix(in srgb, var(--accent) 14%, transparent)); color: var(--accent); }
.schedule-summary { color: var(--accent); font-size: 12px; padding: 8px 10px; border: 1px dashed color-mix(in srgb, var(--accent) 45%, var(--border)); border-radius: 12px; background: color-mix(in srgb, var(--accent) 8%, transparent); }
.schedule-form textarea { min-height: 140px; resize: vertical; line-height: 1.5; }
.anchor-field { display: flex; flex-direction: column; gap: 6px; }
.anchor-label { font-size: 12px; color: var(--text-secondary); font-weight: 700; }
.anchor-hint { font-size: 11px; line-height: 1.5; color: var(--text-muted); }
.schedule-option { display: flex; align-items: center; gap: 8px; color: var(--text-secondary); font-size: 12px; }
.schedule-option input { width: auto; }
.primary-btn { min-height: 38px; background: linear-gradient(135deg, var(--accent), color-mix(in srgb, var(--accent) 78%, #ffffff)); border: 1px solid var(--accent); color: var(--text-on-accent); border-radius: 12px; padding: 9px 12px; cursor: pointer; font-weight: 800; transition: transform 180ms ease, box-shadow 180ms ease, opacity 180ms ease; }
.primary-btn:hover:not(:disabled) { transform: translateY(-1px); box-shadow: 0 10px 26px color-mix(in srgb, var(--accent) 28%, transparent); }
.primary-btn:disabled { opacity: 0.5; cursor: not-allowed; }
.schedule-list { overflow-y: auto; padding: 16px; }
.schedule-list-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 12px; }
.schedule-list-header strong { display: block; color: var(--text-primary); font-size: 15px; }
.empty { color: var(--text-muted); text-align: center; padding: 48px 20px; font-size: 13px; border: 1px dashed var(--border); border-radius: var(--radius-md); background: color-mix(in srgb, var(--bg-primary) 72%, transparent); }
.schedule-item { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 14px; padding: 14px; border: 1px solid color-mix(in srgb, var(--border) 84%, transparent); border-radius: var(--radius-md); margin-bottom: 10px; background: linear-gradient(135deg, color-mix(in srgb, var(--bg-primary) 92%, transparent), color-mix(in srgb, var(--bg-tertiary) 42%, transparent)); transition: transform 200ms ease, border-color 200ms ease, box-shadow 200ms ease; }
.schedule-item:hover { transform: translateY(-2px); border-color: color-mix(in srgb, var(--accent) 38%, var(--border)); box-shadow: 0 14px 36px color-mix(in srgb, #000 16%, transparent); }
.schedule-item--disabled { opacity: 0.72; }
.schedule-main { min-width: 0; }
.schedule-title-row { display: flex; align-items: flex-start; justify-content: space-between; gap: 10px; }
.schedule-title { font-weight: 800; color: var(--text-primary); font-size: 14px; }
.schedule-anchor { display: inline-flex; align-items: center; border-radius: 999px; font-family: var(--font-mono); }
.schedule-anchor { max-width: 100%; margin-top: 9px; font-size: 10px; color: var(--text-muted); border: 1px solid var(--border); padding: 3px 8px; }
.schedule-anchor--active { color: var(--green); border-color: color-mix(in srgb, var(--green) 45%, var(--border)); background: var(--green-dim); }
.schedule-meta { color: var(--text-muted); font-size: 11px; margin-top: 4px; }
.schedule-prompt { color: var(--text-secondary); font-size: 12px; line-height: 1.5; margin-top: 9px; white-space: pre-wrap; max-height: 92px; overflow: hidden; }
.schedule-actions { display: flex; flex-direction: column; gap: 7px; flex-shrink: 0; }
.schedule-actions button { border: 1px solid var(--border); border-radius: 10px; background: var(--bg-secondary); color: var(--text-secondary); padding: 7px 10px; cursor: pointer; transition: transform 180ms ease, color 180ms ease, background 180ms ease, border-color 180ms ease; }
.schedule-actions button:hover:not(:disabled) { color: var(--text-primary); background: var(--bg-hover); border-color: var(--accent); transform: translateY(-1px); }
.schedule-actions .danger { color: var(--danger, #ef4444); }
.dialog-fade-enter-active, .dialog-fade-leave-active { transition: opacity 180ms ease; }
.dialog-fade-enter-active .scheduler-dialog, .dialog-fade-leave-active .scheduler-dialog { transition: transform 220ms ease, opacity 220ms ease; }
.dialog-fade-enter-from, .dialog-fade-leave-to { opacity: 0; }
.dialog-fade-enter-from .scheduler-dialog, .dialog-fade-leave-to .scheduler-dialog { opacity: 0; transform: translateY(16px) scale(0.98); }
@media (max-width: 860px) { .scheduler-overlay { align-items: stretch; padding: 12px; } .scheduler-body { grid-template-columns: 1fr; overflow-y: auto; } .schedule-form { border-right: none; border-bottom: 1px solid var(--border); } .schedule-list { overflow: visible; } }
@media (prefers-reduced-motion: reduce) { .scheduler-dialog, .schedule-item, .schedule-type-grid button, .primary-btn, .schedule-actions button, .close-btn { transition: none; } .schedule-item:hover, .primary-btn:hover:not(:disabled), .schedule-actions button:hover:not(:disabled), .schedule-type-grid button:hover:not(.active), .close-btn:hover { transform: none; } }
</style>
