// frontend/src/features/send-message/ui/MessageInput.vue
<script setup>
import { ref, nextTick, watch, computed } from 'vue'
import { useUserPreferences } from '@shared/lib/useUserPreferences'
import { formatFileSize } from '@shared/lib/textParsers'
import {
  buildSlashCommandInput,
  filterSlashCommandSuggestions,
  getSlashCommandContext,
} from '@features/command-palette/lib/slashCommandSuggest'

const props = defineProps({
  disabled: {
    type: Boolean,
    default: false,
  },
  running: {
    type: Boolean,
    default: false,
  },
  slashCommands: {
    type: Array,
    default: () => [],
  },
  placeholderOverride: {
    type: String,
    default: '',
  },
})

const emit = defineEmits(['send', 'slash-select'])

const { shouldEnterSend, shouldCtrlEnterSend } = useUserPreferences()

const input = ref('')
const isComposing = ref(false)
const compositionEndedRecently = ref(false)
const caretIndex = ref(0)
const slashActiveIndex = ref(0)
const slashContext = ref(null)

const slashSuggestions = computed(() => {
  if (!slashContext.value) return []
  return filterSlashCommandSuggestions(props.slashCommands, slashContext.value.query)
})

const slashSuggestVisible = computed(() => (
  !props.disabled
  && !isComposing.value
  && slashContext.value !== null
  && slashSuggestions.value.length > 0
))

// 动态生成placeholder文本
const placeholderText = computed(() => {
  if (props.placeholderOverride) return props.placeholderOverride
  if (props.disabled) return 'Waiting for Claude to finish...'
  if (props.running) return 'Send follow-up (queued until Claude finishes)...'

  const sendShortcut = shouldEnterSend() ? 'Enter' : 'Ctrl+Enter'
  const newLineShortcut = shouldEnterSend() ? 'Ctrl+Enter' : 'Enter'

  return `Send a message... (${sendShortcut} to send, ${newLineShortcut} for new line, type / for skills)`
})

// 动态生成发送按钮的提示文本
const sendButtonTitle = computed(() => {
  const sendShortcut = shouldEnterSend() ? 'Enter' : 'Ctrl+Enter'
  return `Send message (${sendShortcut})`
})
const inputEl = ref(null)
const slashListEl = ref(null)
const fileInputEl = ref(null)
const pendingAttachments = ref([])

function autoResize() {
  const el = inputEl.value
  if (!el) return
  el.style.height = 'auto'
  el.style.height = el.scrollHeight + 'px'
}

watch(input, () => {
  nextTick(() => {
    autoResize()
    syncSlashContext()
  })
})

function syncCaret() {
  caretIndex.value = inputEl.value?.selectionStart ?? input.value.length
  syncSlashContext()
}

function syncSlashContext() {
  slashContext.value = getSlashCommandContext(input.value, caretIndex.value)
  slashActiveIndex.value = 0
}

function applySlashSelection(command) {
  if (!command || !slashContext.value) return
  input.value = buildSlashCommandInput(input.value, slashContext.value, command.name)
  slashContext.value = null
  slashActiveIndex.value = 0
  emit('slash-select', command)
  nextTick(() => {
    const pos = input.value.length
    inputEl.value?.setSelectionRange(pos, pos)
    autoResize()
    inputEl.value?.focus()
  })
}

function scrollSlashActiveIntoView() {
  const container = slashListEl.value
  if (!container) return
  const items = container.querySelectorAll('.slash-item')
  const el = items[slashActiveIndex.value]
  if (el) el.scrollIntoView({ block: 'nearest' })
}

function handleSend() {
  const text = input.value.trim()
  if ((!text && pendingAttachments.value.length === 0) || props.disabled) return

  slashContext.value = null

  if (pendingAttachments.value.length > 0) {
    emit('send', {
      text: text || 'Please review the attached files.',
      attachments: pendingAttachments.value.map(item => ({
        name: item.name,
        mime_type: item.mime_type,
        size: item.size,
        data: item.data,
      })),
    })
  } else {
    emit('send', text)
  }

  input.value = ''
  pendingAttachments.value = []
  nextTick(() => {
    autoResize()
    inputEl.value?.focus()
  })
}

function handleCompositionStart() {
  isComposing.value = true
}

function handleCompositionEnd() {
  isComposing.value = false
  // 标记最近刚结束输入法，避免keydown事件立即触发
  compositionEndedRecently.value = true
  // 50ms后清除标记，给keydown事件足够的时间窗口
  setTimeout(() => {
    compositionEndedRecently.value = false
  }, 50)
}

function handleKeydown(e) {
  if (slashSuggestVisible.value) {
    const len = slashSuggestions.value.length
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      slashActiveIndex.value = (slashActiveIndex.value + 1) % len
      nextTick(scrollSlashActiveIntoView)
      return
    }
    if (e.key === 'ArrowUp') {
      e.preventDefault()
      slashActiveIndex.value = (slashActiveIndex.value - 1 + len) % len
      nextTick(scrollSlashActiveIntoView)
      return
    }
    if (e.key === 'Enter' || e.key === 'Tab') {
      e.preventDefault()
      applySlashSelection(slashSuggestions.value[slashActiveIndex.value])
      return
    }
    if (e.key === 'Escape') {
      e.preventDefault()
      slashContext.value = null
      return
    }
  }

  if (e.key === 'Enter') {
    // During IME composition or just after composition, defer all Enter handling to browser default
    if (isComposing.value || compositionEndedRecently.value) {
      return
    }

    const hasCtrl = e.ctrlKey
    const hasCmd = e.metaKey
    const hasModifier = hasCtrl || hasCmd

    // 根据用户偏好决定行为
    if (shouldEnterSend() && !hasModifier) {
      // 模式1：Enter发送，Ctrl/Cmd+Enter换行
      // 只有单独按Enter时才发送
      e.preventDefault()
      handleSend()
    } else if (shouldCtrlEnterSend() && hasModifier) {
      // 模式2：Ctrl/Cmd+Enter发送，Enter换行
      // 只有按Ctrl/Cmd+Enter时才发送
      e.preventDefault()
      handleSend()
    } else if (hasModifier) {
      // Ctrl/Cmd+Enter 但当前模式不要求发送 -> 手动插入换行
      e.preventDefault()
      const start = inputEl.value.selectionStart
      const end = inputEl.value.selectionEnd
      const value = input.value
      input.value = value.slice(0, start) + '\n' + value.slice(end)
      nextTick(() => {
        inputEl.value.selectionStart = inputEl.value.selectionEnd = start + 1
        autoResize()
      })
    }
    // 其他情况：让浏览器默认处理（单独Enter在非enter-send模式下）
  }
}

function handlePaste(e) {
  const items = e.clipboardData?.items
  if (!items) return

  for (const item of items) {
    if (item.kind === 'file') {
      const file = item.getAsFile()
      if (file) {
        e.preventDefault()
        addAttachmentFile(file)
        return
      }
    }
  }
}

function handleDrop(e) {
  e.preventDefault()
  const files = e.dataTransfer?.files
  if (!files) return
  for (const file of files) {
    addAttachmentFile(file)
  }
}

function handleDragover(e) {
  e.preventDefault()
}

function handleFileSelect(e) {
  const files = e.target.files
  if (!files) return
  for (const file of files) {
    addAttachmentFile(file)
  }
  e.target.value = ''
}

function addAttachmentFile(file) {
  const reader = new FileReader()
  reader.onload = () => {
    const dataUrl = reader.result
    const base64 = dataUrl.split(',')[1]
    pendingAttachments.value.push({
      name: file.name || 'attachment',
      data: base64,
      mime_type: file.type || 'application/octet-stream',
      size: file.size || 0,
      preview: file.type?.startsWith('image/') ? dataUrl : '',
    })
  }
  reader.readAsDataURL(file)
}

function addImage(base64, mediaType) {
  const preview = `data:${mediaType};base64,${base64}`
  pendingAttachments.value.push({
    name: `image-${Date.now()}.png`,
    data: base64,
    mime_type: mediaType,
    size: 0,
    preview,
  })
}

function removeAttachment(index) {
  pendingAttachments.value.splice(index, 1)
}

function formatSize(size) {
  return formatFileSize(size)
}

function setInput(text) {
  input.value = text
  nextTick(() => {
    autoResize()
    inputEl.value?.focus()
  })
}

function appendText(text) {
  input.value += text
  nextTick(() => {
    autoResize()
    inputEl.value?.focus()
  })
}

function handleAreaClick(e) {
  // If clicking on the input area (but not on controls), focus the input
  const isControl = e.target.closest('.send-btn, .attach-btn, .attachment-remove, .attachment-thumb, .attachment-file, input[type="file"]')

  if (!isControl && !props.disabled) {
    inputEl.value?.focus()
  }
}

function openFilePicker() {
  fileInputEl.value?.click()
}

function clearAttachments() {
  pendingAttachments.value = []
}

defineExpose({ setInput, addImage, appendText, clearAttachments })
</script>

<template>
  <div class="input-area" @drop="handleDrop" @dragover="handleDragover" @click="handleAreaClick">
    <Transition name="slash-fade">
      <div v-if="slashSuggestVisible" ref="slashListEl" class="slash-suggest">
        <button
          v-for="(cmd, index) in slashSuggestions"
          :key="cmd.name + ':' + cmd.type"
          type="button"
          class="slash-item"
          :class="{ 'slash-item--active': index === slashActiveIndex }"
          @mousedown.prevent="applySlashSelection(cmd)"
          @mouseenter="slashActiveIndex = index"
        >
          <span class="slash-name">/{{ cmd.name }}</span>
          <span class="slash-tag" :class="cmd.type === 'skill' ? 'slash-tag--skill' : 'slash-tag--command'">
            {{ cmd.type === 'skill' ? 'skill' : 'command' }}
          </span>
          <span v-if="cmd.argumentHint" class="slash-hint">{{ cmd.argumentHint }}</span>
          <span class="slash-desc">{{ cmd.description }}</span>
        </button>
      </div>
    </Transition>
    <div v-if="pendingAttachments.length > 0" class="attachment-previews">
      <div
        v-for="(item, i) in pendingAttachments"
        :key="i"
        :class="item.preview ? 'attachment-thumb' : 'attachment-file'"
      >
        <img v-if="item.preview" :src="item.preview" :alt="item.name" />
        <div v-else class="attachment-file-main">
          <span class="attachment-icon">FILE</span>
          <span class="attachment-name">{{ item.name }}</span>
          <span class="attachment-size">{{ formatSize(item.size) }}</span>
        </div>
        <button class="attachment-remove" @click="removeAttachment(i)" title="Remove attachment" aria-label="Remove attachment">
          <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3">
            <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
          </svg>
        </button>
      </div>
    </div>
    <textarea
      ref="inputEl"
      v-model="input"
      @keydown="handleKeydown"
      @input="syncCaret"
      @click="syncCaret"
      @keyup="syncCaret"
      @compositionstart="handleCompositionStart"
      @compositionend="handleCompositionEnd"
      @paste="handlePaste"
      :placeholder="placeholderText"
      :disabled="disabled"
      rows="1"
      class="input-field"
      autocomplete="off"
      autocorrect="off"
      autocapitalize="off"
      spellcheck="false"
    ></textarea>
    <div class="input-actions">
      <input
        ref="fileInputEl"
        type="file"
        multiple
        class="file-input"
        @change="handleFileSelect"
      />
      <button
        class="attach-btn"
        :disabled="disabled"
        title="Attach files"
        aria-label="Attach files"
        @click.stop="openFilePicker"
      >
        +
      </button>
      <button
        class="send-btn"
        :disabled="(!input.trim() && pendingAttachments.length === 0) || disabled"
        :title="sendButtonTitle"
        aria-label="Send message"
        @click="handleSend"
      >
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <line x1="22" y1="2" x2="11" y2="13"/>
          <polygon points="22 2 15 22 11 13 2 9 22 2"/>
        </svg>
      </button>
    </div>
  </div>
</template>

<style scoped>
.input-area {
  position: relative;
  display: flex;
  flex-direction: column;
  gap: 0;
  background: color-mix(in srgb, var(--glass-bg) 46%, transparent);
  border: 1px solid color-mix(in srgb, var(--glass-border) 72%, transparent);
  border-radius: var(--radius-lg);
  padding: 9px 86px 9px 14px;
  margin: 0;
  min-height: 46px;
  box-shadow: 0 10px 28px rgba(0, 0, 0, 0.13), inset 0 1px 0 var(--glass-highlight);
  backdrop-filter: blur(calc(var(--glass-blur) * 1.05)) saturate(var(--glass-saturate));
  -webkit-backdrop-filter: blur(calc(var(--glass-blur) * 1.05)) saturate(var(--glass-saturate));
  transition:
    border-color var(--transition-fast),
    background var(--transition-base),
    box-shadow var(--transition-fast),
    transform var(--transition-fast);
  cursor: text;
}

.input-area:focus-within {
  background: color-mix(in srgb, var(--glass-bg) 64%, transparent);
  border-color: var(--accent);
  box-shadow: var(--shadow-active), 0 14px 34px rgba(0, 0, 0, 0.16), inset 0 1px 0 var(--glass-highlight);
}

.attachment-previews {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
  padding-bottom: 8px;
}

.attachment-thumb {
  position: relative;
  width: 64px;
  height: 64px;
  border-radius: var(--radius-md);
  overflow: hidden;
  border: 1px solid var(--glass-border);
  background: var(--layer-glass);
  box-shadow: var(--shadow-sm);
  cursor: default;
}

.attachment-thumb img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.attachment-file {
  position: relative;
  max-width: 240px;
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-md);
  background: var(--layer-glass);
  padding: 9px 30px 9px 10px;
  box-shadow: var(--shadow-xs);
  cursor: default;
}

.attachment-file-main {
  display: flex;
  align-items: center;
  gap: 6px;
  min-width: 0;
}

.attachment-icon {
  flex-shrink: 0;
  color: var(--accent);
  font-size: 10px;
  font-weight: 700;
}

.attachment-name {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  color: var(--text-primary);
  font-size: 12px;
}

.attachment-size {
  flex-shrink: 0;
  color: var(--text-muted);
  font-size: 11px;
}

.attachment-remove {
  position: absolute;
  top: 4px;
  right: 4px;
  width: 22px;
  height: 22px;
  border-radius: 50%;
  background: var(--glass-bg-strong);
  color: var(--text-primary);
  border: 1px solid var(--glass-border);
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  opacity: 0;
  box-shadow: var(--shadow-sm);
  transition: opacity var(--transition-fast), background var(--transition-fast), color var(--transition-fast);
}

.attachment-thumb:hover .attachment-remove,
.attachment-file:hover .attachment-remove,
.attachment-remove:focus-visible {
  opacity: 1;
}

.input-field {
  flex: none;
  width: 100%;
  background: none;
  border: none;
  outline: none;
  box-shadow: none;
  color: var(--text-primary);
  font-family: var(--font-sans);
  font-size: 14px;
  line-height: 1.45;
  resize: none;
  min-height: 24px;
  max-height: 38vh;
  overflow-y: auto;
  padding-right: 4px;
}

.input-field::placeholder {
  color: var(--text-muted);
  user-select: none;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
}

.input-field:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.input-actions {
  position: absolute;
  right: 8px;
  bottom: 7px;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: flex-end;
  gap: 5px;
}

.file-input {
  display: none;
}

.attach-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  min-width: 32px;
  height: 32px;
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-md);
  background: var(--layer-glass);
  color: var(--text-secondary);
  cursor: pointer;
  font-size: 16px;
  line-height: 1;
  transition: background var(--transition-fast), color var(--transition-fast), border-color var(--transition-fast), box-shadow var(--transition-fast);
}

.attach-btn:hover:not(:disabled) {
  background: var(--layer-active);
  border-color: var(--accent);
  color: var(--accent);
  box-shadow: var(--shadow-sm);
}

.attach-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.send-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  border: 1px solid rgba(255, 255, 255, 0.16);
  border-radius: var(--radius-md);
  background: linear-gradient(135deg, var(--accent), var(--purple));
  color: var(--text-on-accent);
  cursor: pointer;
  transition:
    filter var(--transition-fast),
    transform var(--transition-fast),
    box-shadow var(--transition-fast),
    opacity var(--transition-fast);
  flex-shrink: 0;
  box-shadow: var(--shadow-md), var(--shadow-glow);
  align-self: flex-end;
}

.send-btn:hover:not(:disabled) {
  filter: brightness(1.08);
  transform: translateY(-1px);
  box-shadow: var(--shadow-lg), var(--shadow-glow);
}

.send-btn:active:not(:disabled) {
  transform: translateY(0);
  box-shadow: var(--shadow-xs);
}

.send-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.slash-suggest {
  position: absolute;
  left: 0;
  right: 0;
  bottom: calc(100% + 6px);
  max-height: 240px;
  overflow-y: auto;
  background: var(--glass-bg-strong);
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-glass);
  padding: 4px;
  z-index: 120;
  backdrop-filter: blur(var(--glass-blur)) saturate(var(--glass-saturate));
  -webkit-backdrop-filter: blur(var(--glass-blur)) saturate(var(--glass-saturate));
}

.slash-item {
  display: flex;
  align-items: baseline;
  gap: 10px;
  width: 100%;
  border: none;
  background: transparent;
  color: inherit;
  text-align: left;
  padding: 8px 10px;
  border-radius: var(--radius-sm);
  cursor: pointer;
}

.slash-item:hover,
.slash-item--active {
  background: var(--layer-active);
}

.slash-name {
  font-family: var(--font-mono);
  font-size: 13px;
  color: var(--accent);
  white-space: nowrap;
  flex-shrink: 0;
}

.slash-tag {
  font-size: 10px;
  padding: 1px 5px;
  border-radius: 3px;
  white-space: nowrap;
  flex-shrink: 0;
}

.slash-tag--skill {
  color: var(--purple);
  background: var(--purple-dim);
}

.slash-tag--command {
  color: var(--text-muted);
  background: var(--layer-glass);
  border: 1px solid var(--glass-border);
}

.slash-hint {
  font-family: var(--font-mono);
  font-size: 11px;
  color: var(--text-muted);
  white-space: nowrap;
  flex-shrink: 0;
}

.slash-desc {
  font-size: 12px;
  color: var(--text-secondary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.slash-fade-enter-active,
.slash-fade-leave-active {
  transition: opacity 0.12s ease, transform 0.12s ease;
}

.slash-fade-enter-from,
.slash-fade-leave-to {
  opacity: 0;
  transform: translateY(4px);
}
</style>

// frontend-next/src/features/send-message/ui/MessageInput.tsx
'use client'

import { useState, useRef, useCallback, useEffect, forwardRef, useImperativeHandle } from 'react'
import { sessionStore } from '@/entities/session'
import { useUserPreferences } from '@/shared/lib/useUserPreferences'
import { formatFileSize } from '@/shared/lib/textParsers'

export interface MessageInputHandle {
  setInput(text: string): void
  addImage(base64: string, mediaType: string): void
  appendText(text: string): void
  clearAttachments(): void
}

interface Attachment {
  name: string
  data: string
  mime_type: string
  size: number
  preview: string // data URL for images
}

interface SlashCommand {
  name: string
  description?: string
  icon?: string
}

interface MessageInputProps {
  sessionId: string
  disabled?: boolean
  running?: boolean
  slashCommands?: SlashCommand[]
  onSlashSelect?: (command: SlashCommand) => void
}

export const MessageInput = forwardRef<MessageInputHandle, MessageInputProps>(function MessageInput(
  { sessionId, disabled = false, running = false, slashCommands = [], onSlashSelect },
  ref,
) {
  const { shouldEnterSend, shouldCtrlEnterSend } = useUserPreferences()

  const [text, setText] = useState('')
  const [sending, setSending] = useState(false)
  const [attachments, setAttachments] = useState<Attachment[]>([])
  const [isComposing, setIsComposing] = useState(false)
  const [compositionEndedRecently, setCompositionEndedRecently] = useState(false)
  const [caretIndex, setCaretIndex] = useState(0)
  const [slashActiveIndex, setSlashActiveIndex] = useState(0)
  const [slashQuery, setSlashQuery] = useState<string | null>(null)

  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)
  const slashListRef = useRef<HTMLDivElement>(null)
  const compositionEndTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  // Filter slash suggestions based on current query
  const slashSuggestions = slashCommands.filter((cmd) => {
    if (!slashQuery) return true
    return cmd.name.toLowerCase().includes(slashQuery.toLowerCase())
  })

  const slashSuggestVisible = !disabled && !isComposing && slashQuery !== null && slashSuggestions.length > 0

  // Auto-resize textarea
  useEffect(() => {
    const ta = textareaRef.current
    if (ta) {
      ta.style.height = 'auto'
      ta.style.height = `${Math.min(ta.scrollHeight, 200)}px`
    }
  }, [text])

  // Cleanup composition timer
  useEffect(() => {
    return () => {
      if (compositionEndTimerRef.current) clearTimeout(compositionEndTimerRef.current)
    }
  }, [])

  // Expose methods to parent
  useImperativeHandle(ref, () => ({
    setInput(value: string) {
      setText(value)
    },
    addImage(base64: string, mediaType: string) {
      const preview = `data:${mediaType};base64,${base64}`
      setAttachments((prev) => [
        ...prev,
        { name: `image-${Date.now()}.png`, data: base64, mime_type: mediaType, size: 0, preview },
      ])
    },
    appendText(value: string) {
      setText((prev) => prev + value)
    },
    clearAttachments() {
      setAttachments([])
    },
  }))

  // Dynamic placeholder
  const placeholderText = (() => {
    if (disabled) return 'Waiting for Claude to finish...'
    if (running) return 'Send follow-up (queued until Claude finishes)...'
    const sendShortcut = shouldEnterSend() ? 'Enter' : 'Ctrl+Enter'
    const newLineShortcut = shouldEnterSend() ? 'Ctrl+Enter' : 'Enter'
    return `Send a message... (${sendShortcut} to send, ${newLineShortcut} for new line, type / for skills)`
  })()

  const sendButtonTitle = (() => {
    const sendShortcut = shouldEnterSend() ? 'Enter' : 'Ctrl+Enter'
    return `Send message (${sendShortcut})`
  })()

  function syncSlashContext(currentText: string, pos: number) {
    // Check if cursor is in a slash command context: "/" followed by text at word start
    const beforeCursor = currentText.slice(0, pos)
    const slashIndex = beforeCursor.lastIndexOf('/')
    if (slashIndex === -1) {
      setSlashQuery(null)
      return
    }
    // Only trigger if the "/" is at word start (preceded by space or start of string)
    if (slashIndex > 0 && beforeCursor[slashIndex - 1] !== ' ' && beforeCursor[slashIndex - 1] !== '\n') {
      setSlashQuery(null)
      return
    }
    const query = beforeCursor.slice(slashIndex + 1)
    // Only show if query doesn't contain spaces (single word after /)
    if (query.includes(' ')) {
      setSlashQuery(null)
      return
    }
    setSlashQuery(query || '')
    setSlashActiveIndex(0)
  }

  function applySlashSelection(command: SlashCommand) {
    if (!slashQuery) return
    // Replace "/query" with the command name
    const beforeCursor = text.slice(0, caretIndex)
    const slashIndex = beforeCursor.lastIndexOf('/')
    const afterCursor = text.slice(caretIndex)
    const newText = beforeCursor.slice(0, slashIndex) + `/${command.name} ` + afterCursor
    setText(newText)
    setSlashQuery(null)
    setSlashActiveIndex(0)
    onSlashSelect?.(command)
    // Focus back to textarea
    setTimeout(() => {
      const ta = textareaRef.current
      if (ta) {
        const pos = slashIndex + command.name.length + 2
        ta.focus()
        ta.setSelectionRange(pos, pos)
      }
    }, 0)
  }

  function scrollSlashActiveIntoView() {
    const container = slashListRef.current
    if (!container) return
    const items = container.querySelectorAll('.slash-item')
    const el = items[slashActiveIndex] as HTMLElement | undefined
    if (el) el.scrollIntoView({ block: 'nearest' })
  }

  const sendMessage = useCallback(
    async (promptText: string) => {
      if ((!promptText.trim() && attachments.length === 0) || sending || disabled) return
      setSending(true)
      try {
        const ws = sessionStore.getWsConnection(sessionId)
        if (ws) {
          if (attachments.length > 0) {
            ws.send({
              action: 'send_prompt',
              prompt: promptText.trim() || 'Please review the attached files.',
              attachments: attachments.map((a) => ({
                name: a.name,
                mime_type: a.mime_type,
                size: a.size,
                data: a.data,
              })),
            })
          } else {
            ws.send({ action: 'send_prompt', prompt: promptText.trim() })
          }
          setText('')
          setAttachments([])
        }
      } finally {
        setSending(false)
      }
    },
    [sessionId, sending, disabled, attachments],
  )

  function handleKeyDown(e: React.KeyboardEvent) {
    if (slashSuggestVisible) {
      const len = slashSuggestions.length
      if (e.key === 'ArrowDown') {
        e.preventDefault()
        setSlashActiveIndex((prev) => (prev + 1) % len)
        setTimeout(scrollSlashActiveIntoView, 0)
        return
      }
      if (e.key === 'ArrowUp') {
        e.preventDefault()
        setSlashActiveIndex((prev) => (prev - 1 + len) % len)
        setTimeout(scrollSlashActiveIntoView, 0)
        return
      }
      if (e.key === 'Enter' || e.key === 'Tab') {
        e.preventDefault()
        applySlashSelection(slashSuggestions[slashActiveIndex])
        return
      }
      if (e.key === 'Escape') {
        e.preventDefault()
        setSlashQuery(null)
        return
      }
    }

    if (e.key === 'Enter') {
      // During or just after IME composition, defer to browser default
      if (isComposing || compositionEndedRecently) return

      const hasCtrl = e.ctrlKey
      const hasCmd = e.metaKey
      const hasModifier = hasCtrl || hasCmd

      if (shouldEnterSend() && !hasModifier) {
        // Mode 1: Enter sends, Ctrl/Cmd+Enter inserts new line
        e.preventDefault()
        sendMessage(text)
      } else if (shouldCtrlEnterSend() && hasModifier) {
        // Mode 2: Ctrl/Cmd+Enter sends, Enter inserts new line
        e.preventDefault()
        sendMessage(text)
      } else if (hasModifier) {
        // Ctrl/Cmd+Enter but current mode doesn't send -> insert newline
        e.preventDefault()
        const ta = textareaRef.current
        if (ta) {
          const start = ta.selectionStart
          const end = ta.selectionEnd
          const newValue = text.slice(0, start) + '\n' + text.slice(end)
          setText(newValue)
          setTimeout(() => {
            ta.selectionStart = ta.selectionEnd = start + 1
          }, 0)
        }
      }
      // Otherwise: let browser default handle it (Enter in non-enter-send mode)
    }
  }

  function handleChange(e: React.ChangeEvent<HTMLTextAreaElement>) {
    setText(e.target.value)
  }

  function handleSelect() {
    const ta = textareaRef.current
    if (ta) {
      setCaretIndex(ta.selectionStart)
      syncSlashContext(ta.value, ta.selectionStart)
    }
  }

  function handleCompositionStart() {
    setIsComposing(true)
  }

  function handleCompositionEnd() {
    setIsComposing(false)
    // Mark that composition just ended, prevent Enter keydown from firing send
    setCompositionEndedRecently(true)
    if (compositionEndTimerRef.current) clearTimeout(compositionEndTimerRef.current)
    compositionEndTimerRef.current = setTimeout(() => {
      setCompositionEndedRecently(false)
    }, 50)
  }

  // ── File attachment handlers ──

  function handlePaste(e: React.ClipboardEvent) {
    const items = e.clipboardData?.items
    if (!items) return
    for (const item of items) {
      if (item.kind === 'file') {
        const file = item.getAsFile()
        if (file) {
          e.preventDefault()
          addFile(file)
          return
        }
      }
    }
  }

  function handleDrop(e: React.DragEvent) {
    e.preventDefault()
    const files = e.dataTransfer?.files
    if (!files) return
    for (const file of Array.from(files)) {
      addFile(file)
    }
  }

  function handleDragOver(e: React.DragEvent) {
    e.preventDefault()
  }

  function handleFileSelect(e: React.ChangeEvent<HTMLInputElement>) {
    const files = e.target.files
    if (!files) return
    for (const file of Array.from(files)) {
      addFile(file)
    }
    e.target.value = ''
  }

  function addFile(file: File) {
    const reader = new FileReader()
    reader.onload = () => {
      const dataUrl = reader.result as string
      const base64 = dataUrl.split(',')[1]
      const isImage = file.type?.startsWith('image/')
      setAttachments((prev) => [
        ...prev,
        {
          name: file.name || 'attachment',
          data: base64,
          mime_type: file.type || 'application/octet-stream',
          size: file.size || 0,
          preview: isImage ? dataUrl : '',
        },
      ])
    }
    reader.readAsDataURL(file)
  }

  function removeAttachment(index: number) {
    setAttachments((prev) => prev.filter((_, i) => i !== index))
  }

  function openFilePicker() {
    fileInputRef.current?.click()
  }

  return (
    <div className="input-area" onDragOver={handleDragOver} onDrop={handleDrop}>
      {/* Attachment previews */}
      {attachments.length > 0 && (
        <div className="attachment-previews">
          {attachments.map((att, index) => (
            <div key={index} className="attachment-item">
              {att.preview ? (
                <div className="attachment-thumb-wrap">
                  <img src={att.preview} alt={att.name} className="attachment-thumb" />
                  <span className="attachment-thumb-name">{att.name}</span>
                </div>
              ) : (
                <div className="attachment-file">
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                    <polyline points="14 2 14 8 20 8" />
                  </svg>
                  <span className="attachment-file-name">{att.name}</span>
                  <span className="attachment-file-size">{formatFileSize(att.size)}</span>
                </div>
              )}
              <button
                className="attachment-remove"
                onClick={() => removeAttachment(index)}
                title="Remove attachment"
                aria-label="Remove attachment"
              >
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <line x1="18" y1="6" x2="6" y2="18" />
                  <line x1="6" y1="6" x2="18" y2="18" />
                </svg>
              </button>
            </div>
          ))}
        </div>
      )}

      {/* Slash command suggestions */}
      {slashSuggestVisible && (
        <div className="slash-suggestions" ref={slashListRef}>
          {slashSuggestions.map((cmd, index) => (
            <div
              key={cmd.name}
              className={`slash-item ${index === slashActiveIndex ? 'slash-item-active' : ''}`}
              onMouseDown={(e) => {
                e.preventDefault()
                applySlashSelection(cmd)
              }}
            >
              <span className="slash-item-name">{cmd.icon || '/'}{cmd.name}</span>
              {cmd.description && <span className="slash-item-desc">{cmd.description}</span>}
            </div>
          ))}
        </div>
      )}

      <textarea
          ref={textareaRef}
          className="input-field"
          placeholder={placeholderText}
          value={text}
          onChange={handleChange}
          onKeyDown={handleKeyDown}
          onSelect={handleSelect}
          onCompositionStart={handleCompositionStart}
          onCompositionEnd={handleCompositionEnd}
          onPaste={handlePaste}
          disabled={disabled}
          rows={1}
          autoComplete="off"
          autoCorrect="off"
          autoCapitalize="off"
          spellCheck={false}
        />
        <div className="input-actions">
          <input
            ref={fileInputRef}
            type="file"
            className="file-input"
            onChange={handleFileSelect}
            multiple
            aria-hidden="true"
          />

          <button
            type="button"
            className="attach-btn"
            onClick={openFilePicker}
            disabled={disabled}
            title="Attach files"
            aria-label="Attach files"
          >
            +
          </button>

          <button
            type="button"
            className="send-btn"
            disabled={(!text.trim() && attachments.length === 0) || disabled || sending}
            onClick={() => sendMessage(text)}
            title={sendButtonTitle}
            aria-label={sendButtonTitle}
          >
            {sending ? (
              <span className="runtime-spinner" style={{ borderColor: 'var(--text-on-accent)', borderTopColor: 'transparent' }} />
            ) : (
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <line x1="22" y1="2" x2="11" y2="13" />
                <polygon points="22 2 15 22 11 13 2 9 22 2" />
              </svg>
            )}
          </button>
        </div>
    </div>
  )
})
