// frontend-next/src/features/evolution/ui/EvolutionDialog.tsx
'use client'

import { useState, useEffect, useCallback } from 'react'
import { useEvolution } from '../model/useEvolution'

interface EvolutionDialogProps {
  visible: boolean
  projectId?: string
  projectDir?: string
  sessionId?: string
  onClose: () => void
  onDraftCreated?: (data: { type: string; revision?: unknown; ruleDraft?: unknown }) => void
}

export function EvolutionDialog({
  visible,
  projectId = '',
  projectDir = '',
  sessionId = '',
  onClose,
  onDraftCreated,
}: EvolutionDialogProps) {
  const { loading, saving, error, lessons, extract, updateLesson, removeLesson, createClaudeDraft } = useEvolution()
  const [target, setTarget] = useState<'claude' | 'rule'>('claude')
  const [rulePath, setRulePath] = useState('')
  const [rulePathsText, setRulePathsText] = useState('')
  const [createdDraft, setCreatedDraft] = useState<{ type: string } | null>(null)

  // Reset state when dialog opens
  useEffect(() => {
    if (visible) {
      setTarget('claude')
      setRulePath('')
      setRulePathsText('')
      setCreatedDraft(null)
      extract({ projectId, projectDir, sessionId })
    }
  }, [visible, projectId, projectDir, sessionId, extract])

  // Close on Escape
  useEffect(() => {
    if (!visible) return
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.stopPropagation()
        onClose()
      }
    }
    window.addEventListener('keydown', handler, true)
    return () => window.removeEventListener('keydown', handler, true)
  }, [visible, onClose])

  const canCreate = !loading && !saving && lessons.length > 0 && (target !== 'rule' || Boolean(rulePath.trim()))

  const handleCreateDraft = useCallback(async () => {
    if (target === 'claude') {
      const data = await createClaudeDraft(projectDir || '')
      if (data?.revision) {
        setCreatedDraft({ type: 'claude' })
        onDraftCreated?.({ type: 'claude', revision: data.revision })
      }
      return
    }
    // Rule draft creation
    if (rulePath.trim()) {
      setCreatedDraft({ type: 'rule' })
      onDraftCreated?.({ type: 'rule', ruleDraft: { path: rulePath.trim(), content: '', pathsText: rulePathsText } })
    }
  }, [target, createClaudeDraft, projectDir, rulePath, rulePathsText, onDraftCreated])

  if (!visible) return null

  return (
    <div className="evolution-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose() }}>
      <div className="evolution-dialog">
        <div className="evolution-header">
          <div>
            <h3>Evolution</h3>
            <p>Extract reusable lessons from this session and turn them into a CLAUDE.md version or rule draft</p>
          </div>
          <button className="close-btn" onClick={onClose}>×</button>
        </div>

        {error && <div className="notice">{error}</div>}
        {createdDraft?.type === 'claude' && (
          <div className="success">Version created. Open Rule to review and apply.</div>
        )}
        {createdDraft?.type === 'rule' && (
          <div className="success">Rule draft created. Open Rule to review and save.</div>
        )}

        <div className="evolution-body">
          <div className="target-panel">
            <button className={`target-btn${target === 'claude' ? ' active' : ''}`} onClick={() => setTarget('claude')}>CLAUDE.md</button>
            <button className={`target-btn${target === 'rule' ? ' active' : ''}`} onClick={() => setTarget('rule')}>Rule</button>
          </div>

          {target === 'rule' && (
            <div className="rule-config">
              <input
                className="rule-input"
                placeholder="Rule path, e.g. frontend.md or vue/components.md"
                value={rulePath}
                onChange={(e) => setRulePath(e.target.value)}
              />
              <textarea
                className="rule-input rule-paths"
                placeholder="paths globs, one per line. Empty means global."
                value={rulePathsText}
                onChange={(e) => setRulePathsText(e.target.value)}
              />
            </div>
          )}

          <div className="evolution-actions">
            <button className="secondary-btn" disabled={loading} onClick={() => extract({ projectId, projectDir, sessionId })}>
              {loading ? 'Extracting...' : 'Re-extract'}
            </button>
            <button className="primary-btn" disabled={!canCreate} onClick={handleCreateDraft}>
              {saving ? 'Creating...' : target === 'rule' ? 'Generate Rule Draft' : 'Generate CLAUDE.md Version'}
            </button>
          </div>

          {loading && <div className="empty">Extracting lessons...</div>}
          {!loading && lessons.length === 0 && <div className="empty">No lessons extracted</div>}
          {!loading && lessons.length > 0 && (
            <div className="lesson-list">
              {lessons.map((lesson, index) => (
                <div key={lesson.id || index} className="lesson-item">
                  <label className="lesson-enabled">
                    <input
                      type="checkbox"
                      checked={lesson.enabled !== false}
                      onChange={(e) => updateLesson(index, { enabled: e.target.checked })}
                    />
                  </label>
                  <div className="lesson-main">
                    <input
                      className="lesson-title"
                      value={lesson.title}
                      onChange={(e) => updateLesson(index, { title: e.target.value })}
                    />
                    <textarea
                      className="lesson-content"
                      value={lesson.content}
                      onChange={(e) => updateLesson(index, { content: e.target.value })}
                    />
                    <div className="lesson-meta">
                      {lesson.type} · {lesson.source_session_id || 'current scope'}
                    </div>
                  </div>
                  <button className="remove-btn" onClick={() => removeLesson(index)}>Remove</button>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// frontend/src/features/evolution/ui/EvolutionDialog.vue
<script setup>
import { ref, watch, computed } from 'vue'
import { useEvolution } from '../model/useEvolution'
import { useDialogManager, useVisibleProxy, useEscapeToClose } from '@shared/lib/useDialogManager'

const props = defineProps({
  visible: { type: Boolean, default: false },
  projectId: { type: String, default: '' },
  projectDir: { type: String, default: '' },
  sessionId: { type: String, default: '' },
})
const emit = defineEmits(['close', 'draft-created'])

const { useDialog } = useDialogManager()
useDialog('evolution', useVisibleProxy(props, emit))

const target = ref('claude')
const rulePath = ref('')
const rulePathsText = ref('')
const canCreate = computed(() => {
  if (loading.value || saving.value || lessons.value.length === 0) return false
  if (target.value === 'rule') return Boolean(rulePath.value.trim())
  return true
})

const {
  loading,
  saving,
  error,
  lessons,
  createdDraft,
  extract,
  updateLesson,
  removeLesson,
  createClaudeDraft,
  createRuleDraft,
  reset,
} = useEvolution()

watch(() => props.visible, (v) => {
  if (v) {
    target.value = 'claude'
    rulePath.value = ''
    rulePathsText.value = ''
    reset()
    extract({ projectId: props.projectId, projectDir: props.projectDir, sessionId: props.sessionId })
  }
})

useEscapeToClose(() => props.visible, () => emit('close'))

async function handleCreateDraft() {
  if (target.value === 'rule') {
    const data = await createRuleDraft({ path: rulePath.value, pathsText: rulePathsText.value })
    if (data?.ruleDraft) {
      emit('draft-created', { type: 'rule', ruleDraft: data.ruleDraft })
    }
    return
  }

  const data = await createClaudeDraft(props.projectDir)
  if (data?.revision) {
    emit('draft-created', { type: 'claude', revision: data.revision })
  }
}
</script>

<template>
  <Teleport to="body">
    <Transition name="dialog-fade">
      <div v-if="visible" class="evolution-overlay" @click.self="emit('close')">
        <div class="evolution-dialog">
          <div class="evolution-header">
            <div>
              <h3>Evolution</h3>
              <p>Extract reusable lessons from this session and turn them into a CLAUDE.md version or rule draft</p>
            </div>
            <button class="close-btn" @click="emit('close')">×</button>
          </div>

          <div v-if="error" class="notice">{{ error }}</div>
          <div v-if="createdDraft?.type === 'claude'" class="success">
            Version created: v{{ createdDraft.revision?.version_no }}. Open Rule to review and apply.
          </div>
          <div v-else-if="createdDraft?.type === 'rule'" class="success">
            Rule draft created. Open Rule to review and save.
          </div>

          <div class="evolution-body">
            <div class="target-panel">
              <button class="target-btn" :class="{ active: target === 'claude' }" @click="target = 'claude'">CLAUDE.md</button>
              <button class="target-btn" :class="{ active: target === 'rule' }" @click="target = 'rule'">Rule</button>
            </div>

            <div v-if="target === 'rule'" class="rule-config">
              <input
                v-model="rulePath"
                class="rule-input"
                placeholder="Rule path, e.g. frontend.md or vue/components.md"
              />
              <textarea
                v-model="rulePathsText"
                class="rule-input rule-paths"
                placeholder="paths globs, one per line. Empty means global."
              ></textarea>
            </div>

            <div class="evolution-actions">
              <button class="secondary-btn" :disabled="loading" @click="extract({ projectId, projectDir, sessionId })">
                {{ loading ? 'Extracting...' : 'Re-extract' }}
              </button>
              <button class="primary-btn" :disabled="!canCreate" @click="handleCreateDraft">
                {{ saving ? 'Creating...' : target === 'rule' ? 'Generate Rule Draft' : 'Generate CLAUDE.md Version' }}
              </button>
            </div>

            <div v-if="loading" class="empty">Extracting lessons...</div>
            <div v-else-if="lessons.length === 0" class="empty">No lessons extracted</div>
            <div v-else class="lesson-list">
              <div v-for="(lesson, index) in lessons" :key="lesson.id || index" class="lesson-item">
                <label class="lesson-enabled">
                  <input
                    type="checkbox"
                    :checked="lesson.enabled !== false"
                    @change="updateLesson(index, { enabled: $event.target.checked })"
                  />
                </label>
                <div class="lesson-main">
                  <input
                    class="lesson-title"
                    :value="lesson.title"
                    @input="updateLesson(index, { title: $event.target.value })"
                  />
                  <textarea
                    class="lesson-content"
                    :value="lesson.content"
                    @input="updateLesson(index, { content: $event.target.value })"
                  ></textarea>
                  <div class="lesson-meta">
                    {{ lesson.type }} · {{ lesson.source_session_id || 'current scope' }}
                  </div>
                </div>
                <button class="remove-btn" @click="removeLesson(index)">Remove</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
.evolution-overlay { position: fixed; inset: 0; z-index: 100; background: var(--bg-overlay); display: flex; align-items: center; justify-content: center; }
.evolution-dialog { width: 860px; max-width: 94vw; max-height: 84vh; background: var(--bg-secondary); border: 1px solid var(--border); border-radius: var(--radius-lg); box-shadow: var(--shadow-xl); overflow: hidden; display: flex; flex-direction: column; }
.evolution-header { display: flex; justify-content: space-between; align-items: center; padding: 14px 18px; border-bottom: 1px solid var(--border); }
.evolution-header h3 { margin: 0; font-size: 15px; color: var(--text-primary); }
.evolution-header p { margin: 3px 0 0; font-size: 12px; color: var(--text-muted); max-width: 560px; }
.close-btn { border: none; background: transparent; color: var(--text-muted); font-size: 24px; cursor: pointer; }
.notice { padding: 8px 18px; color: var(--danger, #ef4444); background: var(--bg-tertiary); border-bottom: 1px solid var(--border); font-size: 12px; }
.success { padding: 8px 18px; color: var(--success, #22c55e); background: var(--bg-tertiary); border-bottom: 1px solid var(--border); font-size: 12px; }
.evolution-body { padding: 14px; overflow-y: auto; min-height: 460px; }
.target-panel { display: flex; gap: 8px; margin-bottom: 12px; }
.target-btn { border: 1px solid var(--border); background: transparent; color: var(--text-secondary); border-radius: var(--radius-sm); padding: 7px 12px; cursor: pointer; }
.target-btn.active { border-color: var(--accent); color: var(--accent); background: var(--accent-dim); }
.rule-config { display: grid; gap: 8px; margin-bottom: 12px; }
.rule-input { border: 1px solid var(--border); border-radius: var(--radius-sm); background: var(--bg-primary); color: var(--text-primary); padding: 8px 10px; font-family: var(--font-sans); }
.rule-paths { min-height: 72px; resize: vertical; }
.evolution-actions { display: flex; justify-content: flex-end; gap: 8px; margin-bottom: 12px; }
.primary-btn, .secondary-btn { border-radius: var(--radius-sm); padding: 7px 12px; cursor: pointer; }
.primary-btn { background: var(--accent); border: 1px solid var(--accent); color: var(--text-on-accent); }
.secondary-btn { background: transparent; border: 1px solid var(--border); color: var(--text-secondary); }
.primary-btn:disabled, .secondary-btn:disabled { opacity: 0.5; cursor: not-allowed; }
.empty { color: var(--text-muted); text-align: center; padding: 40px; font-size: 13px; }
.lesson-list { display: flex; flex-direction: column; gap: 10px; }
.lesson-item { display: flex; gap: 10px; align-items: flex-start; padding: 12px; border: 1px solid var(--border); border-radius: var(--radius-md); background: var(--bg-primary); }
.lesson-enabled { padding-top: 7px; }
.lesson-main { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 8px; }
.lesson-title, .lesson-content { border: 1px solid var(--border); border-radius: var(--radius-sm); background: var(--bg-secondary); color: var(--text-primary); padding: 7px 9px; font-family: var(--font-sans); }
.lesson-title { font-weight: 600; }
.lesson-content { min-height: 74px; resize: vertical; }
.lesson-meta { color: var(--text-muted); font-size: 11px; }
.remove-btn { border: 1px solid var(--border); background: transparent; color: var(--danger, #ef4444); border-radius: var(--radius-sm); padding: 6px 9px; cursor: pointer; }
.dialog-fade-enter-active, .dialog-fade-leave-active { transition: opacity 0.15s ease; }
.dialog-fade-enter-from, .dialog-fade-leave-to { opacity: 0; }
</style>
