// frontend/src/features/session-list/ui/CreateSessionDialog.vue
<script setup>
import { computed, ref, watch, nextTick } from 'vue'
import { pickProjectDirectory } from '@entities/project'
import { useEscapeToClose } from '@shared/lib/useDialogManager'
import { AGENT_PROVIDERS, LAST_AGENT_PROVIDER_KEY } from '@shared/lib/constants'

const props = defineProps({
  visible: {
    type: Boolean,
    required: true,
  },
})

const emit = defineEmits(['confirm', 'cancel'])

useEscapeToClose(() => props.visible, () => emit('cancel'))

const mode = ref('github')
const agentProvider = ref(localStorage.getItem(LAST_AGENT_PROVIDER_KEY) || 'claude')
const projectName = ref('')
const githubUrl = ref('')
const projectPath = ref('')
const creating = ref(false)
const picking = ref(false)
const pickerError = ref('')
const primaryInput = ref(null)

const isMac = /Mac|iPhone|iPad|iPod/.test(window.navigator.platform || window.navigator.userAgent)
const PROJECT_NAME_RE = /^[a-zA-Z0-9][a-zA-Z0-9._-]*$/
const agentProviderOptions = AGENT_PROVIDERS

function getPathBaseName(path) {
  const trimmed = path.trim().replace(/[\\/]+$/, '')
  if (!trimmed) return ''
  const parts = trimmed.split(/[\\/]/)
  return parts[parts.length - 1] || ''
}

const resolvedProjectName = computed(() => {
  if (mode.value === 'local') return getPathBaseName(projectPath.value)
  return projectName.value.trim()
})

const nameError = computed(() => {
  if (mode.value !== 'github') return ''
  const name = projectName.value.trim()
  if (!name) return ''
  if (!PROJECT_NAME_RE.test(name)) {
    return 'Only letters, digits, hyphens, underscores, dots allowed. Must start with a letter or digit.'
  }
  return ''
})

const pathError = computed(() => {
  if (mode.value !== 'local') return ''
  return projectPath.value.trim() ? '' : 'Project path is required.'
})

const canConfirm = computed(() => {
  if (creating.value || picking.value) return false
  if (mode.value === 'local') return !!projectPath.value.trim()
  return !!projectName.value.trim() && !nameError.value
})

watch(() => props.visible, (val) => {
  if (val) {
    nextTick(() => {
      primaryInput.value?.focus()
    })
  } else {
    mode.value = 'github'
    agentProvider.value = localStorage.getItem(LAST_AGENT_PROVIDER_KEY) || 'claude'
    projectName.value = ''
    githubUrl.value = ''
    projectPath.value = ''
    creating.value = false
    picking.value = false
    pickerError.value = ''
  }
})

function extractRepoName(url) {
  if (!url) return ''
  const match = url.match(/\/([^/]+?)(?:\.git)?$/)
  return match ? match[1] : ''
}

function handleGithubUrlInput() {
  const extracted = extractRepoName(githubUrl.value)
  if (extracted && (!projectName.value || projectName.value === extractRepoName(githubUrl.value.slice(0, -1)))) {
    projectName.value = extracted
  }
}

async function handlePickDirectory() {
  if (!isMac || picking.value) return
  pickerError.value = ''
  picking.value = true
  try {
    const result = await pickProjectDirectory()
    if (!props.visible) return
    if (result?.dir_path) {
      mode.value = 'local'
      projectPath.value = result.dir_path
    }
  } catch (err) {
    if (!props.visible) return
    pickerError.value = err.message || 'Failed to pick directory'
  } finally {
    picking.value = false
  }
}

function handleConfirm() {
  if (!canConfirm.value) return
  creating.value = true
  localStorage.setItem(LAST_AGENT_PROVIDER_KEY, agentProvider.value)

  if (mode.value === 'local') {
    emit('confirm', {
      mode: 'local',
      name: resolvedProjectName.value,
      dirPath: projectPath.value.trim(),
      provider: agentProvider.value,
    })
    return
  }

  emit('confirm', {
    mode: 'github',
    name: projectName.value.trim(),
    githubUrl: githubUrl.value.trim(),
    provider: agentProvider.value,
  })
}

function handleCancel() {
  emit('cancel')
}
</script>

<template>
  <Teleport to="body">
    <div
      v-if="visible"
      class="dialog-overlay"
      @click.self="handleCancel"
      role="dialog"
      aria-modal="true"
      aria-label="Create new project"
    >
      <div class="dialog">
        <h2 class="dialog-title">New Project</h2>

        <div class="mode-switch">
          <button
            class="mode-btn"
            :class="{ active: mode === 'github' }"
            @click="mode = 'github'"
          >
            GitHub
          </button>
          <button
            class="mode-btn"
            :class="{ active: mode === 'local' }"
            @click="mode = 'local'"
          >
            Local Folder
          </button>
        </div>

        <template v-if="mode === 'github'">
          <div class="form-group">
            <label class="form-label" for="github-url">
              GitHub URL
            </label>
            <input
              id="github-url"
              ref="primaryInput"
              v-model="githubUrl"
              type="text"
              class="form-input"
              placeholder="https://github.com/user/repo.git"
              @input="handleGithubUrlInput"
            />
            <div class="form-hint">Optional. Clone from a GitHub repository.</div>
          </div>

          <div class="form-group">
            <label class="form-label" for="project-name">
              Project Name <span class="required">*</span>
            </label>
            <input
              id="project-name"
              v-model="projectName"
              type="text"
              class="form-input"
              :class="{ 'form-input-error': nameError }"
              placeholder="e.g. my-awesome-project"
              @keydown.enter="handleConfirm"
            />
            <div v-if="nameError" class="form-error">{{ nameError }}</div>
          </div>
        </template>

        <template v-else>
          <div class="form-group">
            <label class="form-label" for="project-path">
              Project Path <span class="required">*</span>
            </label>
            <div class="path-row">
              <input
                id="project-path"
                ref="primaryInput"
                v-model="projectPath"
                type="text"
                class="form-input"
                :class="{ 'form-input-error': pathError || pickerError }"
                placeholder="/Users/you/workspace/my-project"
                @keydown.enter="handleConfirm"
              />
              <button
                v-if="isMac"
                class="btn-ghost path-picker-btn"
                @click="handlePickDirectory"
                :disabled="picking || creating"
                type="button"
              >
                {{ picking ? 'Opening...' : 'Choose Folder' }}
              </button>
            </div>
            <div class="form-hint">Use a full local path, or choose a folder with the macOS picker.</div>
            <div v-if="pathError" class="form-error">{{ pathError }}</div>
            <div v-else-if="pickerError" class="form-error">{{ pickerError }}</div>
          </div>

          <div class="form-group">
            <label class="form-label">Project Name</label>
            <div class="readonly-value" :class="{ empty: !resolvedProjectName }">
              {{ resolvedProjectName || 'Will be derived from the selected folder name' }}
            </div>
          </div>
        </template>

        <div class="form-group">
          <label class="form-label" for="agent-provider">
            Agent Provider
          </label>
          <select
            id="agent-provider"
            v-model="agentProvider"
            class="form-input form-select"
          >
            <option
              v-for="option in agentProviderOptions"
              :key="option.id"
              :value="option.id"
            >
              {{ option.label }}
            </option>
          </select>
          <div class="form-hint">Claude Code 为默认路径；Cursor ACP 在服务端运行 `agent acp`。</div>
        </div>

        <div class="dialog-actions">
          <button
            class="btn-ghost"
            @click="handleCancel"
            :disabled="creating || picking"
          >
            Cancel
          </button>
          <button
            class="btn-primary"
            @click="handleConfirm"
            :disabled="!canConfirm"
          >
            <span v-if="creating" class="spinner"></span>
            {{ creating ? (mode === 'github' ? (githubUrl ? 'Cloning...' : 'Creating...') : 'Opening...') : 'Create' }}
          </button>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<style scoped>
.dialog {
  width: 520px;
  max-width: calc(100vw - 32px);
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  padding: 24px;
  box-shadow: var(--shadow-xl);
}

.dialog-title {
  margin-bottom: 20px;
}

.mode-switch {
  display: flex;
  gap: 8px;
  margin-bottom: 20px;
}

.mode-btn {
  padding: 7px 12px;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  background: transparent;
  color: var(--text-secondary);
  cursor: pointer;
  font-size: 13px;
  transition: background var(--transition-fast), border-color var(--transition-fast), color var(--transition-fast);
}

.mode-btn.active {
  background: var(--accent-dim);
  border-color: color-mix(in srgb, var(--accent) 35%, var(--border));
  color: var(--accent);
}

.form-group {
  margin-bottom: 16px;
}

.form-label {
  display: block;
  font-size: 13px;
  color: var(--text-secondary);
  margin-bottom: 6px;
}

.required {
  color: var(--red);
}

.path-row {
  display: flex;
  gap: 8px;
}

.path-row .form-input {
  flex: 1;
}

.path-picker-btn {
  flex-shrink: 0;
  white-space: nowrap;
}

.form-input {
  width: 100%;
  padding: 8px 12px;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  background: var(--bg-input);
  color: var(--text-primary);
  font-family: var(--font-sans);
  font-size: 14px;
  line-height: 1.5;
  outline: none;
  transition: border-color var(--transition-fast), box-shadow var(--transition-fast);
}

.form-input:focus {
  border-color: var(--accent);
  box-shadow: var(--ring);
}

.form-input::placeholder {
  color: var(--text-muted);
}

.form-select {
  cursor: pointer;
}

.form-hint {
  font-size: 11px;
  color: var(--text-muted);
  margin-top: 4px;
}

.form-input-error {
  border-color: var(--red);
}

.form-input-error:focus {
  border-color: var(--red);
  box-shadow: 0 0 0 2px rgba(239, 68, 68, 0.15);
}

.form-error {
  font-size: 11px;
  color: var(--red);
  margin-top: 4px;
}

.readonly-value {
  min-height: 38px;
  padding: 8px 12px;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  background: var(--bg-tertiary);
  color: var(--text-primary);
  display: flex;
  align-items: center;
  word-break: break-all;
}

.readonly-value.empty {
  color: var(--text-muted);
}

.dialog-actions {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
  margin-top: 24px;
}

.btn-ghost {
  padding: 8px 16px;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  background: transparent;
  color: var(--text-secondary);
  font-size: 14px;
  cursor: pointer;
  transition: background var(--transition-fast), color var(--transition-fast), border-color var(--transition-fast);
}

.btn-ghost:hover:not(:disabled) {
  background: var(--bg-hover);
  color: var(--text-primary);
}

.btn-ghost:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn-primary {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 8px 16px;
  border: none;
  border-radius: var(--radius-sm);
  background: var(--accent);
  color: var(--text-on-accent);
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: filter var(--transition-fast), transform var(--transition-spring), box-shadow var(--transition-fast);
  box-shadow: var(--shadow-sm);
}

.btn-primary:hover:not(:disabled) {
  filter: brightness(1.1);
  transform: translateY(-1px);
  box-shadow: var(--shadow-md);
}

.btn-primary:active:not(:disabled) {
  transform: translateY(0);
}

.btn-primary:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.spinner {
  width: 14px;
  height: 14px;
  border: 2px solid var(--bg-primary);
  border-top-color: transparent;
  animation: spin 0.6s linear infinite;
}
</style>

// frontend-next/src/features/session-list/ui/CreateSessionDialog.tsx
'use client'

import { useState, useEffect, useRef, useCallback } from 'react'
import { AGENT_PROVIDERS, LAST_AGENT_PROVIDER_KEY } from '@/shared/lib/constants'

interface CreateSessionDialogProps {
  visible: boolean
  onConfirm: (data: { mode: string; name: string; dirPath?: string; githubUrl?: string; provider: string }) => void
  onCancel: () => void
}

const PROJECT_NAME_RE = /^[a-zA-Z0-9][a-zA-Z0-9._-]*$/

function getPathBaseName(path: string): string {
  const trimmed = path.trim().replace(/[\\/]+$/, '')
  if (!trimmed) return ''
  const parts = trimmed.split(/[\\/]/)
  return parts[parts.length - 1] || ''
}

function extractRepoName(url: string): string {
  if (!url) return ''
  const match = url.match(/\/([^/]+?)(?:\.git)?$/)
  return match ? match[1] : ''
}

export function CreateSessionDialog({ visible, onConfirm, onCancel }: CreateSessionDialogProps) {
  const [mode, setMode] = useState<'github' | 'local'>('github')
  const [agentProvider, setAgentProvider] = useState('claude')
  const [projectName, setProjectName] = useState('')
  const [githubUrl, setGithubUrl] = useState('')
  const [projectPath, setProjectPath] = useState('')
  const [creating, setCreating] = useState(false)
  const primaryInputRef = useRef<HTMLInputElement>(null)
  const initializedRef = useRef(false)

  // Reset on visibility change
  useEffect(() => {
    if (visible) {
      setMode('github')
      setAgentProvider(localStorage.getItem(LAST_AGENT_PROVIDER_KEY) || 'claude')
      setProjectName('')
      setGithubUrl('')
      setProjectPath('')
      setCreating(false)
      initializedRef.current = false
      setTimeout(() => primaryInputRef.current?.focus(), 0)
    }
  }, [visible])

  const resolvedProjectName = mode === 'local' ? getPathBaseName(projectPath) : projectName.trim()

  const nameError = (() => {
    if (mode !== 'github') return ''
    const name = projectName.trim()
    if (!name) return ''
    if (!PROJECT_NAME_RE.test(name)) return 'Only letters, digits, hyphens, underscores, dots allowed. Must start with a letter or digit.'
    return ''
  })()

  const pathError = (() => {
    if (mode !== 'local') return ''
    return projectPath.trim() ? '' : 'Project path is required.'
  })()

  const canConfirm = !creating && (mode === 'local' ? !!projectPath.trim() : !!projectName.trim() && !nameError)

  const handleGithubUrlInput = useCallback((value: string) => {
    setGithubUrl(value)
    if (!initializedRef.current) {
      const extracted = extractRepoName(value)
      if (extracted && !projectName) {
        setProjectName(extracted)
        initializedRef.current = true
      }
    }
  }, [projectName])

  const handleConfirm = useCallback(() => {
    if (!canConfirm) return
    setCreating(true)
    localStorage.setItem(LAST_AGENT_PROVIDER_KEY, agentProvider)

    if (mode === 'local') {
      onConfirm({
        mode: 'local',
        name: resolvedProjectName,
        dirPath: projectPath.trim(),
        provider: agentProvider,
      })
      return
    }

    onConfirm({
      mode: 'github',
      name: projectName.trim(),
      githubUrl: githubUrl.trim(),
      provider: agentProvider,
    })
  }, [canConfirm, agentProvider, mode, resolvedProjectName, projectPath, projectName, githubUrl, onConfirm])

  const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleConfirm()
    }
    if (e.key === 'Escape') {
      onCancel()
    }
  }, [handleConfirm, onCancel])

  if (!visible) return null

  return (
    <div className="dialog-overlay" onClick={(e) => { if (e.target === e.currentTarget) onCancel() }} role="dialog" aria-modal="true" aria-label="Create new project" onKeyDown={handleKeyDown}>
      <div className="dialog">
        <h2 className="dialog-title">New Project</h2>

        <div className="mode-switch">
          <button className={`mode-btn${mode === 'github' ? ' active' : ''}`} onClick={() => setMode('github')}>GitHub</button>
          <button className={`mode-btn${mode === 'local' ? ' active' : ''}`} onClick={() => setMode('local')}>Local Folder</button>
        </div>

        {mode === 'github' ? (
          <>
            <div className="form-group">
              <label className="form-label" htmlFor="github-url">GitHub URL</label>
              <input
                id="github-url"
                ref={primaryInputRef}
                value={githubUrl}
                type="text"
                className="form-input"
                placeholder="https://github.com/user/repo.git"
                onChange={(e) => handleGithubUrlInput(e.target.value)}
              />
              <div className="form-hint">Optional. Clone from a GitHub repository.</div>
            </div>
            <div className="form-group">
              <label className="form-label" htmlFor="project-name">Project Name <span className="required">*</span></label>
              <input
                id="project-name"
                value={projectName}
                type="text"
                className={`form-input${nameError ? ' form-input-error' : ''}`}
                placeholder="e.g. my-awesome-project"
                onChange={(e) => setProjectName(e.target.value)}
              />
              {nameError && <div className="form-error">{nameError}</div>}
            </div>
          </>
        ) : (
          <>
            <div className="form-group">
              <label className="form-label" htmlFor="project-path">Project Path <span className="required">*</span></label>
              <div className="path-row">
                <input
                  id="project-path"
                  ref={primaryInputRef}
                  value={projectPath}
                  type="text"
                  className={`form-input${pathError ? ' form-input-error' : ''}`}
                  placeholder="/Users/you/workspace/my-project"
                  onChange={(e) => setProjectPath(e.target.value)}
                />
              </div>
              <div className="form-hint">Use a full local path.</div>
              {pathError && <div className="form-error">{pathError}</div>}
            </div>
            <div className="form-group">
              <label className="form-label">Project Name</label>
              <div className={`readonly-value${!resolvedProjectName ? ' empty' : ''}`}>
                {resolvedProjectName || 'Will be derived from the selected folder name'}
              </div>
            </div>
          </>
        )}

        <div className="form-group">
          <label className="form-label" htmlFor="agent-provider">Agent Provider</label>
          <select
            id="agent-provider"
            value={agentProvider}
            className="form-input form-select"
            onChange={(e) => setAgentProvider(e.target.value)}
          >
            {AGENT_PROVIDERS.map((option) => (
              <option key={option.id} value={option.id}>{option.label}</option>
            ))}
          </select>
          <div className="form-hint">Claude Code 为默认路径；Cursor ACP 在服务端运行 `agent acp`。</div>
        </div>

        <div className="dialog-actions">
          <button className="btn-ghost" onClick={onCancel} disabled={creating}>Cancel</button>
          <button className="btn-primary" onClick={handleConfirm} disabled={!canConfirm}>
            {creating ? (
              <span className="spinner" />
            ) : 'Create'}
          </button>
        </div>
      </div>
    </div>
  )
}
