// frontend-next/src/features/im-binding/ui/ChannelInitDialog.tsx
'use client'

import { useState, useEffect, useCallback, useRef } from 'react'

export interface UiData {
  verification_url?: string
  qr_code_url?: string
  qrcode?: string
  login_status?: string
}

interface ChannelInitDialogProps {
  channelType: string
  displayName?: string
  initMode?: string
  initFields?: string[]
  description?: string
  initStatus?: string
  uiData?: UiData
  disabled?: boolean
  onSubmit: (data: Record<string, string>) => void
  onBack: () => void
}

const FIELD_LABELS: Record<string, string> = {
  app_id: 'App ID',
  app_secret: 'App Secret',
  api_addr: 'API Address',
  ws_addr: 'WebSocket Address',
  admin_secret: 'Admin Secret',
  admin_user_id: 'Admin User ID',
  bot_token: 'Bot Token',
}

export function ChannelInitDialog({
  channelType,
  displayName = '',
  initMode = 'credentials',
  initFields = [],
  description = '',
  initStatus = 'not_initialized',
  uiData = {},
  disabled = false,
  onSubmit,
  onBack,
}: ChannelInitDialogProps) {
  const [formValues, setFormValues] = useState<Record<string, string>>({})
  const qrCanvasRef = useRef<HTMLCanvasElement>(null)
  const [autoPolling, setAutoPolling] = useState(false)
  const pollTimerRef = useRef<ReturnType<typeof setInterval> | null>(null)

  const isCredentialsMode = initMode === 'credentials'
  const isQrMode = initMode === 'qr_login'
  const isPromptMode = initMode === 'prompt'
  const hasVerificationUrl = !!uiData?.verification_url
  const hasQrImage = !!uiData?.qr_code_url

  // Auto-poll for QR login
  useEffect(() => {
    const shouldPoll = (uiData?.verification_url || uiData?.qr_code_url) && uiData?.qrcode
    if (shouldPoll && !pollTimerRef.current) {
      setAutoPolling(true)
      pollTimerRef.current = setInterval(() => {
        if (!disabled) {
          onSubmit({ step: 'poll', qrcode: uiData?.qrcode || '' })
        }
      }, 2500)
    }
    return () => {
      if (pollTimerRef.current) {
        clearInterval(pollTimerRef.current)
        pollTimerRef.current = null
      }
      setAutoPolling(false)
    }
  }, [uiData?.verification_url, uiData?.qr_code_url, uiData?.qrcode, disabled, onSubmit])

  // Generate QR code from verification URL
  useEffect(() => {
    if (hasVerificationUrl && qrCanvasRef.current && uiData.verification_url) {
      import('qrcode').then((QRCode) => {
        QRCode.toCanvas(qrCanvasRef.current!, uiData.verification_url!, {
          width: 200,
          margin: 2,
          color: { dark: '#000000', light: '#ffffff' },
        }).catch(() => {})
      })
    }
  }, [hasVerificationUrl, uiData.verification_url])

  const pollStatusText = uiData?.login_status === 'scaned' || uiData?.login_status === 'scanned'
    ? 'Scanned — confirm on your device'
    : 'Waiting for scan...'

  const loginStatusClass = uiData?.login_status === 'scaned' || uiData?.login_status === 'scanned'
    ? 'status-scanned' : 'status-waiting'

  const handleSubmit = useCallback(() => {
    onSubmit({ ...formValues })
  }, [formValues, onSubmit])

  const handlePollQr = useCallback(() => {
    onSubmit({ step: 'poll', qrcode: uiData?.qrcode || '' })
  }, [onSubmit, uiData?.qrcode])

  const updateField = useCallback((field: string, value: string) => {
    setFormValues(prev => ({ ...prev, [field]: value }))
  }, [])

  return (
    <div className="channel-init">
      <button className="back-link" onClick={onBack}>
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <polyline points="15 18 9 12 15 6" />
        </svg>
        Back
      </button>

      <div className="init-header">
        <h3 className="init-title">Initialize {displayName || channelType}</h3>
        {description && <p className="init-desc">{description}</p>}
      </div>

      {/* Credentials mode */}
      {isCredentialsMode && (
        <>
          <div className="form-fields">
            {initFields.map((field) => (
              <div key={field} className="form-field">
                <label className="field-label">{FIELD_LABELS[field] || field}</label>
                <input
                  className="field-input"
                  type={field.includes('secret') || field.includes('token') ? 'password' : 'text'}
                  placeholder={FIELD_LABELS[field] || field}
                  value={formValues[field] || ''}
                  onChange={(e) => updateField(field, e.target.value)}
                />
              </div>
            ))}
          </div>
          <button className="btn-init" disabled={disabled} onClick={handleSubmit}>
            Initialize
          </button>
        </>
      )}

      {/* QR login mode */}
      {isQrMode && (
        <>
          {hasVerificationUrl ? (
            <div className="qr-section">
              <div className="qr-container">
                <canvas ref={qrCanvasRef} />
              </div>
              <a href={uiData.verification_url} target="_blank" rel="noopener" className="verify-link">
                Or open verification link
              </a>
              <div className="poll-status">
                <div className={`poll-indicator ${loginStatusClass}`}>
                  <div className="spinner-tiny" />
                  <span>{pollStatusText}</span>
                </div>
              </div>
              {!autoPolling && (
                <button className="btn-init" disabled={disabled} onClick={handlePollQr}>
                  Check Status
                </button>
              )}
            </div>
          ) : hasQrImage ? (
            <div className="qr-section">
              <div className="qr-container">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={uiData.qr_code_url} alt="QR Code" className="qr-image" />
              </div>
              <p className="qr-hint">Scan with WeChat to connect</p>
              <div className="poll-status">
                <div className={`poll-indicator ${loginStatusClass}`}>
                  <div className="spinner-tiny" />
                  <span>{pollStatusText}</span>
                </div>
              </div>
              {!autoPolling && (
                <button className="btn-init" disabled={disabled} onClick={handlePollQr}>
                  Check Status
                </button>
              )}
            </div>
          ) : (
            <div className="qr-section">
              <button className="btn-init" disabled={disabled} onClick={() => onSubmit({ step: 'start' })}>
                Get QR Code
              </button>
            </div>
          )}
        </>
      )}

      {/* Prompt-based init mode */}
      {isPromptMode && (
        <div className="prompt-section">
          <p className="prompt-hint">
            This will send setup instructions to your Claude session.
            Follow the prompts to complete initialization (including QR scan if required).
          </p>
          <button className="btn-init" disabled={disabled} onClick={() => onSubmit({ step: 'start' })}>
            Start Setup
          </button>
        </div>
      )}
    </div>
  )
}

// frontend/src/features/im-binding/ui/ChannelInitDialog.vue
<script setup>
import { ref, computed, watch, nextTick, onBeforeUnmount } from 'vue'
import QRCode from 'qrcode'

const props = defineProps({
  channelType: { type: String, required: true },
  displayName: { type: String, default: '' },
  initMode: { type: String, default: 'credentials' },
  initFields: { type: Array, default: () => [] },
  description: { type: String, default: '' },
  initStatus: { type: String, default: 'not_initialized' },
  uiData: { type: Object, default: () => ({}) },
  disabled: { type: Boolean, default: false },
})

const emit = defineEmits(['submit', 'back'])

const formValues = ref({})
const qrCanvas = ref(null)
const isCredentialsMode = computed(() => props.initMode === 'credentials')
const isQrMode = computed(() => props.initMode === 'qr_login')
const isPromptMode = computed(() => props.initMode === 'prompt')
const hasVerificationUrl = computed(() => !!props.uiData?.verification_url)
const hasQrImage = computed(() => !!props.uiData?.qr_code_url)

// Generate QR code from verification_url (e.g. Lark OAuth device flow)
watch(() => props.uiData?.verification_url, async (url) => {
  if (!url) return
  await nextTick()
  if (qrCanvas.value) {
    try {
      await QRCode.toCanvas(qrCanvas.value, url, {
        width: 200,
        margin: 2,
        color: { dark: '#000000', light: '#ffffff' },
      })
    } catch { /* QR render failed silently */ }
  }
}, { immediate: true })

function onSubmit() {
  emit('submit', { ...formValues.value })
}

function onPollQr() {
  emit('submit', { step: 'poll', qrcode: props.uiData?.qrcode || '' })
}

const FIELD_LABELS = {
  app_id: 'App ID',
  app_secret: 'App Secret',
  api_addr: 'API Address',
  ws_addr: 'WebSocket Address',
  admin_secret: 'Admin Secret',
  admin_user_id: 'Admin User ID',
  bot_token: 'Bot Token',
}

function fieldLabel(field) {
  return FIELD_LABELS[field] || field
}

function loginStatusClass(status) {
  if (status === 'scaned' || status === 'scanned') return 'status-scanned'
  return 'status-waiting'
}

// ── Auto-polling for QR login ──
const pollTimer = ref(null)
const isAutoPolling = ref(false)

watch([
  () => props.uiData?.verification_url,
  () => props.uiData?.qr_code_url,
  () => props.uiData?.qrcode,
], ([verifyUrl, qrImgUrl, qrcode]) => {
  stopAutoPoll()
  if ((verifyUrl || qrImgUrl) && qrcode) {
    startAutoPoll()
  }
}, { immediate: true })

function startAutoPoll() {
  if (pollTimer.value) return
  isAutoPolling.value = true
  pollTimer.value = setInterval(() => {
    if (props.disabled) return
    onPollQr()
  }, 2500)
}

function stopAutoPoll() {
  if (pollTimer.value) {
    clearInterval(pollTimer.value)
    pollTimer.value = null
  }
  isAutoPolling.value = false
}

onBeforeUnmount(() => stopAutoPoll())

const pollStatusText = computed(() => {
  const status = props.uiData?.login_status
  if (status === 'scaned' || status === 'scanned') return 'Scanned — confirm on your device'
  return 'Waiting for scan...'
})
</script>

<template>
  <div class="channel-init">
    <button class="back-link" @click="emit('back')">
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <polyline points="15 18 9 12 15 6" />
      </svg>
      Back
    </button>

    <div class="init-header">
      <h3 class="init-title">Initialize {{ displayName || channelType }}</h3>
      <p v-if="description" class="init-desc">{{ description }}</p>
    </div>

    <!-- Credentials mode -->
    <template v-if="isCredentialsMode">
      <div class="form-fields">
        <div v-for="field in initFields" :key="field" class="form-field">
          <label class="field-label">{{ fieldLabel(field) }}</label>
          <input
            v-model="formValues[field]"
            class="field-input"
            :type="field.includes('secret') || field.includes('token') ? 'password' : 'text'"
            :placeholder="fieldLabel(field)"
          />
        </div>
      </div>
      <button
        class="btn-init"
        :disabled="disabled"
        @click="onSubmit"
      >
        Initialize
      </button>
    </template>

    <!-- QR login mode -->
    <template v-else-if="isQrMode">
      <!-- QR from verification URL (e.g. Lark — generate QR from URL) -->
      <div v-if="hasVerificationUrl" class="qr-section">
        <div class="qr-container">
          <canvas ref="qrCanvas"></canvas>
        </div>
        <a
          :href="uiData.verification_url"
          target="_blank"
          rel="noopener"
          class="verify-link"
        >
          Or open verification link
        </a>
        <div class="poll-status">
          <div class="poll-indicator" :class="loginStatusClass(uiData?.login_status)">
            <div class="spinner-tiny"></div>
            <span>{{ pollStatusText }}</span>
          </div>
        </div>
        <button v-if="!isAutoPolling" class="btn-init" :disabled="disabled" @click="onPollQr">
          Check Status
        </button>
      </div>
      <!-- QR from image data (e.g. WeChat — base64 image) -->
      <div v-else-if="hasQrImage" class="qr-section">
        <div class="qr-container">
          <img :src="uiData.qr_code_url" alt="QR Code" class="qr-image" />
        </div>
        <p class="qr-hint">Scan with WeChat to connect</p>
        <div class="poll-status">
          <div class="poll-indicator" :class="loginStatusClass(uiData?.login_status)">
            <div class="spinner-tiny"></div>
            <span>{{ pollStatusText }}</span>
          </div>
        </div>
        <button v-if="!isAutoPolling" class="btn-init" :disabled="disabled" @click="onPollQr">
          Check Status
        </button>
      </div>
      <!-- No QR yet — start button -->
      <div v-else class="qr-section">
        <button class="btn-init" :disabled="disabled" @click="$emit('submit', { step: 'start' })">
          Get QR Code
        </button>
      </div>
    </template>

    <!-- Prompt-based init mode (e.g. Lark — sends setup prompt to Claude session) -->
    <template v-else-if="isPromptMode">
      <div class="prompt-section">
        <p class="prompt-hint">
          This will send setup instructions to your Claude session.
          Follow the prompts to complete initialization (including QR scan if required).
        </p>
        <button class="btn-init" :disabled="disabled" @click="$emit('submit', { step: 'start' })">
          Start Setup
        </button>
      </div>
    </template>
  </div>
</template>

<style scoped>
.channel-init {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.back-link {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  background: none;
  border: none;
  color: var(--text-muted);
  font-size: 12px;
  cursor: pointer;
  padding: 0;
  align-self: flex-start;
  transition: color 0.15s;
}

.back-link:hover {
  color: var(--text-primary);
}

.init-header {
  text-align: center;
}

.init-title {
  font-size: 15px;
  font-weight: 600;
  color: var(--text-primary);
  margin: 0 0 6px;
}

.init-desc {
  font-size: 12px;
  color: var(--text-secondary);
  margin: 0;
  line-height: 1.5;
}

.form-fields {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.form-field {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.field-label {
  font-size: 12px;
  color: var(--text-muted);
  font-weight: 500;
}

.field-input {
  padding: 8px 10px;
  background: var(--bg-input);
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  color: var(--text-primary);
  font-family: var(--font-mono);
  font-size: 13px;
  outline: none;
  transition: border-color var(--transition-fast);
}

.field-input:focus {
  border-color: var(--accent);
}

.field-input::placeholder {
  color: var(--text-muted);
}

.btn-init {
  align-self: center;
  padding: 8px 28px;
  border: 1px solid var(--accent);
  border-radius: var(--radius-sm);
  background: var(--accent-dim);
  color: var(--accent);
  font-size: 14px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.15s;
}

.btn-init:hover:not(:disabled) {
  background: var(--accent);
  color: var(--text-on-accent);
}

.btn-init:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.qr-section {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
}

.qr-container {
  padding: 12px;
  background: #ffffff;
  border-radius: var(--radius-md);
  box-shadow: var(--shadow-sm);
}

.qr-image {
  display: block;
  width: 200px;
  height: 200px;
}

.qr-hint {
  font-size: 13px;
  color: var(--text-secondary);
}

.verify-link {
  font-size: 12px;
  color: var(--accent);
  text-decoration: none;
  transition: opacity 0.15s;
}

.verify-link:hover {
  opacity: 0.8;
  text-decoration: underline;
}

.prompt-section {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 16px;
}

.prompt-hint {
  font-size: 13px;
  color: var(--text-secondary);
  text-align: center;
  line-height: 1.6;
  max-width: 320px;
}

.status-waiting {
  background: var(--yellow-dim, rgba(245, 158, 11, 0.1));
  color: var(--yellow, #f59e0b);
}

.status-scanned {
  background: var(--green-dim, rgba(52, 211, 153, 0.1));
  color: var(--green);
}

.poll-status {
  margin-top: 4px;
}

.poll-indicator {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  font-size: 13px;
  padding: 6px 14px;
  border-radius: var(--radius-sm);
  background: var(--yellow-dim, rgba(245, 158, 11, 0.1));
  color: var(--yellow, #f59e0b);
  transition: background 0.3s, color 0.3s;
}

.poll-indicator.status-scanned {
  background: var(--green-dim, rgba(52, 211, 153, 0.1));
  color: var(--green);
}

.spinner-tiny {
  width: 12px;
  height: 12px;
  border: 2px solid currentColor;
  border-top-color: transparent;
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
  opacity: 0.7;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}
</style>
