// frontend-next/src/features/im-binding/ui/ImButton.tsx
'use client'

interface ImButtonProps {
  disabled?: boolean
  bound?: boolean
  channelType?: string
  instanceName?: string
  onClick: () => void
}

const CHANNEL_LABELS: Record<string, string> = {
  openim: 'OpenIM',
  lark: 'Lark',
  qq: 'QQ',
  weixin: 'WeChat',
}

function getLabel(bound: boolean, channelType: string, instanceName: string): string {
  if (!bound) return 'IM'
  if (instanceName) return instanceName
  return CHANNEL_LABELS[channelType] || channelType || 'IM'
}

export function ImButton({ disabled = false, bound = false, channelType = '', instanceName = '', onClick }: ImButtonProps) {
  const label = getLabel(bound, channelType, instanceName)

  return (
    <button
      className={`glass-btn glass-btn--accent im-btn${bound ? ' im-btn--bound' : ''}`}
      disabled={disabled}
      onClick={onClick}
      title="IM Integration"
    >
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
      </svg>
      <span className="im-btn-label">{label}</span>
      {bound && <span className="im-status-dot" />}
    </button>
  )
}

// frontend/src/features/im-binding/ui/ImButton.vue
<script setup>
defineProps({
  disabled: {
    type: Boolean,
    default: false,
  },
  bound: {
    type: Boolean,
    default: false,
  },
  channelType: {
    type: String,
    default: '',
  },
  instanceName: {
    type: String,
    default: '',
  },
})

const CHANNEL_LABELS = {
  openim: 'OpenIM',
  lark: 'Lark',
  qq: 'QQ',
  weixin: 'WeChat',
}

const emit = defineEmits(['click'])

function getLabel(bound, channelType, instanceName) {
  if (!bound) return 'IM'
  if (instanceName) return instanceName
  return CHANNEL_LABELS[channelType] || channelType || 'IM'
}
</script>

<template>
  <button
    class="glass-btn glass-btn--accent im-btn"
    :class="{ 'im-btn--bound': bound }"
    :disabled="disabled"
    @click="emit('click')"
    title="IM Integration"
  >
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
    </svg>
    <span class="im-btn-label">{{ getLabel(bound, channelType, instanceName) }}</span>
    <span v-if="bound" class="im-status-dot"></span>
  </button>
</template>

<style scoped>
.im-btn {
  position: relative;
  overflow: hidden;
}

.im-btn::before {
  content: '';
  position: absolute;
  inset: 0;
  background: linear-gradient(120deg, transparent, color-mix(in srgb, var(--accent) 18%, transparent), transparent);
  transform: translateX(-120%);
  transition: transform 420ms ease;
}

.im-btn:hover:not(:disabled)::before {
  transform: translateX(120%);
}

.im-btn > * {
  position: relative;
}

.im-btn--bound {
  color: var(--green);
}

.im-btn--bound:hover:not(:disabled) {
  color: var(--green);
  border-color: color-mix(in srgb, var(--accent) 34%, var(--border));
  background: linear-gradient(135deg, color-mix(in srgb, var(--accent) 12%, transparent), transparent);
  box-shadow: var(--shadow-sm);
}

.im-btn--bound:active:not(:disabled) {
  transform: scale(0.96);
  transition-duration: 100ms;
}

.im-btn-label {
  font-weight: 500;
  max-width: 80px;
  overflow: hidden;
  text-overflow: ellipsis;
}

.im-status-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--green);
  box-shadow: 0 0 4px var(--green);
  animation: pulse 1.5s ease-in-out infinite;
}

@keyframes pulse {
  0%, 100% { opacity: 1; box-shadow: 0 0 4px var(--green); }
  50% { opacity: 0.4; box-shadow: 0 0 8px var(--green); }
}

@media (max-width: 768px) {
  .im-btn-label {
    display: none;
  }
}

@media (prefers-reduced-motion: reduce) {
  .im-btn {
    transition: color 0.15s, background 0.15s, border-color 0.15s;
  }
  .im-btn:hover:not(:disabled) {
    transform: none;
  }
  .im-btn:active:not(:disabled) {
    transform: none;
  }
  .im-status-dot {
    animation-duration: 0.01ms;
  }
}
</style>
