// frontend/src/features/git-manager/ui/GitManagerDialog.vue
<script setup>
import { ref, watch } from 'vue'
import { getGitConfig, setGitConfig, listSshKeys, generateSshKey } from '../api/gitApi'
import { useDialogManager, useVisibleProxy, useEscapeToClose } from '@shared/lib/useDialogManager'
import { useTimeout } from '@shared/lib/useTimeout'

const props = defineProps({
  visible: {
    type: Boolean,
    required: true,
  },
})

const emit = defineEmits(['close'])

const { useDialog } = useDialogManager()
useDialog('git-manager', useVisibleProxy(props, emit))
useEscapeToClose(() => props.visible, () => emit('close'))

const loading = ref(false)
const saving = ref(false)
const error = ref('')

// Git config
const userName = ref('')
const userEmail = ref('')
const configSaved = ref(false)

// SSH keys
const sshKeys = ref([])
const generating = ref(false)
const showGenForm = ref(false)
const genKeyType = ref('ed25519')
const genComment = ref('')
const copiedKey = ref('')
const { set: setTimer } = useTimeout()

async function loadData() {
  loading.value = true
  error.value = ''
  configSaved.value = false
  try {
    const [config, keys] = await Promise.all([
      getGitConfig(),
      listSshKeys(),
    ])
    userName.value = config.user_name || ''
    userEmail.value = config.user_email || ''
    sshKeys.value = keys.keys || []
  } catch (e) {
    error.value = e.message || 'Failed to load git config'
  } finally {
    loading.value = false
  }
}

async function handleSaveConfig() {
  saving.value = true
  error.value = ''
  configSaved.value = false
  try {
    const result = await setGitConfig(userName.value, userEmail.value)
    userName.value = result.user_name
    userEmail.value = result.user_email
    configSaved.value = true
    setTimer(() => { configSaved.value = false }, 2000)
  } catch (e) {
    error.value = e.message || 'Failed to save git config'
  } finally {
    saving.value = false
  }
}

async function handleGenerate() {
  generating.value = true
  error.value = ''
  try {
    await generateSshKey(genKeyType.value, genComment.value)
    showGenForm.value = false
    genComment.value = ''
    // Reload keys
    const keys = await listSshKeys()
    sshKeys.value = keys.keys || []
  } catch (e) {
    error.value = e.message || 'Failed to generate SSH key'
  } finally {
    generating.value = false
  }
}

async function copyPublicKey(publicKey, keyName) {
  try {
    await navigator.clipboard.writeText(publicKey)
    copiedKey.value = keyName
    setTimer(() => { copiedKey.value = '' }, 2000)
  } catch {
    // Fallback for non-HTTPS
    const ta = document.createElement('textarea')
    ta.value = publicKey
    document.body.appendChild(ta)
    ta.select()
    document.execCommand('copy')
    document.body.removeChild(ta)
    copiedKey.value = keyName
    setTimer(() => { copiedKey.value = '' }, 2000)
  }
}

watch(() => props.visible, (val) => {
  if (val) {
    loadData()
    showGenForm.value = false
  }
})
</script>

<template>
  <Teleport to="body">
    <div v-if="visible" class="dialog-overlay" @click.self="$emit('close')">
      <div class="dialog">
        <div class="dialog-header">
          <h2>Git Management</h2>
          <button class="close-btn" @click="emit('close')" title="Close">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <line x1="18" y1="6" x2="6" y2="18"/>
              <line x1="6" y1="6" x2="18" y2="18"/>
            </svg>
          </button>
        </div>

        <div v-if="error" class="error-bar">{{ error }}</div>

        <div v-if="loading" class="loading-state">Loading...</div>

        <div v-else class="dialog-body">
          <!-- Git Config Section -->
          <div class="section">
            <h3 class="section-title">Git Identity</h3>
            <p class="section-desc">Configure the global git user for commits.</p>
            <div class="field-row">
              <label>user.name</label>
              <input
                v-model="userName"
                type="text"
                class="field-input"
                placeholder="Velpos"
              />
            </div>
            <div class="field-row">
              <label>user.email</label>
              <input
                v-model="userEmail"
                type="text"
                class="field-input"
                placeholder="velpos@local"
              />
            </div>
            <div class="section-actions">
              <button
                class="btn-primary"
                :disabled="saving"
                @click="handleSaveConfig"
              >
                {{ saving ? 'Saving...' : configSaved ? 'Saved' : 'Save' }}
              </button>
            </div>
          </div>

          <!-- SSH Keys Section -->
          <div class="section">
            <div class="section-header">
              <div>
                <h3 class="section-title">SSH Keys</h3>
                <p class="section-desc">Manage SSH keys for GitHub authentication.</p>
              </div>
              <button
                v-if="!showGenForm"
                class="btn-secondary"
                @click="showGenForm = true"
              >
                + Generate Key
              </button>
            </div>

            <!-- Generate form -->
            <div v-if="showGenForm" class="gen-form">
              <div class="field-row">
                <label>Type</label>
                <select v-model="genKeyType" class="field-input">
                  <option value="ed25519">Ed25519 (recommended)</option>
                  <option value="rsa">RSA</option>
                  <option value="ecdsa">ECDSA</option>
                </select>
              </div>
              <div class="field-row">
                <label>Comment</label>
                <input
                  v-model="genComment"
                  type="text"
                  class="field-input"
                  placeholder="your-email@example.com"
                />
              </div>
              <div class="gen-actions">
                <button
                  class="btn-primary"
                  :disabled="generating"
                  @click="handleGenerate"
                >
                  {{ generating ? 'Generating...' : 'Generate' }}
                </button>
                <button
                  class="btn-secondary"
                  @click="showGenForm = false"
                >
                  Cancel
                </button>
              </div>
            </div>

            <!-- Key list -->
            <div v-if="sshKeys.length === 0 && !showGenForm" class="empty-state">
              No SSH keys found. Generate one to get started.
            </div>
            <div v-for="key in sshKeys" :key="key.name" class="key-card">
              <div class="key-info">
                <div class="key-name">{{ key.name }}</div>
                <div class="key-meta">{{ key.type }} &middot; {{ key.fingerprint }}</div>
              </div>
              <button
                class="btn-copy"
                :class="{ copied: copiedKey === key.name }"
                @click="copyPublicKey(key.public_key, key.name)"
                :title="copiedKey === key.name ? 'Copied!' : 'Copy public key'"
              >
                <svg v-if="copiedKey !== key.name" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2"/>
                  <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>
                </svg>
                <svg v-else width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <polyline points="20 6 9 17 4 12"/>
                </svg>
                {{ copiedKey === key.name ? 'Copied' : 'Copy' }}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<style scoped>
.dialog-overlay {
  background: var(--overlay-glass);
  backdrop-filter: blur(14px) saturate(120%);
  -webkit-backdrop-filter: blur(14px) saturate(120%);
  z-index: 1000;
}

.dialog {
  background: var(--glass-bg-strong);
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-lg, 12px);
  width: 560px;
  max-width: calc(100vw - 32px);
  max-height: calc(100vh - 64px);
  display: flex;
  flex-direction: column;
  box-shadow: var(--shadow-glass);
  backdrop-filter: blur(var(--glass-blur)) saturate(var(--glass-saturate));
  -webkit-backdrop-filter: blur(var(--glass-blur)) saturate(var(--glass-saturate));
}

.dialog-header {
  border-bottom: 1px solid var(--glass-border);
  background: var(--layer-glass);
}

.dialog-header h2 {
  margin: 0;
  font-size: 15px;
  font-weight: 600;
  color: var(--text-primary);
}

.close-btn {
  color: var(--text-secondary);
  transition: background var(--transition-fast), color var(--transition-fast);
}

.close-btn:hover {
  background: var(--layer-active);
  color: var(--accent);
}

.error-bar {
  padding: 8px 20px;
  background: var(--status-error-bg, rgba(255, 59, 48, 0.1));
  color: var(--status-error, #ff3b30);
  font-size: 12px;
  border-bottom: 1px solid var(--border);
}

.loading-state {
  padding: 40px 20px;
  text-align: center;
  color: var(--text-secondary);
  font-size: 13px;
}

.dialog-body {
  padding: 16px 20px;
  overflow-y: auto;
  flex: 1;
}

.section {
  margin-bottom: 24px;
}

.section:last-child {
  margin-bottom: 0;
}

.section-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 12px;
}

.section-title {
  margin: 0 0 4px 0;
  font-size: 13px;
  font-weight: 600;
  color: var(--text-primary);
}

.section-desc {
  margin: 0 0 12px 0;
  font-size: 12px;
  color: var(--text-secondary);
}

.field-row {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 8px;
}

.field-row label {
  min-width: 80px;
  font-size: 12px;
  color: var(--text-secondary);
  font-weight: 500;
}

.field-input {
  flex: 1;
  padding: 6px 10px;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  background: var(--bg-secondary);
  color: var(--text-primary);
  font-size: 12px;
  font-family: var(--font-mono, monospace);
  outline: none;
  transition: border-color var(--transition-fast);
}

.field-input:focus {
  border-color: var(--accent);
}

select.field-input {
  cursor: pointer;
}

.section-actions {
  margin-top: 12px;
  display: flex;
  gap: 8px;
}

.btn-primary {
  padding: 6px 16px;
  border: none;
  border-radius: var(--radius-sm);
  background: var(--accent);
  color: #fff;
  font-size: 12px;
  font-weight: 500;
  cursor: pointer;
  transition: opacity var(--transition-fast);
}

.btn-primary:hover:not(:disabled) {
  opacity: 0.9;
}

.btn-primary:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn-secondary {
  padding: 6px 12px;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  background: transparent;
  color: var(--text-secondary);
  font-size: 12px;
  font-weight: 500;
  cursor: pointer;
  transition: color var(--transition-fast), border-color var(--transition-fast);
  white-space: nowrap;
}

.btn-secondary:hover {
  color: var(--text-primary);
  border-color: var(--accent);
}

.gen-form {
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  padding: 12px;
  margin-bottom: 12px;
}

.gen-actions {
  margin-top: 10px;
  display: flex;
  gap: 8px;
}

.empty-state {
  padding: 20px 0;
  text-align: center;
  color: var(--text-secondary);
  font-size: 12px;
}

.key-card {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 12px;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  margin-bottom: 8px;
  background: var(--bg-secondary);
}

.key-info {
  min-width: 0;
  flex: 1;
}

.key-name {
  font-size: 13px;
  font-weight: 600;
  color: var(--text-primary);
  font-family: var(--font-mono, monospace);
}

.key-meta {
  font-size: 11px;
  color: var(--text-secondary);
  margin-top: 2px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.btn-copy {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 4px 10px;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  background: transparent;
  color: var(--text-secondary);
  font-size: 11px;
  cursor: pointer;
  transition: color var(--transition-fast), border-color var(--transition-fast);
  white-space: nowrap;
  flex-shrink: 0;
  margin-left: 12px;
}

.btn-copy:hover {
  color: var(--text-primary);
  border-color: var(--accent);
}

.btn-copy.copied {
  color: var(--status-success, #34c759);
  border-color: var(--status-success, #34c759);
}
</style>

// frontend-next/src/features/git-manager/ui/GitManagerDialog.tsx
'use client'

import { useEffect, useState, useCallback } from 'react'
import { Modal } from '@/shared/ui/Modal'
import { getGitConfig, setGitConfig, listSshKeys, generateSshKey } from '../api/gitApi'
import type { GitConfig, SshKey } from '../api/gitApi'

interface Props {
  open: boolean
  onClose: () => void
}

export function GitManagerDialog({ open, onClose }: Props) {
  const [loading, setLoading] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')

  const [userName, setUserName] = useState('')
  const [userEmail, setUserEmail] = useState('')
  const [configSaved, setConfigSaved] = useState(false)

  const [sshKeys, setSshKeys] = useState<SshKey[]>([])
  const [generating, setGenerating] = useState(false)
  const [showGenForm, setShowGenForm] = useState(false)
  const [genKeyType, setGenKeyType] = useState('ed25519')
  const [genComment, setGenComment] = useState('')
  const [copiedKey, setCopiedKey] = useState('')

  const loadData = useCallback(async () => {
    setLoading(true)
    setError('')
    setConfigSaved(false)
    try {
      const [config, keys] = await Promise.all([getGitConfig(), listSshKeys()])
      setUserName(config.user_name || '')
      setUserEmail(config.user_email || '')
      setSshKeys(keys.keys || [])
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to load git config')
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    if (open) {
      loadData()
      setShowGenForm(false)
    }
  }, [open, loadData])

  useEffect(() => {
    if (!configSaved) return
    const t = setTimeout(() => setConfigSaved(false), 2000)
    return () => clearTimeout(t)
  }, [configSaved])

  async function handleSaveConfig() {
    setSaving(true)
    setError('')
    setConfigSaved(false)
    try {
      const result = await setGitConfig(userName, userEmail)
      setUserName(result.user_name)
      setUserEmail(result.user_email)
      setConfigSaved(true)
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to save git config')
    } finally {
      setSaving(false)
    }
  }

  async function handleGenerate() {
    setGenerating(true)
    setError('')
    try {
      await generateSshKey(genKeyType, genComment)
      setShowGenForm(false)
      setGenComment('')
      const keys = await listSshKeys()
      setSshKeys(keys.keys || [])
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to generate SSH key')
    } finally {
      setGenerating(false)
    }
  }

  async function copyPublicKey(publicKey: string, keyName: string) {
    try {
      await navigator.clipboard.writeText(publicKey)
      setCopiedKey(keyName)
      setTimeout(() => setCopiedKey(''), 2000)
    } catch {
      const ta = document.createElement('textarea')
      ta.value = publicKey
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
      setCopiedKey(keyName)
      setTimeout(() => setCopiedKey(''), 2000)
    }
  }

  return (
    <Modal open={open} onClose={onClose} title="Git Management" width="560px">
      {error && <div className="settings-error">{error}</div>}

      {loading ? (
        <div className="settings-loading">Loading...</div>
      ) : (
        <>
          {renderIdentitySection()}
          {renderSshSection()}
        </>
      )}
    </Modal>
  )

  function renderIdentitySection() {
    return (
      <div className="git-section">
        <h3 className="git-section-title">Git Identity</h3>
        <p className="git-section-desc">Configure the global git user for commits.</p>
        <div className="git-field-row">
          <label>user.name</label>
          <input
            className="settings-input git-mono-input"
            type="text"
            value={userName}
            onChange={e => setUserName(e.target.value)}
            placeholder="Velpos"
          />
        </div>
        <div className="git-field-row">
          <label>user.email</label>
          <input
            className="settings-input git-mono-input"
            type="text"
            value={userEmail}
            onChange={e => setUserEmail(e.target.value)}
            placeholder="velpos@local"
          />
        </div>
        <div className="git-section-actions">
          <button
            className="settings-btn settings-btn-primary"
            onClick={handleSaveConfig}
            disabled={saving}
          >
            {saving ? 'Saving...' : configSaved ? 'Saved' : 'Save'}
          </button>
        </div>
      </div>
    )
  }

  function renderSshSection() {
    return (
      <div className="git-section">
        <div className="git-section-header">
          <div>
            <h3 className="git-section-title">SSH Keys</h3>
            <p className="git-section-desc">Manage SSH keys for GitHub authentication.</p>
          </div>
          {!showGenForm && (
            <button className="settings-btn" onClick={() => setShowGenForm(true)}>
              + Generate Key
            </button>
          )}
        </div>

        {showGenForm && (
          <div className="git-gen-form">
            <div className="git-field-row">
              <label>Type</label>
              <select className="settings-select" value={genKeyType} onChange={e => setGenKeyType(e.target.value)}>
                <option value="ed25519">Ed25519 (recommended)</option>
                <option value="rsa">RSA</option>
                <option value="ecdsa">ECDSA</option>
              </select>
            </div>
            <div className="git-field-row">
              <label>Comment</label>
              <input
                className="settings-input"
                type="text"
                value={genComment}
                onChange={e => setGenComment(e.target.value)}
                placeholder="your-email@example.com"
              />
            </div>
            <div className="git-gen-actions">
              <button className="settings-btn settings-btn-primary" onClick={handleGenerate} disabled={generating}>
                {generating ? 'Generating...' : 'Generate'}
              </button>
              <button className="settings-btn" onClick={() => setShowGenForm(false)}>
                Cancel
              </button>
            </div>
          </div>
        )}

        {sshKeys.length === 0 && !showGenForm && (
          <div className="git-empty">No SSH keys found. Generate one to get started.</div>
        )}

        {sshKeys.map(key => (
          <div key={key.name} className="git-key-card">
            <div className="git-key-info">
              <div className="git-key-name">{key.name}</div>
              <div className="git-key-meta">{key.type} &middot; {key.fingerprint}</div>
            </div>
            <button
              className={`git-btn-copy${copiedKey === key.name ? ' copied' : ''}`}
              onClick={() => copyPublicKey(key.public_key, key.name)}
              title={copiedKey === key.name ? 'Copied!' : 'Copy public key'}
            >
              {copiedKey === key.name ? (
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <polyline points="20 6 9 17 4 12" />
                </svg>
              ) : (
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                  <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                </svg>
              )}
              {copiedKey === key.name ? 'Copied' : 'Copy'}
            </button>
          </div>
        ))}
      </div>
    )
  }
}
