// frontend-next/src/features/command-palette/ui/CommandPalettePopover.tsx
'use client'

import { useState, useEffect, useRef, useCallback, useMemo } from 'react'
import type { CommandItem } from '../api/commandApi'
import type { PolicyRow } from '../model/useCommandPalette'

interface Props {
  visible: boolean
  commands: CommandItem[]
  policyRows: PolicyRow[]
  loading: boolean
  searchQuery: string
  onSelect: (cmd: CommandItem) => void
  onClose: () => void
  onSearchQueryChange: (q: string) => void
  onPolicyChange?: (row: PolicyRow, patch: Record<string, unknown>) => void
}

type TabKey = 'all' | 'skill' | 'command' | 'mcp'

export function CommandPalettePopover({
  visible,
  commands,
  policyRows,
  loading,
  searchQuery,
  onSelect,
  onClose,
  onSearchQueryChange,
  onPolicyChange,
}: Props) {
  const popoverRef = useRef<HTMLDivElement>(null)
  const searchRef = useRef<HTMLInputElement>(null)
  const listRef = useRef<HTMLDivElement>(null)
  const [activeIndex, setActiveIndex] = useState(0)
  const [manageMode, setManageMode] = useState(false)
  const [activeTab, setActiveTab] = useState<TabKey>('all')

  const tabs = useMemo(() => {
    const items: { key: TabKey; label: string }[] = [
      { key: 'all', label: 'All' },
      { key: 'skill', label: 'Skills' },
      { key: 'command', label: 'Commands' },
    ]
    if (commands.some((cmd) => cmd.type === 'mcp')) {
      items.push({ key: 'mcp', label: 'MCP' })
    }
    return items
  }, [commands])

  const filteredCommands = useMemo(() => {
    let list: CommandItem[] = commands
    if (activeTab !== 'all') {
      list = commands.filter((c) => c.type === activeTab)
    }
    const q = searchQuery.toLowerCase()
    if (!q) return list
    return list.filter(
      (c) =>
        c.name.toLowerCase().includes(q) ||
        (c.description || '').toLowerCase().includes(q)
    )
  }, [commands, searchQuery, activeTab])

  const filteredPolicyRows = useMemo(() => {
    let list: PolicyRow[] = policyRows
    if (activeTab !== 'all') {
      list = policyRows.filter((row) => row.command_type === activeTab)
    }
    const q = searchQuery.toLowerCase()
    if (!q) return list
    return list.filter(
      (row) =>
        row.command_name.toLowerCase().includes(q) ||
        (row.description || '').toLowerCase().includes(q)
    )
  }, [policyRows, searchQuery, activeTab])

  // Reset index when filtered list changes
  useEffect(() => {
    setActiveIndex(0)
  }, [filteredCommands.length])

  // Focus search input when opened
  useEffect(() => {
    if (visible && searchRef.current) {
      searchRef.current.focus()
    }
  }, [visible])

  // Close on Escape
  useEffect(() => {
    if (!visible) return
    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape') {
        onClose()
      }
    }
    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [visible, onClose])

  // Close on click outside
  useEffect(() => {
    if (!visible) return
    function handleClickOutside(e: MouseEvent) {
      if (popoverRef.current && !popoverRef.current.contains(e.target as Node)) {
        onClose()
      }
    }
    // Delay to avoid immediate close on trigger click
    const timer = setTimeout(() => {
      document.addEventListener('mousedown', handleClickOutside)
    }, 0)
    return () => {
      clearTimeout(timer)
      document.removeEventListener('mousedown', handleClickOutside)
    }
  }, [visible, onClose])

  const scrollActiveIntoView = useCallback(() => {
    const container = listRef.current
    if (!container) return
    const items = container.querySelectorAll('.cmd-item')
    const el = items[activeIndex]
    if (el) el.scrollIntoView({ block: 'nearest' })
  }, [activeIndex])

  function handleKeyDown(e: React.KeyboardEvent) {
    const len = manageMode ? 0 : filteredCommands.length
    if (!len && e.key !== 'Escape') return

    const hasModifiers = e.ctrlKey || e.metaKey
    if (hasModifiers) return

    if (e.key === 'ArrowDown') {
      e.preventDefault()
      setActiveIndex((prev) => (prev + 1) % len)
      requestAnimationFrame(() => scrollActiveIntoView())
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      setActiveIndex((prev) => (prev - 1 + len) % len)
      requestAnimationFrame(() => scrollActiveIntoView())
    } else if (e.key === 'Enter') {
      e.preventDefault()
      const item = filteredCommands[activeIndex]
      if (item && item.type !== 'mcp') {
        selectItem(item)
      }
    }
  }

  function commandLabel(cmd: CommandItem) {
    if (cmd.type === 'mcp') return cmd.name
    return `/${cmd.name}`
  }

  function commandTag(cmd: CommandItem) {
    if (cmd.type === 'skill') return 'skill'
    if (cmd.type === 'mcp') return 'mcp'
    return 'built-in'
  }

  function commandTagClass(cmd: CommandItem) {
    if (cmd.type === 'skill') return 'cmd-tag--prompt'
    if (cmd.type === 'mcp') return 'cmd-tag--mcp'
    return 'cmd-tag--local'
  }

  function selectItem(cmd: CommandItem) {
    if (cmd?.type === 'mcp') return
    if (cmd) {
      onSelect(cmd)
    }
  }

  if (!visible) return null

  return (
    <div
      ref={popoverRef}
      className="cmd-popover"
      onKeyDown={handleKeyDown}
      role="dialog"
      aria-label="Command palette"
    >
      {/* Tabs */}
      <div className="cmd-tabs">
        {tabs.map((tab) => (
          <button
            key={tab.key}
            className={`cmd-tab${activeTab === tab.key ? ' cmd-tab--active' : ''}`}
            onClick={() => setActiveTab(tab.key)}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Search */}
      <div className="cmd-search-wrap">
        <svg className="cmd-search-icon" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <circle cx="11" cy="11" r="8" /><line x1="21" y1="21" x2="16.65" y2="16.65" />
        </svg>
        <input
          ref={searchRef}
          className="cmd-search"
          type="text"
          placeholder="Search commands..."
          value={searchQuery}
          onChange={(e) => onSearchQueryChange(e.target.value)}
          autoComplete="off"
        />
      </div>

      {/* Loading */}
      {loading && <div className="cmd-loading">Loading...</div>}

      {/* Command List */}
      {!manageMode && (
        <div ref={listRef} className="cmd-list">
          {filteredCommands.length === 0 && !loading && (
            <div className="cmd-empty">No matching commands</div>
          )}
          {filteredCommands.map((cmd, idx) => (
            <div
              key={`${cmd.name}:${cmd.type}`}
              className={`cmd-item${idx === activeIndex ? ' cmd-item--active' : ''}`}
              onClick={() => selectItem(cmd)}
              onMouseEnter={() => setActiveIndex(idx)}
            >
              <span className="cmd-item-name">{commandLabel(cmd)}</span>
              <span className={`cmd-tag ${commandTagClass(cmd)}`}>{commandTag(cmd)}</span>
              {cmd.description && (
                <span className="cmd-item-desc">{cmd.description}</span>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Policy Manage Mode */}
      {manageMode && (
        <div className="cmd-list cmd-policy-list">
          {filteredPolicyRows.map((row) => (
            <div key={`${row.command_name}:${row.command_type}`} className="cmd-policy-row">
              <span className="cmd-policy-name">/{row.command_name}</span>
              <label className="cmd-policy-toggle">
                <input
                  type="checkbox"
                  checked={row.enabled}
                  onChange={() => onPolicyChange?.(row, { enabled: !row.enabled })}
                />
                Enabled
              </label>
              <label className="cmd-policy-toggle">
                <input
                  type="checkbox"
                  checked={row.visible}
                  onChange={() => onPolicyChange?.(row, { visible: !row.visible })}
                />
                Visible
              </label>
            </div>
          ))}
        </div>
      )}

      <style>{`
        .cmd-popover {
          position: absolute;
          bottom: 100%;
          left: 0;
          right: 0;
          margin-bottom: 8px;
          background: var(--bg-secondary);
          border: 1px solid var(--glass-border);
          border-radius: var(--radius-lg);
          box-shadow: var(--shadow-glass);
          max-height: 360px;
          display: flex;
          flex-direction: column;
          overflow: hidden;
          z-index: 100;
          backdrop-filter: blur(16px) saturate(140%);
        }
        .cmd-tabs {
          display: flex;
          gap: 4px;
          padding: 8px 12px 0;
          flex-shrink: 0;
        }
        .cmd-tab {
          padding: 4px 10px;
          font-size: 11px;
          font-weight: 600;
          color: var(--text-muted);
          background: transparent;
          border: none;
          border-radius: var(--radius-sm);
          cursor: pointer;
          transition: color var(--transition-fast), background var(--transition-fast);
        }
        .cmd-tab:hover { color: var(--text-primary); background: var(--bg-hover); }
        .cmd-tab--active { color: var(--accent); background: var(--accent-dim); }
        .cmd-search-wrap {
          position: relative;
          margin: 8px 12px;
          flex-shrink: 0;
        }
        .cmd-search-icon {
          position: absolute;
          left: 10px;
          top: 50%;
          transform: translateY(-50%);
          color: var(--text-muted);
          pointer-events: none;
        }
        .cmd-search {
          width: 100%;
          height: 32px;
          padding: 0 10px 0 32px;
          background: var(--bg-input);
          border: 1px solid var(--glass-border);
          border-radius: var(--radius-md);
          color: var(--text-primary);
          font-size: 13px;
          outline: none;
        }
        .cmd-search:focus { border-color: var(--accent); }
        .cmd-loading {
          padding: 12px;
          text-align: center;
          color: var(--text-muted);
          font-size: 12px;
        }
        .cmd-list {
          overflow-y: auto;
          flex: 1;
          padding: 4px 8px 8px;
        }
        .cmd-empty {
          padding: 24px 0;
          text-align: center;
          color: var(--text-muted);
          font-size: 13px;
        }
        .cmd-item {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 6px 10px;
          border-radius: var(--radius-md);
          cursor: pointer;
          transition: background var(--transition-fast);
        }
        .cmd-item:hover,
        .cmd-item--active { background: var(--bg-hover); }
        .cmd-item-name { font-size: 13px; font-weight: 500; color: var(--text-primary); }
        .cmd-item-desc {
          font-size: 11px;
          color: var(--text-muted);
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
          flex: 1;
        }
        .cmd-tag {
          font-size: 10px;
          font-weight: 600;
          padding: 2px 6px;
          border-radius: 999px;
          flex-shrink: 0;
        }
        .cmd-tag--local { background: var(--layer-active); color: var(--text-secondary); }
        .cmd-tag--prompt { background: color-mix(in srgb, var(--accent) 15%, transparent); color: var(--accent); }
        .cmd-tag--mcp { background: color-mix(in srgb, #a855f7 15%, transparent); color: #a855f7; }
        .cmd-policy-list { padding: 4px 8px 8px; }
        .cmd-policy-row {
          display: flex;
          align-items: center;
          gap: 12px;
          padding: 6px 10px;
          border-radius: var(--radius-md);
        }
        .cmd-policy-name { font-size: 13px; font-weight: 500; color: var(--text-primary); min-width: 120px; }
        .cmd-policy-toggle {
          display: flex;
          align-items: center;
          gap: 4px;
          font-size: 12px;
          color: var(--text-secondary);
          cursor: pointer;
        }
        .cmd-policy-toggle input { cursor: pointer; }
      `}</style>
    </div>
  )
}

// frontend/src/features/command-palette/ui/CommandPalettePopover.vue
<script setup>
import { ref, computed, watch, nextTick } from 'vue'
import { useClickOutside } from '@shared/lib/useClickOutside'

const props = defineProps({
  visible: {
    type: Boolean,
    default: false,
  },
  commands: {
    type: Array,
    default: () => [],
  },
  policyRows: {
    type: Array,
    default: () => [],
  },
  loading: {
    type: Boolean,
    default: false,
  },
  searchQuery: {
    type: String,
    default: '',
  },
})

const emit = defineEmits(['select', 'close', 'update:searchQuery', 'policy-change'])

const popoverEl = ref(null)
const searchEl = ref(null)
const listEl = ref(null)
const activeIndex = ref(0)
const manageMode = ref(false)
const activeTab = ref('all')

function filterByTab(items, typeField = 'type') {
  if (activeTab.value === 'all') return items
  return items.filter(c => c[typeField] === activeTab.value)
}

const filteredCommands = computed(() => {
  let list = filterByTab(props.commands)
  const q = props.searchQuery.toLowerCase()
  if (!q) return list
  return list.filter(
    c => c.name.toLowerCase().includes(q) || c.description.toLowerCase().includes(q)
  )
})

const filteredPolicyRows = computed(() => {
  let list = filterByTab(props.policyRows, 'command_type')
  const q = props.searchQuery.toLowerCase()
  if (!q) return list
  return list.filter(row => (
    row.command_name.toLowerCase().includes(q)
    || (row.description || '').toLowerCase().includes(q)
  ))
})

watch(() => props.visible, (val) => {
  if (val) {
    activeIndex.value = 0
    nextTick(() => searchEl.value?.focus())
  }
})

watch(() => props.searchQuery, () => {
  activeIndex.value = 0
})

useClickOutside(popoverEl, () => {
  if (props.visible) emit('close')
})

function handleKeydown(e) {
  const len = manageMode.value ? 0 : filteredCommands.value.length
  if (!len && e.key !== 'Escape') return

  // 如果有修饰键（全局快捷键），不处理，让事件传播到全局处理器
  const hasModifiers = e.ctrlKey || e.metaKey
  if (hasModifiers) {
    return // 不阻止事件，让全局快捷键处理器接管
  }

  if (e.key === 'ArrowDown') {
    e.preventDefault()
    activeIndex.value = (activeIndex.value + 1) % len
    nextTick(() => scrollActiveIntoView())
  } else if (e.key === 'ArrowUp') {
    e.preventDefault()
    activeIndex.value = (activeIndex.value - 1 + len) % len
    nextTick(() => scrollActiveIntoView())
  } else if (e.key === 'Enter') {
    e.preventDefault()
    const item = filteredCommands.value[activeIndex.value]
    if (item?.type !== 'mcp') {
      selectItem(item)
    }
  } else if (e.key === 'Escape') {
    e.preventDefault()
    emit('close')
  }
}

const tabs = computed(() => {
  const items = [
    { key: 'all', label: 'All' },
    { key: 'skill', label: 'Skills' },
    { key: 'command', label: 'Commands' },
  ]
  if (props.commands.some((cmd) => cmd.type === 'mcp')) {
    items.push({ key: 'mcp', label: 'MCP' })
  }
  return items
})

function commandLabel(cmd) {
  if (cmd.type === 'mcp') return cmd.name
  return `/${cmd.name}`
}

function commandTag(cmd) {
  if (cmd.type === 'skill') return 'skill'
  if (cmd.type === 'mcp') return 'mcp'
  return 'built-in'
}

function commandTagClass(cmd) {
  if (cmd.type === 'skill') return 'cmd-tag--prompt'
  if (cmd.type === 'mcp') return 'cmd-tag--mcp'
  return 'cmd-tag--local'
}

function selectItem(cmd) {
  if (cmd?.type === 'mcp') return
  if (cmd) {
    emit('select', cmd)
  }
}

function scrollActiveIntoView() {
  const container = listEl.value
  if (!container) return
  const items = container.querySelectorAll('.cmd-item')
  const el = items[activeIndex.value]
  if (el) el.scrollIntoView({ block: 'nearest' })
}

function onSearchInput(e) {
  emit('update:searchQuery', e.target.value)
}
</script>

<template>
  <div v-if="visible" ref="popoverEl" class="cmd-popover" @keydown="handleKeydown">
    <div class="cmd-search-wrapper">
      <svg class="cmd-search-icon" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <circle cx="11" cy="11" r="8" />
        <line x1="21" y1="21" x2="16.65" y2="16.65" />
      </svg>
      <input
        ref="searchEl"
        class="cmd-search"
        :value="searchQuery"
        @input="onSearchInput"
        placeholder="Search..."
        type="text"
      />
    </div>

    <div class="cmd-toolbar">
      <div class="cmd-tabs">
        <button
          v-for="tab in tabs"
          :key="tab.key"
          class="cmd-tab-btn"
          :class="{ active: activeTab === tab.key }"
          @click="activeTab = tab.key; activeIndex = 0"
        >{{ tab.label }}</button>
      </div>
      <button class="cmd-manage-btn" @click="manageMode = !manageMode">
        {{ manageMode ? 'Browse' : 'Manage' }}
      </button>
    </div>

    <div ref="listEl" class="cmd-list">
      <div v-if="loading" class="cmd-loading">Loading commands...</div>
      <template v-else-if="manageMode">
        <div v-if="filteredPolicyRows.length === 0" class="cmd-empty">No commands found</div>
        <div
          v-for="row in filteredPolicyRows"
          :key="row.command_name + ':' + row.command_type"
          class="cmd-policy-item"
        >
          <div class="cmd-policy-main">
            <span class="cmd-name">/{{ row.command_name }}</span>
            <span class="cmd-tag" :class="row.command_type === 'skill' ? 'cmd-tag--prompt' : 'cmd-tag--local'">
              {{ row.command_type === 'skill' ? 'skill' : 'built-in' }}
            </span>
            <span class="cmd-desc">{{ row.description || 'Policy override' }}</span>
          </div>
          <div class="cmd-policy-actions">
            <button
              class="cmd-policy-btn"
              :class="{ active: row.enabled }"
              @click="emit('policy-change', row, { enabled: !row.enabled })"
            >
              {{ row.enabled ? 'Enabled' : 'Disabled' }}
            </button>
            <button
              class="cmd-policy-btn"
              :class="{ active: row.visible }"
              @click="emit('policy-change', row, { visible: !row.visible })"
            >
              {{ row.visible ? 'Visible' : 'Hidden' }}
            </button>
          </div>
        </div>
      </template>
      <template v-else>
        <div v-if="filteredCommands.length === 0" class="cmd-empty">No commands found</div>
        <div
          v-else
          v-for="(cmd, index) in filteredCommands"
          :key="cmd.name + ':' + cmd.type"
          class="cmd-item"
          :class="{
            'cmd-item--active': index === activeIndex,
            'cmd-item--readonly': cmd.type === 'mcp',
          }"
          @click="selectItem(cmd)"
          @mouseenter="activeIndex = index"
        >
          <span class="cmd-name">{{ commandLabel(cmd) }}</span>
          <span class="cmd-tag" :class="commandTagClass(cmd)">
            {{ commandTag(cmd) }}
          </span>
          <span class="cmd-desc">{{ cmd.description }}</span>
        </div>
      </template>
    </div>
  </div>
</template>

<style scoped>
.cmd-popover {
  position: absolute;
  bottom: 100%;
  left: 0;
  right: 0;
  margin-bottom: 6px;
  background: var(--glass-bg-strong);
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-glass);
  max-height: 320px;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  z-index: 100;
  backdrop-filter: blur(var(--glass-blur)) saturate(var(--glass-saturate));
  -webkit-backdrop-filter: blur(var(--glass-blur)) saturate(var(--glass-saturate));
}

.cmd-search-wrapper {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  border-bottom: 1px solid var(--glass-border);
  background: var(--layer-glass);
}

.cmd-search-icon {
  color: var(--text-muted);
  flex-shrink: 0;
}

.cmd-search {
  flex: 1;
  background: none;
  border: none;
  outline: none;
  color: var(--text-primary);
  font-size: 13px;
  font-family: var(--font-sans);
}

.cmd-manage-btn {
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-sm);
  background: color-mix(in srgb, var(--glass-bg) 42%, transparent);
  color: var(--text-secondary);
  font-size: 11px;
  padding: 3px 8px;
  cursor: pointer;
  transition: color var(--transition-fast), background var(--transition-fast), border-color var(--transition-fast), box-shadow var(--transition-fast);
}

.cmd-manage-btn:hover {
  color: var(--accent);
  background: var(--layer-active);
  border-color: var(--accent);
  box-shadow: var(--shadow-sm);
}

.cmd-search::placeholder {
  color: var(--text-muted);
}

.cmd-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 4px 8px;
  border-bottom: 1px solid var(--glass-border);
}

.cmd-tabs {
  display: flex;
  gap: 2px;
  background: color-mix(in srgb, var(--glass-bg) 30%, transparent);
  border-radius: var(--radius-sm);
  padding: 2px;
}

.cmd-tab-btn {
  border: none;
  border-radius: var(--radius-sm);
  background: transparent;
  color: var(--text-muted);
  font-size: 11px;
  padding: 3px 10px;
  cursor: pointer;
  transition: color var(--transition-fast), background var(--transition-fast);
}

.cmd-tab-btn:hover {
  color: var(--text-primary);
}

.cmd-tab-btn.active {
  color: var(--accent);
  background: var(--layer-active);
}

.cmd-list {
  overflow-y: auto;
  padding: 4px;
}

.cmd-item {
  display: flex;
  align-items: baseline;
  gap: 12px;
  padding: 8px 10px;
  border-radius: var(--radius-sm);
  cursor: pointer;
  transition: background 0.1s;
}

.cmd-item:hover,
.cmd-item--active {
  background: var(--layer-active);
}

.cmd-name {
  font-family: var(--font-mono);
  font-size: 13px;
  color: var(--accent);
  white-space: nowrap;
  flex-shrink: 0;
}

.cmd-tag {
  font-size: 10px;
  padding: 1px 5px;
  border-radius: 3px;
  white-space: nowrap;
  flex-shrink: 0;
}

.cmd-tag--prompt {
  color: var(--purple);
  background: var(--purple-dim);
}

.cmd-tag--local {
  color: var(--text-muted);
  background: var(--layer-glass);
  border: 1px solid var(--glass-border);
}

.cmd-tag--mcp {
  color: var(--accent);
  background: var(--accent-dim);
}

.cmd-item--readonly {
  cursor: default;
}

.cmd-item--readonly:hover,
.cmd-item--readonly.cmd-item--active {
  background: color-mix(in srgb, var(--layer-active) 72%, transparent);
}

.cmd-desc {
  font-size: 12px;
  color: var(--text-secondary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.cmd-policy-item {
  display: flex;
  flex-direction: column;
  gap: 7px;
  padding: 9px 10px;
  border-radius: var(--radius-sm);
}

.cmd-policy-item:hover {
  background: var(--layer-active);
}

.cmd-policy-main {
  display: flex;
  align-items: baseline;
  gap: 10px;
  min-width: 0;
}

.cmd-policy-actions {
  display: flex;
  gap: 6px;
  padding-left: 2px;
}

.cmd-policy-btn {
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-sm);
  background: color-mix(in srgb, var(--glass-bg) 36%, transparent);
  color: var(--text-muted);
  font-size: 11px;
  padding: 2px 7px;
  cursor: pointer;
}

.cmd-policy-btn.active {
  color: var(--accent);
  border-color: var(--accent);
  background: var(--accent-dim);
}

.cmd-loading,
.cmd-empty {
  padding: 16px;
  text-align: center;
  color: var(--text-muted);
  font-size: 13px;
}
</style>
