// frontend-next/src/features/message-display/ui/MessageList.tsx
'use client'

import { useEffect, type ReactNode, type RefObject } from 'react'
import { MessageItem } from './MessageItem'
import { MessageScrollButton } from './MessageScrollButton'
import { useMessageListScroll } from '../model/useMessageListScroll'
import type { Message } from '@/shared/types/api'

interface MessageListProps {
  messages: Message[]
  status: string
  hasMore?: boolean
  agentProvider?: string
  footer?: ReactNode
  onLoadMore?: () => void | Promise<void>
}

function emptyDescription(provider?: string): string {
  return provider === 'cursor'
    ? 'Send a prompt to start interacting with Cursor Agent'
    : 'Send a prompt to start interacting with Claude Code'
}

function LoadMoreObserver({
  rootRef,
  sentinelRef,
  enabled,
  onIntersect,
}: {
  rootRef: RefObject<HTMLDivElement | null>
  sentinelRef: RefObject<HTMLDivElement | null>
  enabled: boolean
  onIntersect: () => void
}) {
  useEffect(() => {
    const root = rootRef.current
    const sentinel = sentinelRef.current
    if (!root || !sentinel || !enabled) return

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0]?.isIntersecting) onIntersect()
      },
      { root, threshold: 0, rootMargin: '300px 0px 0px 0px' },
    )

    observer.observe(sentinel)
    return () => observer.disconnect()
  }, [rootRef, sentinelRef, enabled, onIntersect])

  return null
}

export function MessageList({
  messages,
  status,
  hasMore = false,
  agentProvider = 'claude',
  footer,
  onLoadMore,
}: MessageListProps) {
  const {
    containerRef,
    sentinelRef,
    showScrollBtn,
    loadingMore,
    setLoadingMore,
    checkNearBottom,
    scrollToBottom,
  } = useMessageListScroll(messages.length)

  async function handleLoadMore() {
    if (!hasMore || loadingMore || !onLoadMore) return
    const el = containerRef.current
    if (!el) return

    setLoadingMore(true)
    const prevScrollHeight = el.scrollHeight
    await onLoadMore()
    requestAnimationFrame(() => {
      const newScrollHeight = el.scrollHeight
      if (newScrollHeight !== prevScrollHeight) {
        el.scrollTop += newScrollHeight - prevScrollHeight
      }
      setLoadingMore(false)
    })
  }

  return (
    <div className="messages-shell">
      <div
        ref={containerRef}
        className="messages-area message-list"
        onScroll={checkNearBottom}
      >
        <div className="messages-content">
          <div ref={sentinelRef} className="load-more-sentinel">
            {loadingMore && <div className="load-more-indicator">Loading...</div>}
          </div>

          {messages.length === 0 ? (
            <div className="message-empty messages-empty-state">
              <div className="empty-icon">
                <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true">
                  <path d="M12 2L2 7l10 5 10-5-10-5z" />
                  <path d="M2 17l10 5 10-5" />
                  <path d="M2 12l10 5 10-5" />
                </svg>
              </div>
              <div className="empty-title">Velpos</div>
              <div className="empty-desc">{emptyDescription(agentProvider)}</div>
            </div>
          ) : (
            messages.map((msg, i) => (
              <MessageItem key={msg._id ?? msg.id ?? `msg-${i}`} message={msg} />
            ))
          )}

          {footer}
          {status === 'running' && messages.length > 0 && (
            <div className="message-list-running-footer" aria-hidden="true" />
          )}
        </div>
      </div>

      <MessageScrollButton visible={showScrollBtn} onClick={scrollToBottom} />

      {hasMore && onLoadMore && (
        <LoadMoreObserver
          rootRef={containerRef}
          sentinelRef={sentinelRef}
          enabled={!loadingMore}
          onIntersect={() => { void handleLoadMore() }}
        />
      )}
    </div>
  )
}

// frontend/src/features/message-display/ui/MessageList.vue
<script setup>
import { ref, watch, nextTick, onMounted, onBeforeUnmount, computed } from 'vue'
import MessageItem from './MessageItem.vue'

const props = defineProps({
  messages: {
    type: Array,
    required: true,
  },
  hasMore: {
    type: Boolean,
    default: false,
  },
  agentProvider: {
    type: String,
    default: 'claude',
  },
})

const emit = defineEmits(['load-more'])

const emptyDescription = computed(() => (
  props.agentProvider === 'cursor'
    ? 'Send a prompt to start interacting with Cursor Agent'
    : 'Send a prompt to start interacting with Claude Code'
))

const messagesContainer = ref(null)
const isNearBottom = ref(true)
const showScrollBtn = ref(false)
const loadingMore = ref(false)

const BOTTOM_THRESHOLD = 150

function checkNearBottom() {
  const el = messagesContainer.value
  if (!el) return
  const distanceFromBottom = el.scrollHeight - el.scrollTop - el.clientHeight
  isNearBottom.value = distanceFromBottom < BOTTOM_THRESHOLD
  showScrollBtn.value = !isNearBottom.value
}

function scrollToBottom() {
  const el = messagesContainer.value
  if (!el) return
  el.scrollTop = el.scrollHeight
  isNearBottom.value = true
  showScrollBtn.value = false
}

function handleScroll() {
  checkNearBottom()
}

// Sentinel IntersectionObserver for loading more
let sentinelObserver = null
const sentinelEl = ref(null)

function setupSentinel() {
  if (!messagesContainer.value || !sentinelEl.value) return
  if (sentinelObserver) sentinelObserver.disconnect()
  sentinelObserver = new IntersectionObserver(
    (entries) => {
      if (entries[0].isIntersecting && props.hasMore && !loadingMore.value) {
        triggerLoadMore()
      }
    },
    { root: messagesContainer.value, threshold: 0, rootMargin: '300px 0px 0px 0px' }
  )
  sentinelObserver.observe(sentinelEl.value)
}

async function triggerLoadMore() {
  const el = messagesContainer.value
  if (!el) return
  loadingMore.value = true
  if (sentinelObserver) sentinelObserver.disconnect()
  const prevScrollHeight = el.scrollHeight
  emit('load-more')
  await nextTick()
  await nextTick()
  await new Promise(resolve => requestAnimationFrame(resolve))
  const newScrollHeight = el.scrollHeight
  if (newScrollHeight !== prevScrollHeight) {
    el.scrollTop += newScrollHeight - prevScrollHeight
  }
  loadingMore.value = false
  await nextTick()
  setupSentinel()
}

// Auto-scroll when new messages arrive and user is near bottom
watch(() => props.messages.length, () => {
  if (isNearBottom.value) {
    nextTick(scrollToBottom)
  }
})

// MutationObserver for streaming content changes (DOM updates without message count change)
let observer = null
let scrollRafId = null

onMounted(() => {
  const el = messagesContainer.value
  if (!el) return

  observer = new MutationObserver(() => {
    if (isNearBottom.value && !scrollRafId) {
      scrollRafId = requestAnimationFrame(() => {
        scrollRafId = null
        scrollToBottom()
      })
    }
  })
  observer.observe(el, { childList: true, subtree: true, characterData: true })

  setupSentinel()
})

onBeforeUnmount(() => {
  if (observer) {
    observer.disconnect()
    observer = null
  }
  if (scrollRafId) {
    cancelAnimationFrame(scrollRafId)
    scrollRafId = null
  }
  if (sentinelObserver) {
    sentinelObserver.disconnect()
    sentinelObserver = null
  }
})
</script>

<template>
  <div class="messages-shell">
    <div ref="messagesContainer" class="messages-area" @scroll="handleScroll">
      <div class="messages-content">
        <div ref="sentinelEl" class="load-more-sentinel">
          <div v-if="loadingMore" class="load-more-indicator">Loading...</div>
        </div>
        <div v-if="messages.length === 0" class="empty-state">
          <div class="empty-icon">
            <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
              <path d="M12 2L2 7l10 5 10-5-10-5z"/>
              <path d="M2 17l10 5 10-5"/>
              <path d="M2 12l10 5 10-5"/>
            </svg>
          </div>
          <div class="empty-title">Velpos</div>
          <div class="empty-desc">{{ emptyDescription }}</div>
        </div>
        <MessageItem
          v-for="msg in messages"
          :key="msg._id ?? msg.id"
          :message="msg"
        />
        <slot name="footer"></slot>
      </div>
    </div>
    <button
      v-if="showScrollBtn"
      class="scroll-bottom-btn"
      @click="scrollToBottom"
      title="Scroll to bottom"
      aria-label="Scroll to bottom"
    >
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <polyline points="6 9 12 15 18 9"/>
      </svg>
    </button>
  </div>
</template>

<style scoped>
.messages-shell {
  flex: 1;
  min-height: 0;
  position: relative;
  display: flex;
}

.load-more-sentinel {
  height: 1px;
  width: 100%;
}

.load-more-indicator {
  text-align: center;
  padding: 12px 0;
  font-size: 12px;
  color: var(--text-muted);
}

.messages-area {
  flex: 1;
  overflow-y: auto;
  overflow-anchor: none;
  padding: 24px 0 clamp(300px, 34vh, 380px);
  display: flex;
  flex-direction: column;
  position: relative;
  background:
    radial-gradient(circle at 50% 0%, var(--accent-dim), transparent 26%),
    transparent;
  scroll-padding-bottom: clamp(300px, 34vh, 380px);
}

.messages-content {
  width: 100%;
  margin: 0;
  padding: 0 clamp(18px, 2.4vw, 32px);
  display: flex;
  flex-direction: column;
  gap: 0;
}

.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  margin: auto;
  gap: 12px;
  min-height: 42vh;
  padding: 32px;
  color: var(--text-muted);
  text-align: center;
}

.empty-icon {
  width: 76px;
  height: 76px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--accent);
  background: var(--layer-active);
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-2xl);
  box-shadow: var(--shadow-active);
  opacity: 0.86;
  margin-bottom: 8px;
}

.empty-title {
  font-size: 22px;
  font-weight: 700;
  color: var(--text-primary);
  letter-spacing: -0.02em;
}

.empty-desc {
  max-width: 360px;
  font-size: 13px;
  line-height: 1.6;
  color: var(--text-secondary);
}

.scroll-bottom-btn {
  position: absolute;
  left: 50%;
  bottom: calc(clamp(300px, 34vh, 380px) - 46px);
  transform: translateX(-50%);
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: var(--touch-target);
  min-width: var(--touch-target);
  height: var(--touch-target);
  min-height: var(--touch-target);
  padding: 0;
  box-sizing: border-box;
  border-radius: 999px;
  background: var(--glass-bg-strong);
  border: 1px solid var(--glass-border);
  color: var(--text-secondary);
  cursor: pointer;
  box-shadow: var(--shadow-glass);
  backdrop-filter: blur(var(--glass-blur)) saturate(var(--glass-saturate));
  -webkit-backdrop-filter: blur(var(--glass-blur)) saturate(var(--glass-saturate));
  transition: background var(--transition-fast), color var(--transition-fast), border-color var(--transition-fast), box-shadow var(--transition-fast), transform var(--transition-fast);
  z-index: 30;
}

.scroll-bottom-btn:hover {
  background: var(--layer-active);
  color: var(--accent);
  border-color: var(--accent);
  box-shadow: var(--shadow-active);
  transform: translateX(-50%) translateY(-1px);
}
</style>
