// frontend-next/src/features/message-display/ui/UserChoiceBlock.tsx
'use client'

import { useState, useCallback } from 'react'

const OTHER_LABEL = '__other__'

interface Question {
  question: string
  header?: string
  multiSelect?: boolean
  options?: Array<{ label: string; description?: string }>
}

interface Props {
  block: {
    input?: { questions?: Question[] }
    questions?: Question[]
    tool_name?: string
  }
  answered: boolean
  onAnswer: (data: { answers: Record<string, string> }) => void
}

export function UserChoiceBlock({ block, answered, onAnswer }: Props) {
  const [selections, setSelections] = useState<Record<string, string | string[]>>({})
  const [otherTexts, setOtherTexts] = useState<Record<string, string>>({})
  const questions = block.questions || block.input?.questions || []

  const hasBuiltinOther = useCallback((q: Question) => {
    return (q.options || []).some(opt => opt.label.toLowerCase() === 'other')
  }, [])

  const isOtherOpt = useCallback((opt: { label: string }) => {
    return opt.label.toLowerCase() === 'other'
  }, [])

  function toggleOption(qIdx: number, optLabel: string, multiSelect?: boolean) {
    const key = `q${qIdx}`
    setSelections(prev => {
      if (multiSelect) {
        const current = (prev[key] as string[]) || []
        if (current.includes(optLabel)) {
          return { ...prev, [key]: current.filter(l => l !== optLabel) }
        }
        return { ...prev, [key]: [...current, optLabel] }
      }
      return { ...prev, [key]: optLabel }
    })
  }

  function isSelected(qIdx: number, optLabel: string, multiSelect?: boolean): boolean {
    const key = `q${qIdx}`
    const val = selections[key]
    if (multiSelect) {
      return (val as string[] || []).includes(optLabel)
    }
    return val === optLabel
  }

  function isOtherSelected(qIdx: number, multiSelect?: boolean): boolean {
    return isSelected(qIdx, OTHER_LABEL, multiSelect)
  }

  function hasAnswered(qIdx: number): boolean {
    const key = `q${qIdx}`
    const val = selections[key]
    if (Array.isArray(val)) {
      if (val.length === 0) return false
      if (val.includes(OTHER_LABEL)) {
        return !!(otherTexts[key] || '').trim()
      }
      return true
    }
    if (val === OTHER_LABEL) {
      return !!(otherTexts[key] || '').trim()
    }
    return !!val
  }

  const allAnswered = questions.every((_, i) => hasAnswered(i))

  function submitAnswers() {
    const answers: Record<string, string> = {}
    questions.forEach((q, i) => {
      const key = `q${i}`
      const val = selections[key]
      if (Array.isArray(val)) {
        const resolved = val.map(v => v === OTHER_LABEL ? (otherTexts[key] || '').trim() : v)
        answers[q.question] = resolved.join(', ')
      } else if (val === OTHER_LABEL) {
        answers[q.question] = (otherTexts[key] || '').trim()
      } else {
        answers[q.question] = val || ''
      }
    })
    onAnswer({ answers })
  }

  if (questions.length === 0) return null

  return (
    <div className={`user-choice-block ${answered ? 'choice-answered' : ''}`}>
      <div className="choice-header">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <circle cx="12" cy="12" r="10" />
          <line x1="12" y1="8" x2="12" y2="12" />
          <line x1="12" y1="16" x2="12.01" y2="16" />
        </svg>
        <span>User Input Required</span>
      </div>

      {questions.map((q, qIdx) => (
        <div key={qIdx} className="question-group">
          {q.header && (
            <div className="question-header">
              <span className="question-chip">{q.header}</span>
            </div>
          )}
          <div className="question-text">{q.question}</div>

          <div className="options-list">
            {(q.options || []).map((opt, oIdx) => {
              if (!isOtherOpt(opt)) {
                return (
                  <button
                    key={oIdx}
                    className={`option-btn ${isSelected(qIdx, opt.label, q.multiSelect) ? 'option-selected' : ''} ${q.multiSelect ? 'option-multi' : ''}`}
                    disabled={answered}
                    onClick={() => toggleOption(qIdx, opt.label, q.multiSelect)}
                  >
                    <span className="option-indicator">
                      {q.multiSelect ? (
                        <span className="checkbox">
                          {isSelected(qIdx, opt.label, true) && (
                            <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor">
                              <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z" />
                            </svg>
                          )}
                        </span>
                      ) : (
                        <span className="radio">
                          {isSelected(qIdx, opt.label, false) && <span className="radio-dot" />}
                        </span>
                      )}
                    </span>
                    <span className="option-content">
                      <span className="option-label">{opt.label}</span>
                      {opt.description && <span className="option-desc">{opt.description}</span>}
                    </span>
                  </button>
                )
              }
              return null
            })}

            {(q.options || []).some(opt => isOtherOpt(opt)) && (
              <button
                className={`option-btn option-other ${isOtherSelected(qIdx, q.multiSelect) ? 'option-selected' : ''}`}
                disabled={answered}
                onClick={() => toggleOption(qIdx, OTHER_LABEL, q.multiSelect)}
              >
                <span className="option-indicator">
                  {q.multiSelect ? (
                    <span className="checkbox">
                      {isOtherSelected(qIdx, true) && (
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor">
                          <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z" />
                        </svg>
                      )}
                    </span>
                  ) : (
                    <span className="radio">
                      {isOtherSelected(qIdx, false) && <span className="radio-dot" />}
                    </span>
                  )}
                </span>
                <span className="option-content">
                  <span className="option-label">Other</span>
                  <span className="option-desc">{q.options?.find(o => isOtherOpt(o))?.description || 'Provide your own answer'}</span>
                </span>
              </button>
            )}

            {!hasBuiltinOther(q) && (
              <button
                className={`option-btn option-other ${isOtherSelected(qIdx, q.multiSelect) ? 'option-selected' : ''}`}
                disabled={answered}
                onClick={() => toggleOption(qIdx, OTHER_LABEL, q.multiSelect)}
              >
                <span className="option-indicator">
                  {q.multiSelect ? (
                    <span className="checkbox">
                      {isOtherSelected(qIdx, true) && (
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor">
                          <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z" />
                        </svg>
                      )}
                    </span>
                  ) : (
                    <span className="radio">
                      {isOtherSelected(qIdx, false) && <span className="radio-dot" />}
                    </span>
                  )}
                </span>
                <span className="option-content">
                  <span className="option-label">Other</span>
                  <span className="option-desc">Provide your own answer</span>
                </span>
              </button>
            )}
          </div>

          {isOtherSelected(qIdx, q.multiSelect) && !answered && (
            <div className="other-input-wrap">
              <textarea
                className="other-input"
                value={otherTexts[`q${qIdx}`] || ''}
                onChange={(e) => setOtherTexts(prev => ({ ...prev, [`q${qIdx}`]: e.target.value }))}
                placeholder="Type your answer here..."
                rows={2}
              />
            </div>
          )}
        </div>
      ))}

      {!answered && questions.length > 0 && (
        <button className="submit-btn" disabled={!allAnswered} onClick={submitAnswers}>
          Submit
        </button>
      )}
      {answered && <div className="answered-badge">Answered</div>}
    </div>
  )
}

// frontend/src/features/message-display/ui/UserChoiceBlock.vue
<script setup>
import { ref, computed } from 'vue'

const props = defineProps({
  block: { type: Object, required: true },
  answered: { type: Boolean, default: false },
})

const emit = defineEmits(['answer'])

// Track selected answers per question
const selections = ref({})
// Track "Other" free-text input per question
const otherTexts = ref({})
const OTHER_LABEL = '__other__'

const questions = computed(() => props.block.input?.questions || [])

function hasBuiltinOther(q) {
  return (q.options || []).some(opt => opt.label.toLowerCase() === 'other')
}

function isOtherOpt(opt) {
  return opt.label.toLowerCase() === 'other'
}

function toggleOption(qIdx, optLabel, multiSelect) {
  const key = `q${qIdx}`
  if (multiSelect) {
    const current = selections.value[key] || []
    if (current.includes(optLabel)) {
      selections.value[key] = current.filter(l => l !== optLabel)
    } else {
      selections.value[key] = [...current, optLabel]
    }
  } else {
    selections.value[key] = optLabel
  }
}

function isSelected(qIdx, optLabel, multiSelect) {
  const key = `q${qIdx}`
  const val = selections.value[key]
  if (multiSelect) {
    return (val || []).includes(optLabel)
  }
  return val === optLabel
}

function isOtherSelected(qIdx, multiSelect) {
  return isSelected(qIdx, OTHER_LABEL, multiSelect)
}

function hasAnswered(qIdx) {
  const key = `q${qIdx}`
  const val = selections.value[key]
  if (Array.isArray(val)) {
    if (val.length === 0) return false
    if (val.includes(OTHER_LABEL)) {
      return !!(otherTexts.value[key] || '').trim()
    }
    return true
  }
  if (val === OTHER_LABEL) {
    return !!(otherTexts.value[key] || '').trim()
  }
  return !!val
}

const allAnswered = computed(() => {
  return questions.value.every((_, i) => hasAnswered(i))
})

function submitAnswers() {
  const answers = {}
  questions.value.forEach((q, i) => {
    const key = `q${i}`
    const val = selections.value[key]
    if (Array.isArray(val)) {
      const resolved = val.map(v => v === OTHER_LABEL ? (otherTexts.value[key] || '').trim() : v)
      answers[q.question] = resolved.join(', ')
    } else if (val === OTHER_LABEL) {
      answers[q.question] = (otherTexts.value[key] || '').trim()
    } else {
      answers[q.question] = val || ''
    }
  })
  emit('answer', { answers })
}
</script>

<template>
  <div class="user-choice-block" :class="{ 'choice-answered': answered }">
    <div class="choice-header">
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <circle cx="12" cy="12" r="10"/>
        <line x1="12" y1="8" x2="12" y2="12"/>
        <line x1="12" y1="16" x2="12.01" y2="16"/>
      </svg>
      <span>User Input Required</span>
    </div>

    <div v-for="(q, qIdx) in questions" :key="qIdx" class="question-group">
      <div class="question-header" v-if="q.header">
        <span class="question-chip">{{ q.header }}</span>
      </div>
      <div class="question-text">{{ q.question }}</div>

      <div class="options-list">
        <template v-for="(opt, oIdx) in (q.options || [])" :key="oIdx">
          <button
            v-if="!isOtherOpt(opt)"
            class="option-btn"
            :class="{
              'option-selected': isSelected(qIdx, opt.label, q.multiSelect),
              'option-multi': q.multiSelect,
            }"
            :disabled="answered"
            @click="toggleOption(qIdx, opt.label, q.multiSelect)"
          >
            <span class="option-indicator">
              <span v-if="q.multiSelect" class="checkbox">
                <svg v-if="isSelected(qIdx, opt.label, true)" width="12" height="12" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/>
                </svg>
              </span>
              <span v-else class="radio">
                <span v-if="isSelected(qIdx, opt.label, false)" class="radio-dot"/>
              </span>
            </span>
            <span class="option-content">
              <span class="option-label">{{ opt.label }}</span>
              <span v-if="opt.description" class="option-desc">{{ opt.description }}</span>
            </span>
          </button>

          <button
            v-else
            class="option-btn option-other"
            :class="{ 'option-selected': isOtherSelected(qIdx, q.multiSelect) }"
            :disabled="answered"
            @click="toggleOption(qIdx, OTHER_LABEL, q.multiSelect)"
          >
            <span class="option-indicator">
              <span v-if="q.multiSelect" class="checkbox">
                <svg v-if="isOtherSelected(qIdx, true)" width="12" height="12" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/>
                </svg>
              </span>
              <span v-else class="radio">
                <span v-if="isOtherSelected(qIdx, false)" class="radio-dot"/>
              </span>
            </span>
            <span class="option-content">
              <span class="option-label">Other</span>
              <span class="option-desc">{{ opt.description || 'Provide your own answer' }}</span>
            </span>
          </button>
        </template>

        <button
          v-if="!hasBuiltinOther(q)"
          class="option-btn option-other"
          :class="{ 'option-selected': isOtherSelected(qIdx, q.multiSelect) }"
          :disabled="answered"
          @click="toggleOption(qIdx, OTHER_LABEL, q.multiSelect)"
        >
          <span class="option-indicator">
            <span v-if="q.multiSelect" class="checkbox">
              <svg v-if="isOtherSelected(qIdx, true)" width="12" height="12" viewBox="0 0 24 24" fill="currentColor">
                <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/>
              </svg>
            </span>
            <span v-else class="radio">
              <span v-if="isOtherSelected(qIdx, false)" class="radio-dot"/>
            </span>
          </span>
          <span class="option-content">
            <span class="option-label">Other</span>
            <span class="option-desc">Provide your own answer</span>
          </span>
        </button>
      </div>

      <div v-if="isOtherSelected(qIdx, q.multiSelect) && !answered" class="other-input-wrap">
        <textarea
          class="other-input"
          :value="otherTexts[`q${qIdx}`] || ''"
          @input="otherTexts[`q${qIdx}`] = $event.target.value"
          placeholder="Type your answer here..."
          rows="2"
        />
      </div>
    </div>

    <button
      v-if="!answered && questions.length > 0"
      class="submit-btn"
      :disabled="!allAnswered"
      @click="submitAnswers"
    >
      Submit
    </button>
    <div v-if="answered" class="answered-badge">Answered</div>
  </div>
</template>

<style scoped>
.user-choice-block {
  background: var(--bg-secondary);
  border: 1px solid var(--accent);
  border-radius: var(--radius-md);
  padding: 16px;
  margin: 8px 0;
}

.choice-answered {
  opacity: 0.7;
  border-color: var(--border);
}

.choice-header {
  display: flex;
  align-items: center;
  gap: 8px;
  color: var(--accent);
  font-weight: 600;
  font-size: 13px;
  margin-bottom: 12px;
}

.question-group {
  margin-bottom: 12px;
}

.question-header {
  margin-bottom: 4px;
}

.question-chip {
  display: inline-block;
  background: var(--accent-dim);
  color: var(--accent);
  font-size: 11px;
  font-weight: 600;
  padding: 2px 8px;
  border-radius: 10px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.question-text {
  color: var(--text-primary);
  font-size: 14px;
  margin-bottom: 8px;
  line-height: 1.5;
}

.options-list {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.option-btn {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  padding: 10px 12px;
  background: var(--bg-primary);
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  cursor: pointer;
  text-align: left;
  transition: all var(--transition-fast);
  color: var(--text-primary);
  font-family: inherit;
  font-size: 13px;
}

.option-btn:not(:disabled):hover {
  border-color: var(--accent);
  background: var(--bg-hover);
  transform: translateX(2px);
}

.option-btn.option-selected {
  border-color: var(--accent);
  background: var(--accent-dim);
}

.option-btn:disabled {
  cursor: default;
  opacity: 0.6;
}

.option-indicator {
  flex-shrink: 0;
  margin-top: 2px;
}

.radio {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 16px;
  height: 16px;
  border: 2px solid var(--text-muted);
  border-radius: 50%;
}

.option-selected .radio {
  border-color: var(--accent);
}

.radio-dot {
  width: 8px;
  height: 8px;
  background: var(--accent);
  border-radius: 50%;
}

.checkbox {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 16px;
  height: 16px;
  border: 2px solid var(--text-muted);
  border-radius: 3px;
}

.option-selected .checkbox {
  background: var(--accent);
  border-color: var(--accent);
  color: var(--text-on-accent);
}

.option-content {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.option-label {
  font-weight: 500;
}

.option-desc {
  color: var(--text-muted);
  font-size: 12px;
  line-height: 1.4;
}

.submit-btn {
  margin-top: 12px;
  padding: 8px 20px;
  background: var(--accent);
  color: var(--text-on-accent);
  border: none;
  border-radius: var(--radius-sm);
  font-weight: 600;
  font-size: 13px;
  cursor: pointer;
  transition: opacity var(--transition-fast);
}

.submit-btn:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.submit-btn:not(:disabled):hover {
  transform: translateY(-1px);
  box-shadow: var(--shadow-md);
}

.submit-btn:active:not(:disabled) {
  transform: translateY(0) scale(0.97);
  transition-duration: 100ms;
}

.answered-badge {
  margin-top: 8px;
  color: var(--green);
  font-size: 12px;
  font-weight: 600;
}

.other-input-wrap {
  margin-top: 8px;
  padding-left: 26px;
}

.other-input {
  width: 100%;
  padding: 8px 12px;
  background: var(--bg-primary);
  border: 1px solid var(--accent);
  border-radius: var(--radius-sm);
  color: var(--text-primary);
  font-family: inherit;
  font-size: 13px;
  line-height: 1.5;
  resize: vertical;
  min-height: 40px;
}

.other-input:focus {
  outline: none;
  box-shadow: 0 0 0 2px var(--accent-dim);
}

.other-input::placeholder {
  color: var(--text-muted);
}
</style>
